web/src/main/java/com/microsoft/applicationinsights/web/extensibility/modules/WebSessionTrackingTelemetryModule.java
web/src/main/java/com/microsoft/applicationinsights/web/internal/ServletUtils.java
web/src/main/java/com/microsoft/applicationinsights/web/internal/cookies/HttpCookieFactory.java
web/src/test/java/com/microsoft/applicationinsights/web/internal/ServletUtilsTests.java
web/src/test/java/com/microsoft/applicationinsights/web/internal/cookies/SessionCookieTests.java

The session timeout can now be configured in two ways:
1. If a servlet level session (HttpSession) was already created, the session timeout will be taken from the session.
2. If no servlet level session exists, the timeout will be taken from from the application descriptor (web.xml).
3. Otherwise, default timeout.

Support dynamic session timeout

---

core/src/main/java/com/microsoft/applicationinsights/internal/config/TelemetryConfigurationFactory.java

In case of a failure to scan for PC modules in a JBoss web server, I simply load the modules by providing hard-coded module names.
This is only a TEMPORARY solution until we'll investigate and understand why the annotation scanner fail to run. I don't think we should invest more on it right now since the ROI is low (we get the same result with hard-coded module names but with the price of ugly workaround).
Guy, note that I saw only 'private byte' and 'process CPU' PCs have been registered. Does it make sense?

Loading default PCs as fallback for JBoss web servers

---

core/src/main/java/com/microsoft/applicationinsights/internal/config/TelemetryConfigurationFactory.java

When no configuration file found, we still need to set the default channel, so the user won't need to set it by himself.

Setting default channel when no configuration file found

---

web/src/main/java/com/microsoft/applicationinsights/web/extensibility/modules/WebSessionTrackingTelemetryModule.java
web/src/main/java/com/microsoft/applicationinsights/web/extensibility/modules/WebUserTrackingTelemetryModule.java
web/src/test/java/com/microsoft/applicationinsights/web/extensibility/modules/WebSessionTrackingTelemetryModuleTests.java
web/src/test/java/com/microsoft/applicationinsights/web/extensibility/modules/WebUserTrackingTelemetryModuleTests.java
web/src/test/java/com/microsoft/applicationinsights/web/utils/HttpHelper.java
web/src/test/resources/ApplicationInsights.xml

Disabling user/session cookies generation by defaulting the modules to NOT generate cookies. Only if a cookie contains in the request, the module will use it information to update the telemetry sent to AI BE.

Disabling user/session cookies generation

---

core/src/main/java/com/microsoft/applicationinsights/internal/schemav2/RemoteDependencyData.java
core/src/main/java/com/microsoft/applicationinsights/telemetry/Duration.java
core/src/main/java/com/microsoft/applicationinsights/telemetry/RemoteDependencyTelemetry.java
core/src/test/java/com/microsoft/applicationinsights/telemetry/DurationTest.java
core/src/test/java/com/microsoft/applicationinsights/telemetry/RemoteDependencyTelemetryTest.java
samples/src/main/java/com/microsoft/applicationinsights/sample/AiCore.java

PR contains the following:
1. Removing set/get value method from dependency telemetry.
2. Used the duration value in the json sent to the BE.

Removing set/get value functions and fixing duration in json

---

core/src/main/java/com/microsoft/applicationinsights/internal/channel/common/TransmissionNetworkOutput.java
web/src/main/java/com/microsoft/applicationinsights/web/extensibility/modules/WebRequestTrackingTelemetryModule.java

I have an API which a returns `201` successful status code when an entity is created. Insights is currently incorrectly logging these requests as unsuccessful:

Handle all successful status codes

---

agent/build.gradle
collectd/build.gradle
distributions/build.gradle

Incremented Gradle Shadow plugin to version 1.2.3 as this version supports Gradle 2.11 and newer
More information:
https://github.com/johnrengelman/shadow/releases/tag/1.2.3

Fix build problems when using Gradle 2.11+

---

web/src/main/java/com/microsoft/applicationinsights/web/internal/ApplicationInsightsHttpResponseWrapper.java

ApplicationInsightsHttpResponseWrapper does not always set HTTP status code properly resulting in displaying code '200' in Azure portal even for failed requests.
The reason is the missing override for setStatus(int sc, String sm) method.

HTTP response code is not always set properly

---

agent/src/main/java/com/microsoft/applicationinsights/agent/internal/agent/AgentImplementation.java

Appending 'file:/' at the start of a file path works only under windows, where paths start with the drive letter (-> file:/c:/...).
On Unix, paths start with /, resulting in a URL like file://var/lib/... - this is then interpreted as a file on the host 'var', in directory 'lib/...'
This fix utilizes Java to source the URL for a file, instead of crafting it manually.

Fixing URL generation from file path.

---

logging/log4j1_2/appenderSrc/main/java/com/microsoft/applicationinsights/log4j/v1_2/internal/ApplicationInsightsLogEvent.java
logging/log4j2/appenderSrc/main/java/com/microsoft/applicationinsights/log4j/v2/internal/ApplicationInsightsLogEvent.java
logging/logback/appenderSrc/main/java/com/microsoft/applicationinsights/logback/internal/ApplicationInsightsLogEvent.java

Details of the Logging Contexts (MDC, ThreadContext, etc) are not sent to AI - this fix adds them as Custom Properties for each logging framework.

Propagate log context data

---

core/src/main/java/com/microsoft/applicationinsights/internal/channel/common/ApacheSender43.java

Modified ApacheSender43 to use http.proxyHost (and http.proxyPort) if defined. 
This allows using an HTTP proxy

HTTP proxy support: use proxyHost and proxyPort if defined

---

web/src/main/java/com/microsoft/applicationinsights/web/extensibility/modules/WebRequestTrackingTelemetryModule.java

Redirects shouldn't be considered failures, as reported in #281

Consider 4xx and 5xx as failures

---

web/src/main/java/com/microsoft/applicationinsights/web/internal/WebRequestTrackingFilter.java

Cleanup ThreadContext in finally-clause

---

core/src/main/java/com/microsoft/applicationinsights/internal/agent/AgentConnector.java
web/src/main/java/com/microsoft/applicationinsights/web/internal/WebRequestTrackingFilter.java

Check that the agent jar is loaded before attempting to register with it. If not loaded, skip registration and avoid scary error message
fix #317

Avoid error message when agent is not loaded

---

core/src/main/java/com/microsoft/applicationinsights/internal/config/PerformanceCountersXmlElement.java
core/src/main/java/com/microsoft/applicationinsights/internal/config/TelemetryConfigurationFactory.java
core/src/main/java/com/microsoft/applicationinsights/internal/perfcounter/PerformanceCounterContainer.java
core/src/test/java/com/microsoft/applicationinsights/internal/perfcounter/PerformanceCounterContainerTest.java

Allow users to set the cadence of performance counter collection

Allow configuration of PC collection cadence

---

gradle/common-java.gradle

Gradle3 requires Java 7 and above to run. We support JDK 6 and test it internally by running tests against JDK6.
Add a property  `JDKToUse` and setting it to the location of the JDK using `-P` to instruct gradle to use a different JDK for buildling and testing 
See [here](https://docs.gradle.org/current/userguide/java_plugin.html#sec:java_cross_compilation) for more details. 
Added a small tweak for the above to work better on Windows (append .exe to the file names)

Use the non-default JDK when JDKToUse property is defined

---

README.md

In some cases you can see the error below when starting a JVM with Application. This error is because you need the VC2013 redistributable pacakge which is not always installed on non-developer machines.
```
INFO   | jvm 1    | 2016/12/22 17:36:42.556 | AI: ERROR 22-12-2016 17:36, 1: Failed to load native dll, Windows performance counters will not be used. Please make sure that Visual C++ Redistributable is properly installed: Expecting an absolute path of the library: ..\temp\AISDK\native\1.0.6\applicationinsights-core-native-win64.dll.
INFO   | jvm 1    | 2016/12/22 17:36:42.556 | AI: ERROR 22-12-2016 17:36, 1: Failed to initialize JNI connection.
```

Added VS2013 Redist Line

---

core/build.gradle

So the org.objectweb package doesn't end up in the root of the core jar.
This causes us a SecurityException due to another version of the asm jar (3.2 in our case) in our deployed WAR.
I ran the gradle build locally and all the existing tests here still pass.

Updated the agent project not to be transitive when resolved for core

---

core/src/main/java/com/microsoft/applicationinsights/internal/quickpulse/DefaultQuickPulseDataFetcher.java
core/src/main/java/com/microsoft/applicationinsights/internal/quickpulse/DefaultQuickPulseDataSender.java
core/src/main/java/com/microsoft/applicationinsights/internal/quickpulse/DefaultQuickPulsePingSender.java

This will get us over the hump of providing Quick Pulse until we can implement the latest features.
**This PR contains the following fixes for QuickPulse in Java.**
- Clean up of string builder JSON creation
- Changing telemetry names to match version 2.2.0-738
- Fix bug where QP would exhaust the PoolingHttpClientConnectionManager connections
**It does not implement**
- Aggregation
- Per process CPU time
- Real time error and exception messages

Fix low hanging issues for "QuickPulse Broken #360"

---

core/src/main/java/com/microsoft/applicationinsights/internal/agent/CoreAgentNotificationsHandler.java

The HTTP Dependencies durations were being recorded with nanosecond granularity. This PR corrects that behavior and adds `rt.services.visualstudio.com` to the filtering.

Added QuickPulse URL filter and fixed duration

---

core/src/main/java/com/microsoft/applicationinsights/internal/channel/common/TransmissionNetworkOutput.java

The exception seen with the new changes pulled in is now a ConnectException instead of IOException that we were seeing before

Delaying retry on send when ConnectionException is thrown

---

core/src/main/java/com/microsoft/applicationinsights/internal/channel/common/TransmissionNetworkOutput.java

I get different exception between production and sandbox environment. I get the exact log lines "Failed to send, wrong host address or cannot reach address due to network issues" which is the UnknownHostException

Delaying retry on send when HostUnknownException is thrown

---

CHANGELOG.md
core/src/main/java/com/microsoft/applicationinsights/internal/config/TelemetryConfigurationFactory.java
core/src/test/java/com/microsoft/applicationinsights/internal/config/TelemetryConfigurationFactoryTest.java

None of the other SDKs use the `APPLICATION_INSIGHTS_IKEY` environment variable to configure the instrumentation key for Application Insights and instead use `APPINSIGHTS_INSTRUMENTATIONKEY`.
For consistency with the other SDKs (e.g. [Dot-Net](https://aka.ms/n2ruy1) or [Node](https://aka.ms/v8r0pk)) this Java SDK should also support the  more common environment variable name to avoid confusion for developers who have experience with the non-Java SDKs.

Add second environment variable to configure ikey

---

core/src/main/java/com/microsoft/applicationinsights/TelemetryClient.java
core/src/test/java/com/microsoft/applicationinsights/TelemetryClientTests.java

Do not set telemetry timestamp if it already exists
Fixes a bug where track function of TelemetryClient class is overwriting the timestamp that was previously set for the telemetry. This results in not able to specify the order of different events.

Fixes custom telemetry timestamp bug

---

CHANGELOG.md
agent/src/main/java/com/microsoft/applicationinsights/agent/internal/agent/DefaultMethodVisitor.java
agent/src/main/java/com/microsoft/applicationinsights/agent/internal/agent/redis/JedisClassDataProvider.java
agent/src/main/java/com/microsoft/applicationinsights/agent/internal/agent/redis/JedisMethodVisitor.java
agent/src/main/java/com/microsoft/applicationinsights/agent/internal/agent/redis/JedisMethodVisitorV2.java
agent/src/main/java/com/microsoft/applicationinsights/agent/internal/coresync/AgentNotificationsHandler.java
agent/src/main/java/com/microsoft/applicationinsights/agent/internal/coresync/InstrumentedClassType.java
agent/src/main/java/com/microsoft/applicationinsights/agent/internal/coresync/impl/ImplementationsCoordinator.java
core/src/main/java/com/microsoft/applicationinsights/internal/agent/CoreAgentNotificationsHandler.java

Switch to a basic version which relies on DefaultMethodVisitor for most of the work. The only thing the new class (JedisMethodVisitorV2) overrides is the "onStart" method since we want the type of dependency to be "Redis" as opposed to "OTHER".

Fixing reliability issue with JedisMethodVisitor.

---

CHANGELOG.md
core/src/main/java/com/microsoft/applicationinsights/internal/channel/common/TransmissionNetworkOutput.java

I originally made changes to delay retries on specific exceptions but users are hitting this for more reasons such as working offline, working through a proxy, etc. They see >500 requests in less than a minute in these cases which have taken down their proxy. I don't know any reason why there shouldn't be backoff if there is an exception in general instead of constantly retrying. I made the change to delay no matter the exception. I tested on my personal machine and I stopped seeing the constant retries every second.

Delay retrying to send telemetry if an exception is hit

---

CHANGELOG.md
core/src/main/java/com/microsoft/applicationinsights/telemetry/JsonTelemetryDataSerializer.java
core/src/test/java/com/microsoft/applicationinsights/telemetry/JsonTelemetryDataSerializerTest.java

Fix #436 
This was a sanitization issue. Adding quotes around write(String name, com.microsoft.applicationinsights.internal.schemav2.SeverityLevel value) method fixed it.

 Adding quotes around security level write method to fix serialization

---

core/src/main/java/com/microsoft/applicationinsights/telemetry/JsonTelemetryDataSerializer.java

Fix #443 
Updating the sanitization logic. There is no need to sanitize single quotes according to JSON Standards. 
(https://commons.apache.org/proper/commons-lang/apidocs/org/apache/commons/lang3/StringEscapeUtils.html#escapeJson-java.lang.String-)
Further, I am not sure what all types of languages and character schema we support. However, this sanitization logic matches the dot net logic in most possible ways.

removing escape for single quote, not needed for Json sanitization

---

gradle/common-java.gradle

I added some more detail to the output of the test run, but it's behind gradle's `--info` and `--debug` command line options. I also added a simple message displaying the results of the top-level test suite. This should help when debugging unit tests.

Log test status

---

core/src/main/java/com/microsoft/applicationinsights/internal/perfcounter/CpuPerformanceCounterCalculator.java

Corrected issue where the constructor was expecting the `com.sun.management` implementation of the OperatingSystemMXBean.
Since there isn't a getter for ProcessCpuTime in the OperatingSystemMXBean interface, I opted to lookup the metric in the MBeanServer.
Fix #432

Fixed cast error in CpuPerformanceCounterCalculator constructor 

---

CHANGELOG.md
core/src/main/java/com/microsoft/applicationinsights/internal/channel/samplingV2/FixedRateSamplingTelemetryProcessor.java
core/src/main/java/com/microsoft/applicationinsights/internal/channel/samplingV2/SamplingScoreGeneratorV2.java
core/src/main/java/com/microsoft/applicationinsights/internal/config/ParamExcludedTypeXmlElement.java
core/src/main/java/com/microsoft/applicationinsights/internal/config/ParamIncludedTypeXmlElement.java
core/src/main/java/com/microsoft/applicationinsights/internal/config/TelemetryProcessorCreator.java
core/src/main/java/com/microsoft/applicationinsights/internal/config/TelemetryProcessorXmlElement.java
core/src/test/java/com/microsoft/applicationinsights/TestFramework/StubTelemetryChannel.java
core/src/test/java/com/microsoft/applicationinsights/internal/channel/samplingV2/FixedRateSamplingTelemetryProcessorTest.java
core/src/test/java/com/microsoft/applicationinsights/internal/channel/samplingV2/SamplingScoreGeneratorV2Test.java
core/src/test/java/com/microsoft/applicationinsights/internal/config/TelemetryProcessorCreatorTest.java
core/src/test/java/com/microsoft/applicationinsights/internal/config/TestProcessorThatThrowsOnIncludedAndExcludedTypes.java
core/src/test/java/com/microsoft/applicationinsights/internal/config/ValidProcessorWithIncludeExcludeType.java

Introducing Fixed Rate Sampling v2 using TelemetryProcessors architecture. This is in addition to current FixedRateSampler and with then next major version this will be the standard. 
Eg. of creating FixedRateTelemetryProcessor:
In the ApplicationInsights.xml file add the following:
```
<TelemetryProcessors>
<BuiltInProcessors>
<Processor type = "FixedRateSamplingTelemetryProcessor">
<Add name = "SamplingPercentage" value = "50" />
<ExcludedTypes>
<ExcludedType>Request</ExcludedType>
</ExcludedTypes>
<IncludedTypes>
<IncludedType>Request</IncludedType>
<IncludedType>Trace</IncludedType>
<IncludedType>Dependency</IncludedType>
<IncludedType>Exception</IncludedType>
</IncludedTypes>
</Processor>
</BuiltInProcessors>
</TelemetryProcessors>
```
The sampling percentage should be between 0 - …

Introducing Fixed Rate Sampling v2 (Using Processors)

---

CHANGELOG.md
gradle/common-java.gradle

This changes the source compatibility version to 1.7 and Java 1.6 is no longer supported.
Previously, the `JAVA_JRE_6` variable held the home of the Java 6 jars for setting the boot classpath. The build script now checks the `JAVA_JRE_7` for the same reason.

Upgrading (source|target)Compatibility version to 1.7, i.e. ending support for Java 6

---

agent/build.gradle
collectd/build.gradle
core/build.gradle
core/native.gradle
distributions/build.gradle
gradle/common-java.gradle
logging/logging.gradle
web/build.gradle

This pull request updates all the dependencies used by AI-Java SDK to latest versions except Google Guava which is updated to 20.0 as the later versions do no support JDK 1.7
#410 is similar and this PR updates to more recent versions of dependencies

Upgrade dependencies

---

core/build.gradle

The checking for the environment variable was not reliable. I've been using gitbash as my shell in VS Code and it didn't pick up the "windir" env var for some reason. This way it works regardless (and nothing in the build script seems to depend on the windir variable).

Changing to a more reliable way to detect os for build

---

CHANGELOG.md
core/src/main/java/com/microsoft/applicationinsights/internal/config/ConfigurationFileLocator.java
core/src/test/java/com/microsoft/applicationinsights/internal/config/ConfigurationFileLocatorTest.java

Adding system property `insights.configurationFile` to allow to explicitly set directory containing the config file. Necessary for keeping config files externalized in single directory.

adding config dir system property

---

core/src/main/java/com/microsoft/applicationinsights/internal/channel/samplingV2/FixedRateSamplingTelemetryProcessor.java
core/src/main/java/com/microsoft/applicationinsights/internal/channel/samplingV2/SamplingScoreGeneratorV2.java
core/src/test/java/com/microsoft/applicationinsights/internal/channel/samplingV2/FixedRateSamplingTelemetryProcessorTest.java
gradle/provided-configuration.gradle
web/build.gradle

The shadowJar was repackaging way more than it should. This fixes it. 
Here's the gist:
* By default, shadowJar repackages everything in the **runtime** configuration
* `runtime.extendsFrom compile` i.e. **runtime** inherits all behaviors from **compile**.
* Since **provided** was defined so **compile** inherited its behaviors, this created an unwanted transitive link causing everything defined as **provided** to be repackaged. Really, we just need these on the classpath (see changes to provided-configuration).
As a result of fixing what is repackaged:
* Classes in _:agent_ are no longer accessible and shouldn't be, hence the changes to java files.
* Apache's poorly named method `StringUtils.isEmpty` actually does check for `null` :)
Also,
* There's no reference to the Apache HttpClient …

Fix shadow jar

---

core/src/main/java/com/microsoft/applicationinsights/telemetry/JsonTelemetryDataSerializer.java
core/src/test/java/com/microsoft/applicationinsights/telemetry/JsonTelemetryDataSerializerTest.java

Serialize NaN and +/-Infinity to 0.0 to be consistent with other Application Insight clients.
Expand tests.
Fix #492.

Fix handling of NaN and +/-Infinity in JSON serializer

---

core/src/main/java/com/microsoft/applicationinsights/TelemetryConfiguration.java

Fix #503 
Added a check to prevent initialization twice. (basically happens when the TelemetryConfiguration class's getActive() method is invoked inside itself before the call of the first method completes - specifically takes place when initializing quick pulse module)
This duplicate initialization can cause degraded start-up performance.

Prevent Multiple Initialization of Configuration

---

CHANGELOG.md
web/src/main/java/com/microsoft/applicationinsights/web/internal/correlation/TelemetryCorrelationUtils.java

Fix #506 .
This PR fixes the missing Null Reference checks in the TelemetryCorrelationUtils class which caused NullPointerExceptions.

Fix null ref check in telemetry correlation Utils

---

core/src/main/java/com/microsoft/applicationinsights/internal/channel/samplingV2/FixedRateSamplingTelemetryProcessor.java
core/src/main/java/com/microsoft/applicationinsights/internal/config/ParamExcludedTypeXmlElement.java
core/src/main/java/com/microsoft/applicationinsights/internal/config/ParamIncludedTypeXmlElement.java
gradle/publishing.gradle
web/src/main/java/com/microsoft/applicationinsights/web/internal/correlation/AppProfileFetcher.java

fixed javadoc errors
added task to generate pom.xml with each build

fixed publishing stuff

---

core/src/main/java/com/microsoft/applicationinsights/internal/channel/sampling/FixedRateTelemetrySampler.java
core/src/main/java/com/microsoft/applicationinsights/internal/channel/samplingV2/FixedRateSamplingTelemetryProcessor.java
core/src/test/java/com/microsoft/applicationinsights/internal/channel/samplingV2/FixedRateSamplingTelemetryProcessorTest.java

Fix #535 
Fixed both the below issues in this commit.
1. New version of FixedRate Sampling worked only with global sampling percentage and not with user set sampling percentage.
2. Old version of FixedRate Sampling sets sampling score as SamplingPercentage once sampled in. It has to be sampling percentage.

Fixing FixedRateSampling to work in old and new version of sampling

---

CHANGELOG.md
logging/log4j1_2/appenderSrc/main/java/com/microsoft/applicationinsights/log4j/v1_2/internal/ApplicationInsightsLogEvent.java
logging/log4j1_2/appenderSrc/test/java/com/microsoft/applicationinsights/log4j/v1_2/ApplicationInsightsAppenderTests.java
logging/log4j2/appenderSrc/main/java/com/microsoft/applicationinsights/log4j/v2/internal/ApplicationInsightsLogEvent.java
logging/log4j2/appenderSrc/test/java/com/microsoft/applicationinsights/log4j/v2/ApplicationInsightsAppenderTests.java
logging/logback/appenderSrc/main/java/com/microsoft/applicationinsights/logback/internal/ApplicationInsightsLogEvent.java
logging/logback/appenderSrc/test/java/com/microsoft/applicationinsights/logback/ApplicationInsightsAppenderTests.java

This PR #400 fixes the Logger Messages not being pushed when reporting Exceptions via Logging Frameworks (Log4j1_2, Log4j2 and Logback)
They will be reported as Key-value pair in custom dimension of ExceptionTelemetry where Key's name would be "_Logger Message_" and value would be value set by Logger.

Fix Log Messages Being Dropped when Reporting Exceptions

---

test/smoke/build.gradle
test/smoke/framework/testCases/build.gradle
test/smoke/framework/utils/build.gradle
test/smoke/testApps/build.gradle

Overview of issues:
_variables were defined twice:_ opted to use parent project definitions. this scenario is also dependent on it being defined in one place.
_guava missing from test dependencies:_ Since we re-namespace the guava dependency, it needs to be named here also so these still work when custom jars are used.

minor fixes for specifying custom applciationinsights jars for smoke tests

---

core/src/main/java/com/microsoft/applicationinsights/internal/channel/common/TransmissionFileSystemOutput.java
core/src/main/java/com/microsoft/applicationinsights/internal/channel/common/TransmissionPolicyManager.java

Reliable channel: replacing logAlways "TRACE" statements with "info"

---

core/src/main/java/com/microsoft/applicationinsights/internal/channel/common/PartialSuccessHandler.java

Reliable channel: close resources in finally block.

---

core/src/main/java/com/microsoft/applicationinsights/internal/channel/common/TransmissionNetworkOutput.java
core/src/main/java/com/microsoft/applicationinsights/internal/channel/common/TransmissionPolicyManager.java

When reviewing this code to implement a few refactored items I noticed that there was still a retry hard code in the logic. This PR fixes that.
As it would be there are still a mix of tabs and spaces in the files that cause some additional lines for the commit that don't need to be there.

Bugfix against retry logic

---

core/src/main/java/com/microsoft/applicationinsights/internal/channel/TransmissionHandler.java
core/src/main/java/com/microsoft/applicationinsights/internal/channel/TransmissionHandlerArgs.java
core/src/main/java/com/microsoft/applicationinsights/internal/channel/TransmissionHandlerObserver.java
core/src/main/java/com/microsoft/applicationinsights/internal/channel/TransmitterFactory.java

Fixed javadocs tags, that caused build errors while executing `javadoc` gradle task
**P.S.** do I need issue and CHANGELOG for this tiny fix?

Fixed javadocs tags, that caused build errors

---

gradle/common-java.gradle
test/smoke/framework/utils/src/main/java/com/microsoft/applicationinsights/smoketest/JsonHelper.java
test/smoke/testApps/CoreAndFilter/src/main/java/com/microsoft/ajl/simplecalc/SimpleTrackPageViewServlet.java
test/smoke/testApps/CoreAndFilter/src/main/webapp/doPageView.jsp
test/smoke/testApps/CoreAndFilter/src/smokeTest/java/com/microsoft/applicationinsights/smoketest/CoreAndFilterTests.java
test/smoke/testApps/CoreAndFilter/src/smokeTest/resources/appServers.txt
test/smoke/testApps/build.gradle

In addition to the test:
* This also includes adding tomcat 8.5 to test envs (missing from previous PR)
* Included `STARTED` event in smoketests so it's clear when the test method has started in the logs
* Fixed deserialization code in smoke tests to support PageViewData

Adding test case for PageView

---

web/src/main/java/com/microsoft/applicationinsights/web/extensibility/modules/WebRequestTrackingTelemetryModule.java

401s are always errors w.r.t. the http client. It's expected behavior, but it's not a successful request.
I searched other AppInsights repos and could not find anything resembling this classification.

401s are not successful requests

---

core/src/main/java/com/microsoft/applicationinsights/internal/config/ChannelXmlElement.java

Fix #591 
This PR adds ability to configure MAX_INSTANT_RETRIES from the channel configuration.

add MaxInstantRetry XML Element in Channel configuration

---

core/src/main/java/com/microsoft/applicationinsights/TelemetryClient.java

Without this change it is impossible to load instrumentation key from active configuration if it was updated after `TelemetryClient` creation.
I need this in order to pick up instrumentation key that was set from spring configuration.

Added check for TelemetryConfiguration#getInstrumentationKey emptiness

---

core/src/main/java/com/microsoft/applicationinsights/internal/perfcounter/JmxMetricPerformanceCounter.java

This change allow **JmxMetricPerformanceCounter** to send a new instance of MetricTelemetry instead of reuse it.
Fix #609

Change JmxMetricPerformanceCounter

---

core/src/main/java/com/microsoft/applicationinsights/internal/logger/DefaultLogFileProxy.java

Fix #616 
This fix ensures that logs are constantly written to the file.

support real time logging

---

test/smoke/framework/fakeIngestion/servlet/src/main/java/com/microsoft/applicationinsights/test/fakeingestion/MockedAppInsightsIngestionServlet.java
test/smoke/framework/fakeIngestion/standalone/src/main/java/com/microsoft/applicationinsights/test/fakeingestion/MockedAppInsightsIngestionServer.java

This expands the smoke tests, adding a method which waits for a number of telemetry items matching a particular condition.
This is intended for testing perf counters.

added waitForItems methods so to not rely on guessing the right time

---

core/src/main/java/com/microsoft/applicationinsights/internal/config/AddTypeXmlElement.java
core/src/main/java/com/microsoft/applicationinsights/internal/config/ChannelXmlElement.java
core/src/main/java/com/microsoft/applicationinsights/internal/config/ContextInitializersXmlElement.java
core/src/main/java/com/microsoft/applicationinsights/internal/config/FixedSamplerXmlElement.java
core/src/main/java/com/microsoft/applicationinsights/internal/config/JmxListXmlElement.java
core/src/main/java/com/microsoft/applicationinsights/internal/config/JmxXmlElement.java
core/src/main/java/com/microsoft/applicationinsights/internal/config/JvmXmlElement.java
core/src/main/java/com/microsoft/applicationinsights/internal/config/ParamExcludedTypeXmlElement.java
core/src/main/java/com/microsoft/applicationinsights/internal/config/ParamIncludedTypeXmlElement.java
core/src/main/java/com/microsoft/applicationinsights/internal/config/ParamXmlElement.java
core/src/main/java/com/microsoft/applicationinsights/internal/config/PerformanceCounterJvmSectionXmlElement.java
core/src/main/java/com/microsoft/applicationinsights/internal/config/PerformanceCountersXmlElement.java
core/src/main/java/com/microsoft/applicationinsights/internal/config/QuickPulseXmlElement.java
core/src/main/java/com/microsoft/applicationinsights/internal/config/RemoveTypeXmlElement.java
core/src/main/java/com/microsoft/applicationinsights/internal/config/SDKLoggerXmlElement.java
core/src/main/java/com/microsoft/applicationinsights/internal/config/SamplerXmlElement.java
core/src/main/java/com/microsoft/applicationinsights/internal/config/TelemetryInitializersXmlElement.java
core/src/main/java/com/microsoft/applicationinsights/internal/config/TelemetryModulesXmlElement.java
core/src/main/java/com/microsoft/applicationinsights/internal/config/TelemetryProcessorXmlElement.java
core/src/main/java/com/microsoft/applicationinsights/internal/config/TelemetryProcessorsXmlElement.java
core/src/main/java/com/microsoft/applicationinsights/internal/config/WindowsPerformanceCounterXmlElement.java

While working on our configuration XMLs' schema documentation, I noticed all of these annotations. This marks the root element of an xml document. We only have one, so I removed all the ones that were wrong.

too many root element annotations. there's only one root element

---

CHANGELOG.md
core/src/main/java/com/microsoft/applicationinsights/internal/agent/CoreAgentNotificationsHandler.java

This PR fixes incorrect success flag set when capturing HTTP Dependencies. The value was hard coded to true instead of checking based on result code.

Fix incorrect success flag set while capturing http dependency

---

test/smoke/appServers/jre.master.txt
test/smoke/framework/testCore/build.gradle
test/smoke/framework/testCore/src/main/java/com/microsoft/applicationinsights/smoketest/AiSmokeTest.java

Basically, this changes how the smoketests are initialized. If an appserver is exepected, but its *.jre.txt resource cannot be found, the tests runner will now just skip that environment.
For example, this is expected behavior when you do not have the JBoss EAP environment variables set.

Allow smoketests to run all configs it can find

---

test/smoke/framework/testCore/src/main/java/com/microsoft/applicationinsights/smoketest/AiSmokeTest.java

I'm seeing issues every once in a while with container communication. I'm hoping docker just needs a cooldown period.

smoketests: added delay after container stops

---

core/src/main/java/com/microsoft/applicationinsights/internal/annotation/AnnotationPackageScanner.java
core/src/main/java/com/microsoft/applicationinsights/internal/channel/common/ApacheSender43.java
core/src/main/java/com/microsoft/applicationinsights/internal/channel/common/TransmitterImpl.java
core/src/main/java/com/microsoft/applicationinsights/internal/channel/samplingV2/FixedRateSamplingTelemetryProcessor.java
core/src/main/java/com/microsoft/applicationinsights/internal/config/ReflectionUtils.java
core/src/main/java/com/microsoft/applicationinsights/internal/config/TelemetryConfigurationFactory.java
core/src/main/java/com/microsoft/applicationinsights/internal/shutdown/SDKShutdownActivity.java
core/src/test/java/com/microsoft/applicationinsights/internal/config/TelemetryConfigurationFactoryTest.java
web/src/main/java/com/microsoft/applicationinsights/internal/config/WebReflectionUtils.java
web/src/main/java/com/microsoft/applicationinsights/web/extensibility/modules/WebRequestTrackingTelemetryModule.java
web/src/main/java/com/microsoft/applicationinsights/web/internal/ApplicationInsightsServletContextListener.java
web/src/main/java/com/microsoft/applicationinsights/web/internal/WebRequestTrackingFilter.java
web/src/test/java/com/microsoft/applicationinsights/web/extensibility/modules/WebRequestTrackingTelemetryModuleTests.java

This limits the use of reflection during initialization.
This also makes a few other expensive initialization asynchronous.

Optimizations for Filter/TelemetryClient startup

---

core/src/main/java/com/microsoft/applicationinsights/internal/perfcounter/AbstractUnixPerformanceCounter.java
core/src/main/java/com/microsoft/applicationinsights/internal/perfcounter/Constants.java
core/src/main/java/com/microsoft/applicationinsights/internal/perfcounter/CpuPerformanceCounterCalculator.java
core/src/main/java/com/microsoft/applicationinsights/internal/perfcounter/JmxPerformanceCounter.java
core/src/main/java/com/microsoft/applicationinsights/internal/perfcounter/ProcessCpuPerformanceCounter.java
core/src/main/java/com/microsoft/applicationinsights/internal/perfcounter/UnixProcessIOPerformanceCounter.java
core/src/main/java/com/microsoft/applicationinsights/internal/perfcounter/UnixTotalCpuPerformanceCounter.java
core/src/main/java/com/microsoft/applicationinsights/internal/perfcounter/UnixTotalMemoryPerformanceCounter.java
core/src/main/java/com/microsoft/applicationinsights/internal/perfcounter/WindowsPerformanceCounterAsMetric.java
core/src/test/java/com/microsoft/applicationinsights/internal/config/ConfigurationFileLocatorTest.java
test/smoke/framework/testCore/src/main/java/com/microsoft/applicationinsights/smoketest/AiSmokeTest.java
test/smoke/framework/testCore/src/main/java/com/microsoft/applicationinsights/smoketest/TargetUri.java
test/smoke/testApps/AutoPerfCounters/src/smokeTest/java/com/microsoft/applicationinsights/smoketest/PerfCountersDataTest.java

This just causes confusion when seen in the cloud. Now, if we can't measure something, we won't report it as some garbage value.
Fix #647 .

removed usage of -1 as a default value for some measurements

---

CHANGELOG.md
web/src/main/java/com/microsoft/applicationinsights/web/internal/correlation/CdsProfileFetcher.java

Enable system properties for the HTTP client used in the ikey resolver. Also, limit retries in the resolver to save on performance in case of constant failures.

IkeyResolver: support system properties and limit retries.

---

test/smoke/appServers/build.gradle
test/smoke/framework/testCore/src/main/java/com/microsoft/applicationinsights/smoketest/AiSmokeTest.java
test/smoke/framework/testCore/src/main/java/com/microsoft/applicationinsights/smoketest/docker/AiDockerClient.java
test/smoke/framework/utils/src/main/java/com/microsoft/applicationinsights/smoketest/JsonHelper.java
test/smoke/framework/utils/src/main/java/com/microsoft/applicationinsights/smoketest/exceptions/SmokeTestException.java
test/smoke/framework/utils/src/main/java/com/microsoft/applicationinsights/smoketest/exceptions/TimeoutException.java

Reduced number of retries so it fails a bit faster when containers do not start.
Fixed NPE when stopping a container after it fails; it doesn't need to stop. it should be skipped.
Added check for success and throw exception.
Added custom exceptions for clarity.

Minor improvements to smoketests

---

core/src/main/java/com/microsoft/applicationinsights/common/CommonUtils.java
web/src/main/java/com/microsoft/applicationinsights/web/internal/WebRequestTrackingFilter.java

This PR helps in detecting Agent Jar in a better way inside WebRequestTrackingFilter. Instead of calling the Instance of AgentConnector and failing with an exception when Jar is not present this, explicitly tries to see if the AgentNotificationsHandler is present on the classPath. This prevents from throwing unnecessary exception. 
Copying my comment from #646 
I wanted to point out the following: By reverting the changes of how agent is detected to the original implementation, the user will see this misleading exception message when the Agent Jar is not present.
AI: ERROR 04-05-2018 09:08:53.150, 31(localhost-startStop-1): Could not find Agent: 'java.lang.NoClassDefFoundError: com/microsoft/applicationinsights/agent/internal/coresync/AgentNotificationsHandler
at …

updating agent detection in filter

---

core/src/test/java/com/microsoft/applicationinsights/internal/config/ConfigurationFileLocatorTest.java

These test resources were being left over and interfering with other build steps.

Add cleanup step to test

---

agent/src/main/java/com/microsoft/applicationinsights/agent/internal/logger/InternalAgentLogger.java
core/src/main/java/com/microsoft/applicationinsights/internal/logger/InternalLogger.java

to make debugging customer issues easier when point-in-time matters; i.e. to correlate customer log events with events in the application insights services.
TODO:

added timezone to dateformat for logs

---

test/smoke/testApps/CoreAndFilter/src/smokeTest/java/com/microsoft/applicationinsights/smoketest/CoreAndFilterTests.java
test/smoke/testApps/build.gradle

Used a `Matcher` instead of `assertTrue`, which will give a better error message.
This failed for me locally and took some digging to figure out what went wrong. In the future, if you must use `assertTrue` or `assertFalse`, let's include a message, too.

Minor change to smoke tests to make them a bit more tolerant

---

core/src/main/java/com/microsoft/applicationinsights/internal/heartbeat/WebAppsHeartbeatProvider.java

A small fix to remove the trailing white space from the environment variable in HeartBeat

fix trailing whitespace

---

test/smoke/framework/testCore/src/main/java/com/microsoft/applicationinsights/smoketest/DependencyContainer.java
test/smoke/framework/testCore/src/main/java/com/microsoft/applicationinsights/smoketest/UseAgent.java
test/smoke/framework/testCore/src/main/java/com/microsoft/applicationinsights/smoketest/WithDependencyContainers.java
test/smoke/testApps/CoreAndFilter/src/smokeTest/java/com/microsoft/applicationinsights/smoketest/CoreAndFilterTests.java
test/smoke/testApps/build.gradle

Docs for using agent and dependency related annotations.
Using `assertThat` instead of `assertTrue` because the former method gives better output on failure.

Added javadoc and rewrote assert in smoketests

---

core/src/main/java/com/microsoft/applicationinsights/TelemetryClient.java
core/src/main/java/com/microsoft/applicationinsights/internal/util/MapUtil.java
core/src/main/java/com/microsoft/applicationinsights/telemetry/MetricTelemetry.java
core/src/test/java/com/microsoft/applicationinsights/TelemetryClientTests.java
test/smoke/testApps/CoreAndFilter/src/smokeTest/java/com/microsoft/applicationinsights/smoketest/CoreAndFilterTests.java

Original description
---
The stddev should be non-null in aggregate metrics. Maybe it should be -1 since that's an invalid value for Standard Deviation.
See [MetricTelemetry.updateKind](https://github.com/Microsoft/ApplicationInsights-Java/blob/0e2fe37143ad78b600d52189bc1994ccf70ac99c/core/src/main/java/com/microsoft/applicationinsights/telemetry/MetricTelemetry.java#L188). If stddev isn't set (or any of the statistic fields), then the metric won't be marked as kind=Aggregate. Perhaps this logic is flawed since it also excludes the possibility of an aggregation on a data set with size=1.
---
According to the bond spec, stddev can be null; as well as the other statistic fields. Updated TelemetryClient and MetricTelemetry to reflect the [bond …

Updated trackMetric to conform to bond spec

---

test/smoke/framework/fakeIngestion/servlet/src/main/java/com/microsoft/applicationinsights/test/fakeingestion/MockedAppInsightsIngestionServlet.java
test/smoke/framework/fakeIngestion/standalone/src/main/java/com/microsoft/applicationinsights/test/fakeingestion/MockedAppInsightsIngestionServer.java
test/smoke/framework/testCore/src/main/java/com/microsoft/applicationinsights/smoketest/AiSmokeTest.java
test/smoke/framework/testCore/src/main/java/com/microsoft/applicationinsights/smoketest/TargetUri.java
test/smoke/testApps/CoreAndFilter/src/smokeTest/java/com/microsoft/applicationinsights/smoketest/CoreAndFilterTests.java

This adds an optional timeout to the `@TargetUri` annotation. Some tests will need more time, e.g. the one that sleeps for 20 seconds before responding.

added timeout option to @TargetUri

---

core/src/test/java/com/microsoft/applicationinsights/internal/channel/common/TransmissionFileSystemOutputTest.java

Current hypothesis:
2 files are being written within 1 ms i.e. they have the same timestamp which fails the "fetchOldestFile" condition.
already discussed with @dhaval24 . no review needed.

Fix file test

---

web/src/test/java/com/microsoft/applicationinsights/web/extensibility/initializers/WebAppNameContextInitializerTest.java
web/src/test/java/com/microsoft/applicationinsights/web/internal/WebRequestTrackingFilterTests.java
web/src/test/resources/ApplicationInsights.xml

I noticed this was missing tests. They're pretty straightforward.
I did optimize the filter test class a bit: using mockito instead of class override to give it more flexibility.

Tests for WebAppNameContextInitializer

---

azure-application-insights-spring-boot-starter/src/main/java/com/microsoft/applicationinsights/autoconfigure/ApplicationInsightsTelemetryAutoConfiguration.java
azure-application-insights-spring-boot-starter/src/test/java/com/microsoft/applicationinsights/autoconfigure/ApplicationInsightsTelemetryAutoConfigurationTests.java

This PR updates the auto configure of QuickPulse in starter to prevent initialization if Local Forwarder is present.

update auto config of QuickPulse

---

core/src/main/java/com/microsoft/applicationinsights/internal/quickpulse/DefaultQuickPulseCoordinator.java

This fixes an issue in QuickPulse where default post interval which was being used was 5 seconds instead of 1 second.

Fix quickpulse post interval bug

---

azure-application-insights-spring-boot-starter/gradle.properties
azure-application-insights-spring-boot-starter/src/main/java/com/microsoft/applicationinsights/autoconfigure/ApplicationInsightsTelemetryAutoConfiguration.java
azure-application-insights-spring-boot-starter/src/main/java/com/microsoft/applicationinsights/autoconfigure/ApplicationInsightsWebMvcAutoConfiguration.java
gradle.properties
test/smoke/testApps/SpringBootTest/src/main/java/com/springbootstartertest/controller/TestController.java
test/smoke/testApps/SpringBootTest/src/main/resources/application.properties
test/smoke/testApps/SpringBootTest/src/smokeTest/java/com/springbootstartertest/smoketest/SpringbootSmokeTest.java

This fixes the order of Filter injection using SpringBoot starter. It allows to capture the correct response code for failed requests.
It turns out that :  Ordered.HIGHEST_PRECEDENCE = Integer.MIN_VALUE and we were adding 10 to it which reduced the priority eventually ;)
@grlima @littleaj could you please review this change. It is small and there is request to make hot fix for this. 
Deployed the changes in the test app and here is the distributed transaction.

Fix the filter order in starter

---

web/src/test/java/com/microsoft/applicationinsights/web/utils/JettyTestServer.java

This makes the tests a bit more reliable.

added check for open port before creating test server.

---

core/build.gradle

Fix #767.
Upgrades grpc dependency to 1.16.1 to include security fix.

upgrade grpc components

---

web/src/main/java/com/microsoft/applicationinsights/web/internal/correlation/tracecontext/Traceparent.java
web/src/main/java/com/microsoft/applicationinsights/web/internal/correlation/tracecontext/Tracestate.java
web/src/test/java/com/microsoft/applicationinsights/web/internal/correlation/tracecontext/TraceparentTests.java
web/src/test/java/com/microsoft/applicationinsights/web/internal/correlation/tracecontext/TracestateTests.java

This PR brings in the required classes for integrating W3C correlation protocol. 
Related #716 
@reyang @lmolkova take a look. 

W3C : Tracecontext classes 

---

CHANGELOG.md
agent/src/main/java/com/microsoft/applicationinsights/agent/internal/agent/DefaultClassDataProvider.java
agent/src/main/java/com/microsoft/applicationinsights/agent/internal/agent/HttpClientMethodVisitor.java
agent/src/main/java/com/microsoft/applicationinsights/agent/internal/agent/http/HttpClassDataProvider.java
agent/src/main/java/com/microsoft/applicationinsights/agent/internal/config/AgentBuiltInConfiguration.java
agent/src/main/java/com/microsoft/applicationinsights/agent/internal/config/AgentBuiltInConfigurationBuilder.java
agent/src/main/java/com/microsoft/applicationinsights/agent/internal/config/XmlAgentConfigurationBuilder.java
agent/src/main/java/com/microsoft/applicationinsights/agent/internal/config/XmlParserUtils.java
azure-application-insights-spring-boot-starter/src/main/java/com/microsoft/applicationinsights/autoconfigure/ApplicationInsightsProperties.java
azure-application-insights-spring-boot-starter/src/main/java/com/microsoft/applicationinsights/autoconfigure/ApplicationInsightsWebModuleConfiguration.java
core/src/main/java/com/microsoft/applicationinsights/internal/agent/CoreAgentNotificationsHandler.java
web/src/main/java/com/microsoft/applicationinsights/web/extensibility/modules/WebRequestTrackingTelemetryModule.java
web/src/main/java/com/microsoft/applicationinsights/web/internal/RequestTelemetryContext.java
web/src/main/java/com/microsoft/applicationinsights/web/internal/correlation/TraceContextCorrelation.java
web/src/main/java/com/microsoft/applicationinsights/web/internal/correlation/tracecontext/Traceparent.java
web/src/main/java/com/microsoft/applicationinsights/web/internal/correlation/tracecontext/Tracestate.java
web/src/test/java/com/microsoft/applicationinsights/web/extensibility/modules/WebRequestTrackingTelemetryModuleTests.java
web/src/test/java/com/microsoft/applicationinsights/web/internal/correlation/TraceContextCorrelationTests.java
web/src/test/java/com/microsoft/applicationinsights/web/internal/correlation/tracecontext/TraceparentTests.java
web/src/test/java/com/microsoft/applicationinsights/web/internal/correlation/tracecontext/TracestateTests.java

Fix #716 
This PR is super set of all previous PRs which completes the integration of W3C for both incoming and outbound calls.
Non Goals of this PR: Backward Compatibility with AI proprietary correlation protocol. 
Related #776 #775 
Enable W3C:
Incoming Side - 
J2EE Apps add the following to the `<TelemetryModules>` tag inside ApplicationInsights.xml
```<Add type="com.microsoft.applicationinsights.web.extensibility.modules.WebRequestTrackingTelemetryModule"  W3CEnabled ="true"/>```
Springboot apps add the following property:
`azure.application-insights.web.w3c=true`
Outgoing Side - 
Add the following to AI-Agent.xml
```
<Instrumentation>
<BuiltIn enabled="true">
<HTTP enabled="true" W3C="true"/>
</BuiltIn>
</Instrumentation>
```
Remember : you need both inbound and outbound settings to …

W3C Integration

---

CHANGELOG.md
agent/src/main/java/com/microsoft/applicationinsights/agent/internal/agent/DefaultClassDataProvider.java
agent/src/main/java/com/microsoft/applicationinsights/agent/internal/agent/HttpClientMethodVisitor.java
agent/src/main/java/com/microsoft/applicationinsights/agent/internal/agent/http/HttpClassDataProvider.java
agent/src/main/java/com/microsoft/applicationinsights/agent/internal/config/AgentBuiltInConfiguration.java
agent/src/main/java/com/microsoft/applicationinsights/agent/internal/config/AgentBuiltInConfigurationBuilder.java
agent/src/main/java/com/microsoft/applicationinsights/agent/internal/config/XmlAgentConfigurationBuilder.java
agent/src/main/java/com/microsoft/applicationinsights/agent/internal/config/XmlParserUtils.java
azure-application-insights-spring-boot-starter/README.md
azure-application-insights-spring-boot-starter/build.gradle
azure-application-insights-spring-boot-starter/src/main/java/com/microsoft/applicationinsights/autoconfigure/ApplicationInsightsProperties.java
azure-application-insights-spring-boot-starter/src/main/java/com/microsoft/applicationinsights/autoconfigure/ApplicationInsightsWebModuleConfiguration.java
core/build.gradle
core/src/main/java/com/microsoft/applicationinsights/internal/agent/CoreAgentNotificationsHandler.java
web/src/main/java/com/microsoft/applicationinsights/web/extensibility/modules/WebRequestTrackingTelemetryModule.java
web/src/main/java/com/microsoft/applicationinsights/web/internal/RequestTelemetryContext.java
web/src/main/java/com/microsoft/applicationinsights/web/internal/correlation/TelemetryCorrelationUtils.java
web/src/main/java/com/microsoft/applicationinsights/web/internal/correlation/TraceContextCorrelation.java
web/src/main/java/com/microsoft/applicationinsights/web/internal/correlation/tracecontext/Traceparent.java
web/src/main/java/com/microsoft/applicationinsights/web/internal/correlation/tracecontext/Tracestate.java
web/src/test/java/com/microsoft/applicationinsights/web/extensibility/modules/WebRequestTrackingTelemetryModuleTests.java
web/src/test/java/com/microsoft/applicationinsights/web/internal/correlation/TraceContextCorrelationTests.java
web/src/test/java/com/microsoft/applicationinsights/web/internal/correlation/tracecontext/TraceparentTests.java
web/src/test/java/com/microsoft/applicationinsights/web/internal/correlation/tracecontext/TracestateTests.java
web/src/test/java/com/microsoft/applicationinsights/web/utils/ServletUtils.java

Final W3C implementation
#775 #782 #776 #716 
@lmolkova you can skip this review if you want as you already reviewed the old PR.
@littleaj can you take a brief overview?
**Enable W3C:**
**Incoming Side -** 
**J2EE Apps add the following to the `<TelemetryModules>` tag inside ApplicationInsights.xml**
```xml
<Add type="com.microsoft.applicationinsights.web.extensibility.modules.WebRequestTrackingTelemetryModul>
<Param name = " W3CEnabled" value ="true"/>
<Param name ="enableW3CBackCompat" value = "true" />
</Add>
```
**Springboot apps add the following property**:
`azure.application-insights.web.enable-W3C=true`
`azure.application-insights.web.enable-W3C-backcompat-mode=true`
**Outgoing Side -** 
Add the following to AI-Agent.xml
```xml
<Instrumentation>
<BuiltIn enabled="true">
<HTTP …
```

W3C Final implementation

---

CHANGELOG.md
web/build.gradle

Fix #784 
@littleaj I fixed the above. It was quick one liner :)

Relocate Guava

---

core/src/main/java/com/microsoft/applicationinsights/TelemetryClient.java
core/src/main/java/com/microsoft/applicationinsights/internal/util/MapUtil.java
core/src/main/java/com/microsoft/applicationinsights/telemetry/TelemetryContext.java
core/src/test/java/com/microsoft/applicationinsights/internal/util/MapUtilTest.java

Mostly simplifying the caller side since each caller checked for null/empty. Plus, copy from source to target is a nop if it's null or empty, so why not just check for that in the method.

simplified MapUtil.copy

---

build.gradle
core/build.gradle
gradle/common-java.gradle
test/smoke/framework/utils/build.gradle

For reference:
https://www.owasp.org/index.php/OWASP_Dependency_Check
https://github.com/jeremylong/dependency-check-gradle
https://jeremylong.github.io/DependencyCheck/dependency-check-gradle/index.html
Adding dependency checker to build script. This scans our dependnecies for NVD CVEs: https://nvd.nist.gov/
Run it with
```
gradlew dependencyCheckAnalyze
```
I'll update the CI build to run this task and generate a report for periodic review.

Add dependency-check tool to build

---

ApplicationInsightsInternalLogger/src/main/java/com/microsoft/applicationinsights/internal/logger/FileLoggerOutput.java
ApplicationInsightsInternalLogger/src/main/java/com/microsoft/applicationinsights/internal/logger/InternalLogger.java

Fix #653 
This allows a system property to enable logging. This will be especially useful for read log messages which are printed before the config file is read (or if it's non-existant).
This also deprecates the logAlways statement. We've discussed this method before and its pitfalls. I vote to remove it. If you disagree, let's discuss and I can revert it if needed.

added system properties to enable logging.

---

CHANGELOG.md
agent/src/main/java/com/microsoft/applicationinsights/agent/internal/agent/DefaultClassDataProvider.java

This PR will remove duplicate provider name from the class

Remove duplicate provider

---

web/src/main/java/com/microsoft/applicationinsights/web/internal/httputils/AIHttpServletListener.java
web/src/main/java/com/microsoft/applicationinsights/web/internal/httputils/HttpServerHandler.java
web/src/test/java/com/microsoft/applicationinsights/web/internal/httputils/AIHttpServletListenerTest.java
web/src/test/java/com/microsoft/applicationinsights/web/internal/httputils/HttpServerHandlerTest.java

Related #816, #817, #818
Add Async Listener Implementation and tests.  Async Lister is used to complete the spans for Async Servlet Requests.
Note: There was a need to modify `handleEnd()` method's signature, as this method can be called in a different thread than that of `handleStart()`. Also it's not feasible to store the instance of `RequestTelemetryContext` as a final member variable of `HttpServerHandler` class, as it is created when `handleStart()` is invoked.
PS: The CI will fail as the integration with rest of the code is not part of this PR. I will push it as part of another PR.

Add Async Listener Implementation

---

test/smoke/framework/testCore/src/main/java/com/microsoft/applicationinsights/smoketest/AiSmokeTest.java

tailLastLog.sh timeouts each test run after 10s. The stacktrace is just taking up space in the build logs.
commenting out for now.
I'm going to try to address this issue in the future. It may just need a longer timeout. For now, let's just disable it.

disable tailLastLog executions

---

CHANGELOG.md
test/webapps/bookstore-spring/src/main/java/com/springapp/mvc/extensions/WebRequestRunIdTelemetryModule.java
web/src/main/java/com/microsoft/applicationinsights/web/extensibility/modules/WebRequestTrackingTelemetryModule.java
web/src/main/java/com/microsoft/applicationinsights/web/extensibility/modules/WebSessionTrackingTelemetryModule.java
web/src/main/java/com/microsoft/applicationinsights/web/extensibility/modules/WebTelemetryModule.java
web/src/main/java/com/microsoft/applicationinsights/web/extensibility/modules/WebUserTrackingTelemetryModule.java
web/src/main/java/com/microsoft/applicationinsights/web/internal/ThreadContext.java
web/src/main/java/com/microsoft/applicationinsights/web/internal/WebModulesContainer.java
web/src/main/java/com/microsoft/applicationinsights/web/internal/WebRequestTrackingFilter.java
web/src/main/java/com/microsoft/applicationinsights/web/internal/httputils/AIHttpServletListener.java
web/src/main/java/com/microsoft/applicationinsights/web/internal/httputils/HttpServerHandler.java
web/src/test/java/com/microsoft/applicationinsights/web/extensibility/modules/WebRequestTrackingTelemetryModuleTests.java
web/src/test/java/com/microsoft/applicationinsights/web/internal/ThreadContextTests.java
web/src/test/java/com/microsoft/applicationinsights/web/internal/WebRequestTrackingFilterTests.java
web/src/test/java/com/microsoft/applicationinsights/web/internal/httputils/HttpServerHandlerTest.java

Merge #827 first
This PR integrates Async Listener to `WebRequestTrackingFilter`. I have introduced `setRequestTelemetryContext()` API for `WebTelemetryModule` interface as all the web modules need to use the same context which is propagated. 
Deprecated the usage of `InherritableThreadLocal` in favor of `ThreadLocal` as ITLS doesn't work when performing correlation in ThreadPools. 

Final Integration: Async Listener

---

core/src/main/java/com/microsoft/applicationinsights/TelemetryClient.java

fixes double-checked locking issue

Variable needs to be volatile

---

agent/src/main/java/com/microsoft/applicationinsights/agent/internal/agent/sql/PreparedStatementClassVisitor.java

There are two signatures for `setTimestamp` so this needs to be a "multimap"

addressed bug where key/value pair was incorrectly overwritten

---

core/src/main/java/com/microsoft/applicationinsights/internal/shutdown/SDKShutdownActivity.java

I noticed this also when shutting down tomcat: the threads weren't stopping as expected, including the shutdownhook thread. It turns out this was the problem.

the shutdownhook should not be a daemon

---

core/src/main/java/com/microsoft/applicationinsights/internal/channel/common/TransmissionPolicyManager.java

I found this during testing. We should include this in the next release.

remove ThreadLocal when it's no longer used

---

core/src/main/java/com/microsoft/applicationinsights/internal/quickpulse/DefaultQuickPulseDataFetcher.java

Fix QPS (Livemetrics) Invariant version number. Currently Java SDK only supports QPS v1.

Fix qps invariant version from 2 -> 1

---

CHANGELOG.md
core/src/main/java/com/microsoft/applicationinsights/internal/channel/common/ApacheSender43.java

Fix #898  .
Increase the persistent http connection validation period to be equal to the socket timeout period.
This prevents generation of messages like following:
` DEBUG wire                           - http-outgoing-11 << "[read] I/O error: Read timed out"` 
on the client side. 
Suggestion was borrowed based on stackoverflow article: https://stackoverflow.com/questions/34513826/apache-http-client-prints-read-i-o-error-read-timed-out

Increase persistent http connection validation period

---

test/smoke/framework/testCore/src/main/java/com/microsoft/applicationinsights/smoketest/docker/AiDockerClient.java
test/smoke/testApps/AutoPerfCounters/src/main/resources/ApplicationInsights.xml
test/smoke/testApps/CachingCalculator/src/main/resources/ApplicationInsights.xml
test/smoke/testApps/CoreAndFilter/src/main/java/com/microsoft/ajl/simplecalc/SimpleTestRequestSlowWithResponseTime.java
test/smoke/testApps/CoreAndFilter/src/main/resources/ApplicationInsights.xml
test/smoke/testApps/CoreAndFilter/src/smokeTest/java/com/microsoft/applicationinsights/smoketest/CoreAndFilterTests.java
test/smoke/testApps/FixedRateSampling/src/main/resources/ApplicationInsights.xml
test/smoke/testApps/HeartBeat/src/main/resources/ApplicationInsights.xml
test/smoke/testApps/PerfTestApp/src/main/resources/ApplicationInsights.xml
test/smoke/testApps/SpringBootTest/src/main/resources/application.properties
test/smoke/testApps/TraceLog4j1_2/src/main/resources/ApplicationInsights.xml
test/smoke/testApps/TraceLog4j2/src/main/resources/ApplicationInsights.xml
test/smoke/testApps/TraceLogBack/src/main/resources/ApplicationInsights.xml

Adjust timeout for failing test.
Disable QuickPulse in smoketests since it continually pings the actual QuickPulse endpoint.
Parameterized the "slow response time" smoketest app.

smoketest update

---

test/smoke/testApps/build.gradle

After #908, the upgrade broke one thing in the smokeTests. Apparently, `processSmokeTestResources` no longer ran after the `assemble` task. This adds that dependency and adds an error condition if the test app is missing from its libs directory.

Fix smokeTests in Gradle 5

---

core/native.gradle

using VisuallCpp config instead of manual libpath
removed unneeded debug buildType

Use gradle provided native conifg instead of custom libpath

---

collectd/build.gradle
distributions/build.gradle
gradle/common-java.gradle
logging/log4j2/build.gradle
settings.gradle
test/smoke/appServers/JBossEAP.7/build.gradle
test/smoke/build.gradle
test/smoke/testApps/TraceLog4j2/build.gradle
test/smoke/testApps/TraceLog4j2/src/main/java/com/microsoft/ajl/simplecalc/SimpleTestTraceLog4j2Servlet.java
test/smoke/testApps/TraceLog4j2/src/main/java/com/microsoft/ajl/simplecalc/SimpleTestTraceLog4j2WithExceptionServlet.java
test/smoke/testApps/build.gradle

for some reason, pre-v5 gradle ran the annotation processors even when included in a `compile` dependency. In gradle 5, they must be declared as `annotationProcessor` dependencies.
Also:
* corrected some task dependencies from gradle upgrade.
* simplified the bootstrapClasspath code
* removed some redundant file collection construction

Fix log4j2 appender build

---

logging/log4j2/appenderSrc/test/java/com/microsoft/applicationinsights/log4j/v2/internal/ApplicationInsightsLogEventTest.java

Compile errors from last merge: some interface methods not implemented. The must've added some between 2.1 and 2.11.0

Fix broken log4j2 unit test

---

ApplicationInsightsInternalLogger/build.gradle
agent/build.gradle
collectd/build.gradle
core/build.gradle
core/native.gradle
core/src/windows/cpp/CppPerfCounters.cpp
logging/logging.gradle
test/smoke/testApps/build.gradle
web/build.gradle

* Fixes issues with the hamcrest/mockito/junit combo.
* Adds env vars `APPINSIGHTS_WIN_SDK_PATH` and `APPINSIGHTS_VS_PATH` for specifying the location of the Windows SDK and Visual Studio build tools, respectively.
* Update native.gradle to not need absolute paths for .net reference assemblies (remove /FU option and add `#using` directive)

Build script fixes

---

CHANGELOG.md
core/src/main/java/com/microsoft/applicationinsights/internal/agent/CoreAgentNotificationsHandler.java

Make the Explain query string comparison continue regardless of the casing (upper, lower, mixed) for a statement starting with `SELECT`.
Fix #907 .

command name string comparison case insensitive

---

azure-application-insights-spring-boot-starter/src/main/java/com/microsoft/applicationinsights/autoconfigure/ApplicationInsightsProperties.java
azure-application-insights-spring-boot-starter/src/main/java/com/microsoft/applicationinsights/autoconfigure/HeartBeatProvider/SpringBootHeartBeatProvider.java

Springbootstarter findbugs fixes

---

core/src/main/java/com/microsoft/applicationinsights/internal/perfcounter/UnixParsingState.java
core/src/main/java/com/microsoft/applicationinsights/internal/perfcounter/UnixProcessIOtParser.java
core/src/main/java/com/microsoft/applicationinsights/internal/perfcounter/UnixTotalMemInfoParser.java
core/src/main/java/com/microsoft/applicationinsights/internal/perfcounter/WindowsPerformanceCounterAsMetric.java
core/src/main/java/com/microsoft/applicationinsights/internal/perfcounter/WindowsPerformanceCounterAsPC.java
core/src/main/java/com/microsoft/applicationinsights/internal/perfcounter/WindowsPerformanceCounterData.java
core/src/main/java/com/microsoft/applicationinsights/internal/quickpulse/QuickPulseDataCollector.java
core/src/test/java/com/microsoft/applicationinsights/internal/perfcounter/WindowsPerformanceCounterDataTest.java

`UnixParsingState` and `WindowsPerformanceCounterData` missing accessors, making it possible to circumvent the setters with validation.
I'm deprecating the fields since their public facing. For v3, they'll be made private and deprecation removed.

Accessor fixes

---

NOTICE
gradle/publishing.gradle

* Javadoc classpath broke after removing `provided` configuration.
* updated 3rd party versions in NOTICE.

Fix Javadoc classpath + update NOTICE

---

agent/src/main/java/com/microsoft/applicationinsights/agent/internal/config/AgentConfigurationDefaultImpl.java
agent/src/test/java/com/microsoft/applicationinsights/agent/internal/config/XmlAgentConfigurationTest.java
test/smoke/framework/utils/build.gradle
test/smoke/framework/utils/src/main/java/com/microsoft/applicationinsights/smoketest/matchers/ExceptionDataMatchers.java
test/smoke/framework/utils/src/main/java/com/microsoft/applicationinsights/smoketest/matchers/PageViewDataMatchers.java
test/smoke/framework/utils/src/main/java/com/microsoft/applicationinsights/smoketest/matchers/RequestDataMatchers.java
test/smoke/framework/utils/src/main/java/com/microsoft/applicationinsights/smoketest/matchers/TraceDataMatchers.java
test/smoke/testApps/AutoPerfCounters/src/main/resources/ApplicationInsights.xml
test/smoke/testApps/CachingCalculator/src/main/resources/ApplicationInsights.xml
test/smoke/testApps/CoreAndFilter/src/main/resources/ApplicationInsights.xml
test/smoke/testApps/CoreAndFilter/src/smokeTest/java/com/microsoft/applicationinsights/smoketest/CoreAndFilterTests.java
test/smoke/testApps/FixedRateSampling/src/main/resources/ApplicationInsights.xml
test/smoke/testApps/HeartBeat/src/main/resources/ApplicationInsights.xml
test/smoke/testApps/SpringBootTest/src/main/java/com/springbootstartertest/controller/JdbcTestController.java
test/smoke/testApps/SpringBootTest/src/main/resources/application.properties
test/smoke/testApps/SpringBootTest/src/smokeTest/java/com/springbootstartertest/smoketest/SpringbootSmokeTest.java
test/smoke/testApps/TraceLog4j1_2/src/main/resources/ApplicationInsights.xml
test/smoke/testApps/TraceLog4j1_2/src/smokeTest/java/com/microsoft/applicationinsights/smoketest/TraceLog4j1_2Test.java
test/smoke/testApps/TraceLog4j2/src/main/resources/ApplicationInsights.xml
test/smoke/testApps/TraceLog4j2/src/smokeTest/java/com/microsoft/applicationinsights/smoketest/TraceLog4j2Test.java
test/smoke/testApps/TraceLogBack/src/main/resources/ApplicationInsights.xml
test/smoke/testApps/TraceLogBack/src/smokeTest/java/com/microsoft/applicationinsights/smoketest/TraceLogBackTest.java

1. Alters configuration files to accelerate telemetry buffer flush time.
2. Updates the JdbcTestController to skip init for drivers without hostname var set. This is so `@WithDependencyContainers` could be removed from SpringBootSmokeTest (which does not need dependency containers).
Two things caused failing tests while making these changes:
1. Npe from the agent:
```
AI_AGENT_MODE=default
Running Jetty:
AI: ERROR 03-07-2019 23:29:29.226+0000, 1(main): cannot parse the correlation format, will defaultto AI proprietory correlation
AI: ERROR 03-07-2019 23:29:29.228+0000, 1(main): cannot parse the correlation format, will defaultto AI proprietory correlation
AI: TRACE 03-07-2019 23:29:29.231+0000, 1(main): Outbound W3C tracing is enabled : false
AI: TRACE 03-07-2019 23:29:29.231+0000, …
```

Optimize smoke tests channel config

---

collectd/build.gradle
distributions/build.gradle

shadowJars were not being built.
updated jar closure to follow same convention as other build files.

fix jar task dependencies

---

agent/build.gradle
test/smoke/framework/testCore/src/main/java/com/microsoft/applicationinsights/smoketest/AiSmokeTest.java

This was causing jar signing to fail.
exclude LICENSE/NOTICE in intermediate jar task.
also, use a different directory so `-agent-intermediate` is not picked up by releases

Fix shadowJar tasks including same files twice

---

core/src/main/java/com/microsoft/applicationinsights/telemetry/BaseTelemetry.java

Fix #.
If the timestamp property is not set, a call to BaseTelemetry#toString will result in an NPE. This is irritating as for example IntelliJ's debugger and the Mockito mocking framework call #toString.
- [-] Design discussion issue #
- [-] Changes in public surface reviewed
- [-] CHANGELOG.md updated

DateFormatter is not null-safe

---

agent/dependency-check-suppressions.xml
azure-application-insights-spring-boot-starter/build.gradle
azure-application-insights-spring-boot-starter/dependency-check-suppressions.xml
build.gradle
gradle/common-java.gradle
web-auto/dependency-check-suppressions.xml
web/dependency-check-suppressions.xml

This will fail the build if it finds any CVEs in dependencies. You can find the reports in `<project>/build/reports/dependency-check-report.html`. The html has descriptions of CVEs and also has buttons which produce snippets for the suppressions file, if needed.
Most of our use of the dependencies flagged are for their interfaces and the CVEs were generally related to runtime issues. I upgraded libraries where I could. I'll roll-back and evaluate again if the smoke tests fail because of the upgrades.

Enable dependency-check build plugin

---

test/smoke/framework/testCases/src/main/java/com/microsoft/applicationinsights/smoketest/CustomAiTestCases.java
test/smoke/framework/testCases/src/main/java/com/microsoft/applicationinsights/smoketest/FixedAiTestCases.java
test/webapps/PerfTestApp/build.gradle

Also fix PerfTestApp build script. After testing the TLS changes, I had to make these changes to get the perftestapp to work.
The resolution strategy ensures the transitive dependencies of `project(':test:smoke:framework:testCases')` are resolved to the local maven repo.

update test cases classes to be java 7 compatible.

---

core/build.gradle
core/src/main/java/com/microsoft/applicationinsights/internal/config/JaxbAppInsightsConfigurationBuilder.java

To avoid this: https://x-stream.github.io/CVE-2016-3674.html
core.jar size:
* w/ stax driver: 16.8 MB (17,651,728 bytes) [xpp jars excluded]
* w/ xpp3 driver: 16.8 MB (17,677,957 bytes)

use the xpp3 parser

---

core/build.gradle
core/src/main/java/com/microsoft/applicationinsights/internal/channel/common/ApacheSender43.java
core/src/main/java/com/microsoft/applicationinsights/internal/util/NoSupportedProtocolsException.java
core/src/main/java/com/microsoft/applicationinsights/internal/util/SSLOptionsUtil.java
web/src/main/java/com/microsoft/applicationinsights/web/internal/correlation/CdsProfileFetcher.java

You can use `applicationinsights.ssl.protocols` to override. Empty value means <strike>let the JVM/Http client decide (i.e. the current behavior).</strike> use defaults: TLSv1.2 or v1.3.

Use tls1.2 by default

---

core/src/main/java/com/microsoft/applicationinsights/internal/channel/common/TransmissionNetworkOutput.java

E.g. this will log
```
AI: ERROR 06-08-2019 00:02:21.364+0000, 59(ActiveTransmissionNetworkOutput_1-2): Error sending data: Invalid instrumentation key
```
and other reasons that `400` responses are returned.

Log the reason for 400 errors

---

core/src/main/java/com/microsoft/applicationinsights/internal/perfcounter/JvmPerformanceCountersFactory.java
core/src/main/java/com/microsoft/applicationinsights/internal/perfcounter/jvm/GCPerformanceCounter.java
test/smoke/testApps/AutoPerfCounters/src/smokeTest/java/com/microsoft/applicationinsights/smoketest/PerfCountersDataTest.java

Fix GCPerformanceCounter not working

---

agent/build.gradle
agent/src/main/java/com/microsoft/applicationinsights/agent/internal/MainEntryPoint.java
agent/src/main/java/com/microsoft/applicationinsights/agent/internal/model/OutgoingSpanImpl.java
core/build.gradle
test/smoke/testApps/SpringBootTest/src/smokeTest/java/com/springbootstartertest/smoketest/SpringbootSmokeTest.java

`HttpURLConnection` instrumentation was not capturing the outgoing url.

Fix http remote dependency capture

---

agent/build.gradle
agent/src/main/java/com/microsoft/applicationinsights/agent/internal/AIAgentXmlLoader.java
agent/src/main/java/com/microsoft/applicationinsights/agent/internal/MainEntryPoint.java
agent/src/main/java/com/microsoft/applicationinsights/agent/internal/config/BuiltInInstrumentation.java
agent/src/main/java/com/microsoft/applicationinsights/agent/internal/config/builder/BuiltInInstrumentationBuilder.java
agent/src/main/java/com/microsoft/applicationinsights/agent/internal/config/builder/XmlAgentConfigurationBuilder.java
agent/src/main/java/com/microsoft/applicationinsights/agent/internal/config/builder/XmlParserUtils.java
core/build.gradle
test/smoke/testApps/TraceLog4j1_2UsingAgent/src/smokeTest/java/com/microsoft/applicationinsights/smoketest/TraceLog4j1_2Test.java
test/smoke/testApps/TraceLog4j2UsingAgent/src/smokeTest/java/com/microsoft/applicationinsights/smoketest/TraceLog4j2Test.java
test/smoke/testApps/TraceLogBackUsingAgent/src/smokeTest/java/com/microsoft/applicationinsights/smoketest/TraceLogBackTest.java

This allows configuring a `threshold` to be applied for logging capture in `AI-Agent.xml`, e.g.
```
...
<BuiltIn>
<Logging threshold="error" />
</BuiltIn>
...
```
The threshold (if specified) must be one of `trace`, `debug`, `info`, `warn`, `error`.
The default threshold applied is `warn`.

Add logging capture threshold

---

core/src/main/java/com/microsoft/applicationinsights/internal/config/JmxXmlElement.java
core/src/main/java/com/microsoft/applicationinsights/internal/config/PerformanceCountersXmlElement.java
core/src/main/java/com/microsoft/applicationinsights/internal/config/TelemetryProcessorXmlElement.java
core/src/main/java/com/microsoft/applicationinsights/internal/config/TelemetryProcessorsXmlElement.java
core/src/main/java/com/microsoft/applicationinsights/internal/config/WindowsPerformanceCounterXmlElement.java
core/src/test/java/com/microsoft/applicationinsights/internal/config/JaxbAppInsightsConfigurationBuilderTest.java
core/src/test/resources/ApplicationInsights2.xml

Registration of custom JMX performance counters was failing with error:
`Failed to register JMX performance counters: 'java.lang.ClassCastException: com.microsoft.applicationinsights.internal.config.WindowsPerformanceCounterXmlElement cannot be cast to com.microsoft.applicationinsights.internal.config.JmxXmlElement'`

Fix registration of custom JMX performance counters

---

core/src/main/java/com/microsoft/applicationinsights/TelemetryConfiguration.java

Partial Fix for #1043 
This prevents calls to 
```
telemetryConfig.getTelemetryInitializers().add(new MyTelemetryInitializer());
telemetryConfig.getContextInitializers().add(new MyContextInitializer());
```
Affecting other users on different threads who may be doing a 
```
com.microsoft.applicationinsights.TelemetryClient.track(TelemetryClient.java:428)
```
As this causes the lists to be enumerated and if changed from another thread while being enumerated you'll get the following exception. 
```
Caused by: java.util.ConcurrentModificationException
at java.util.ArrayList$Itr.checkForComodification(ArrayList.java:909)
at java.util.ArrayList$Itr.next(ArrayList.java:859)
at com.microsoft.applicationinsights.TelemetryClient.activateInitializers(TelemetryClient.java:460)
at …
```

Make lists threadsafe #1043

---

azure-application-insights-spring-boot-starter/dependency-check-suppressions.xml

will fix the "partial failures" in build.
same reasoning as last time: spring has dependency on jackson which is not used in our starter code

suppress cves from jackson

---

agent/build.gradle
agent/src/main/java/com/microsoft/applicationinsights/agent/internal/model/OutgoingSpanImpl.java
test/smoke/testApps/HttpClients/src/main/java/com/microsoft/applicationinsights/smoketestapp/HttpClientTestServlet.java
test/smoke/testApps/HttpClients/src/smokeTest/java/com/microsoft/applicationinsights/smoketestapp/HttpClientSmokeTest.java

Fix apache http client instrumentation

---

agent-codeless/build.gradle
agent-codeless/src/main/java/com/microsoft/applicationinsights/agentc/internal/model/QuerySpanImpl.java
test/smoke/testApps/MongoDB/build.gradle

This ideally should have been caught during merge from master, but the MongoDB smoke test wasn't added to build server list yet at that time.

Add MongoDB to codeless agent

---

core/src/main/java/com/microsoft/applicationinsights/TelemetryConfiguration.java
core/src/main/java/com/microsoft/applicationinsights/internal/config/TelemetryConfigurationFactory.java
core/src/main/java/com/microsoft/applicationinsights/internal/quickpulse/DefaultQuickPulseDataFetcher.java
core/src/main/java/com/microsoft/applicationinsights/internal/quickpulse/DefaultQuickPulsePingSender.java
core/src/test/java/com/microsoft/applicationinsights/TelemetryConfigurationTestHelper.java
core/src/test/java/com/microsoft/applicationinsights/extensibility/initializer/docker/DockerContextInitializerTests.java
core/src/test/java/com/microsoft/applicationinsights/internal/config/TelemetryConfigurationFactoryTest.java
core/src/test/java/com/microsoft/applicationinsights/internal/heartbeat/HeartbeatTests.java
core/src/test/java/com/microsoft/applicationinsights/internal/quickpulse/DefaultQuickPulseDataFetcherTests.java
core/src/test/java/com/microsoft/applicationinsights/internal/quickpulse/DefaultQuickPulsePingSenderTests.java

add tests to verify.
Fix #1089

fix quickpulse url construction.

---

agent-codeless/src/main/java/com/microsoft/applicationinsights/agentc/internal/AgentImpl.java
agent-codeless/src/main/java/com/microsoft/applicationinsights/agentc/internal/MainEntryPoint.java
agent-codeless/src/main/java/com/microsoft/applicationinsights/agentc/internal/model/Global.java
agent-codeless/src/main/java/com/microsoft/applicationinsights/agentc/internal/model/IncomingSpanImpl.java
agent-codeless/src/main/java/com/microsoft/applicationinsights/agentc/internal/model/LegacySDK.java
agent-codeless/src/main/java/com/microsoft/applicationinsights/agentc/internal/model/LocalSpanImpl.java
agent-codeless/src/main/java/com/microsoft/applicationinsights/agentc/internal/model/LoggerSpans.java
agent-codeless/src/main/java/com/microsoft/applicationinsights/agentc/internal/model/OutgoingSpanImpl.java
agent-codeless/src/main/java/com/microsoft/applicationinsights/agentc/internal/model/QuerySpanImpl.java

This fixes application failing with, e.g.
```
[ERROR   ] SRVE0777E: Exception thrown by application class 'com.microsoft.applicationinsights.agentc.shadow.com.google.common.base.Preconditions.checkNotNull:890'
java.lang.NullPointerException
at com.microsoft.applicationinsights.agentc.shadow.com.google.common.base.Preconditions.checkNotNull(Preconditions.java:890)
at com.microsoft.applicationinsights.agentc.internal.model.Global.getTelemetryClient(Global.java:72)
at com.microsoft.applicationinsights.agentc.internal.AgentImpl.startIncomingSpan(AgentImpl.java:70)
at org.glowroot.instrumentation.engine.impl.OptionalThreadContextImpl.startIncomingSpan(OptionalThreadContextImpl.java:89)
at org.glowroot.instrumentation.servlet.ServletInstrumentation.onBeforeCommon(ServletInstrumentation.java:437) …
```

Fix NullPointerException if agent fails to start

---

agent/src/main/java/com/microsoft/applicationinsights/agent/internal/model/AuxThreadContextImpl.java

The same issue was captured and tracked down in glowroot instrumentation test harness, via the play framework instrumentation.

Fix async thread tracking

---

agent-codeless/src/main/java/com/microsoft/applicationinsights/agentc/internal/AgentImpl.java
agent-codeless/src/main/java/com/microsoft/applicationinsights/agentc/internal/Configuration.java
agent-codeless/src/main/java/com/microsoft/applicationinsights/agentc/internal/MainEntryPoint.java
agent-codeless/src/main/java/com/microsoft/applicationinsights/agentc/internal/model/AsyncOutgoingSpanImpl.java
agent-codeless/src/main/java/com/microsoft/applicationinsights/agentc/internal/model/DistributedTraceContext.java
agent-codeless/src/main/java/com/microsoft/applicationinsights/agentc/internal/model/Global.java
agent-codeless/src/main/java/com/microsoft/applicationinsights/agentc/internal/model/IncomingSpanImpl.java
agent-codeless/src/main/java/com/microsoft/applicationinsights/agentc/internal/model/OutgoingSpanImpl.java
agent-codeless/src/main/java/com/microsoft/applicationinsights/agentc/internal/model/TelemetryCorrelationUtilsCore.java
agent-codeless/src/main/java/com/microsoft/applicationinsights/agentc/internal/model/ThreadContextImpl.java
agent-codeless/src/main/java/com/microsoft/applicationinsights/agentc/internal/model/TraceContextCorrelationCore.java
agent-codeless/src/test/java/com/microsoft/applicationinsights/agentc/internal/ConfigurationTest.java
agent-codeless/src/test/resources/ApplicationInsights.json
core/src/main/java/com/microsoft/applicationinsights/web/internal/correlation/TraceContextCorrelationCore.java
test/smoke/testApps/HttpClients/src/smokeTest/java/com/microsoft/applicationinsights/smoketestapp/HttpClientSmokeTest.java
test/smoke/testApps/SpringBootTest/src/smokeTest/java/com/springbootstartertest/smoketest/SpringbootSmokeTest.java
web/src/main/java/com/microsoft/applicationinsights/web/internal/correlation/TraceContextCorrelation.java

We should always use W3C distributed tracing. `requestIdBackCompat` config will still handle legacy distributed tracing. And there should be a way to disable outbound distributed tracing headers in case they impact downstream services.

W3C distributed tracing

---

core/src/main/java/com/microsoft/applicationinsights/common/CommonUtils.java

In some environments `getCanonicalHostName()` can take several seconds.
I think get `getHostName()` should be fine, since we are calling it on `localhost` anyways (this is what Glowroot uses to capture local host name, see https://github.com/glowroot/glowroot/blob/v0.13.5/agent/core/src/main/java/org/glowroot/agent/init/EnvironmentCreator.java#L66).

Improve startup time

---

agent-codeless/src/main/java/com/microsoft/applicationinsights/agentc/internal/model/LoggerSpans.java

This is needed now that logs can be captured outside of a request context.

Fix possible NullPointerException

---

core/src/main/java/com/microsoft/applicationinsights/extensibility/initializer/docker/internal/DockerContextPoller.java
core/src/main/java/com/microsoft/applicationinsights/internal/channel/common/ActiveTransmissionLoader.java
core/src/main/java/com/microsoft/applicationinsights/internal/quickpulse/QuickPulse.java
core/src/main/java/com/microsoft/applicationinsights/internal/util/ThreadPoolUtils.java

Concerned that it is preventing these threads from running in timely
fashing in some environments. Plus doesn't seem like this made much
difference for cold start time after further testing.

Revert background thread priority change

---

gradle.properties

So local builds will now be `2.5.2-BETA-SNAPSHOT`

Update version number

---

NOTICE
agent/build.gradle
agent/src/main/java/com/microsoft/applicationinsights/agent/internal/AIAgentXmlLoader.java
agent/src/main/java/com/microsoft/applicationinsights/agent/internal/AgentImpl.java
core/build.gradle

In particular, to pick up improved MongoDB instrumentation.

Update to latest instrumentation

---

azure-application-insights-spring-boot-starter/build.gradle

This does a few things:
1. Fixes the unnecessary inclusion of xmlpull and xstream in spring boot shadow
2. Uses shadow configuration for core and web so we don't have to manage their dependencies here (related to 1)
3. Removes an unnecessary relocation.

Fix springboot dependencies

---

agent/build.gradle

The `module-info.class` file that is present in the agent jar can cause apps that are using older versions of ClassGraph (previously known as FastClasspathScanner) to fail with error:
```
Unknown constant pool tag ... in classfile module-info.class
```
This issue is fixed in later versions of ClassGraph (see https://github.com/classgraph/classgraph/issues/141), but this PR will make Application Insights compatible with older versions of ClassGraph as well.

Fix incompatibility with some applications

---

agent/src/main/java/com/microsoft/applicationinsights/agent/internal/config/builder/XmlAgentConfigurationBuilder.java
azure-application-insights-spring-boot-starter/src/main/java/com/microsoft/applicationinsights/autoconfigure/HeartBeatProvider/SpringBootHeartBeatProvider.java
core/src/main/java/com/microsoft/applicationinsights/TelemetryClient.java
core/src/main/java/com/microsoft/applicationinsights/internal/channel/common/SenderThreadLocalBackOffData.java
core/src/main/java/com/microsoft/applicationinsights/internal/channel/common/SenderThreadsBackOffManager.java
core/src/main/java/com/microsoft/applicationinsights/internal/channel/common/TransmissionFileSystemOutput.java
core/src/main/java/com/microsoft/applicationinsights/internal/channel/sampling/FixedRateTelemetrySampler.java
core/src/main/java/com/microsoft/applicationinsights/internal/heartbeat/DefaultHeartBeatPropertyProvider.java
core/src/main/java/com/microsoft/applicationinsights/internal/heartbeat/WebAppsHeartbeatProvider.java
core/src/main/java/com/microsoft/applicationinsights/internal/perfcounter/JniPCConnector.java
core/src/main/java/com/microsoft/applicationinsights/internal/shutdown/SDKShutdownActivity.java
core/src/main/java/com/microsoft/applicationinsights/internal/system/SystemInformation.java
core/src/main/java/com/microsoft/applicationinsights/telemetry/Duration.java
web/src/main/java/com/microsoft/applicationinsights/web/extensibility/initializers/WebOperationNameTelemetryInitializer.java

Fix bugs from static analysis

---

core/src/main/java/com/microsoft/applicationinsights/internal/config/connection/ConnectionString.java
core/src/main/java/com/microsoft/applicationinsights/internal/config/connection/EndpointProvider.java
core/src/test/java/com/microsoft/applicationinsights/internal/config/connection/ConnectionStringParsingTests.java

When a protocol is missing, it should insert `https`, but this isn't working. The current result is missing "//", e.g. `http:example.com`.
Edit: Instead, we will be more strict an throw an exception when the an endpoint value in the connection string is missing a protocol.

Fix uribuilder in connection string parsing

---

CHANGELOG.md

updated changelog for 2.6.0-BETA.2

---

core/src/main/java/com/microsoft/applicationinsights/extensibility/context/ContextTagKeys.java
core/src/main/java/com/microsoft/applicationinsights/internal/util/MapUtil.java
core/src/main/java/com/microsoft/applicationinsights/telemetry/BaseTelemetry.java
core/src/main/java/com/microsoft/applicationinsights/telemetry/ContextTagsMap.java
core/src/main/java/com/microsoft/applicationinsights/telemetry/TelemetryContext.java
core/src/test/java/com/microsoft/applicationinsights/telemetry/ContextTagsMapTests.java
web/src/test/java/com/microsoft/applicationinsights/web/internal/correlation/TelemetryCorrelationUtilsTests.java

Fix #1180 
I created a wrapper map because the map reference escapes via `TelemetryContext.getTags()`.

Add field truncation to 

---

test/smoke/appServers/Jetty.9/jetty9.linux.partial.dockerfile

Dockerfile build for jetty is failing because central.maven.org now requires https (returns 501).

maven now requires https

---

agent-codeless/src/main/java/com/microsoft/applicationinsights/agentc/internal/Configuration.java
agent-codeless/src/main/java/com/microsoft/applicationinsights/agentc/internal/ConfigurationBuilder.java
agent-codeless/src/main/java/com/microsoft/applicationinsights/agentc/internal/MainEntryPoint.java
core/spotbugs.exclude.xml
core/src/main/java/com/microsoft/applicationinsights/internal/channel/common/ApacheSender43.java

Using environment variable `APPLICATIONINSIGHTS_HTTP_PROXY`.
Format is `[scheme://]host[:port]` where scheme defaults to `http` and port defaults to `80` for http and `443` for https.

Add http proxy configuration

---

azure-application-insights-spring-boot-starter/build.gradle

Fix #1199.
Introduced by this change: https://github.com/microsoft/ApplicationInsights-Java/commit/c898d4998ddde88f27b494bda0ac59962bf7e14f
Apparently the 'shadow' configuration (defined by the shadowJar plugin) adds the 'all' classifier to the dependency in the pom by default.
Using the shadow configuration as a dependency simplifies the build script and prevents the need to change the spring-boot-starter build file if web or core dependencies change.

fix classifier added by 'shadow' configuration

---

agent-codeless/package/Microsoft.ApplicationInsights.JavaCodelessAgent.nuspec
agent-codeless/src/main/java/com/microsoft/applicationinsights/agentc/internal/MainEntryPoint.java
agent-codeless/src/main/java/com/microsoft/applicationinsights/agentc/internal/diagnostics/DiagnosticsHelper.java
agent-codeless/src/main/java/com/microsoft/applicationinsights/agentc/internal/diagnostics/log/ApplicationInsightsDiagnosticsLogFilter.java
agent-codeless/src/main/java/com/microsoft/applicationinsights/agentc/internal/diagnostics/status/StatusFile.java
agent-codeless/src/main/resources/appsvc.ai.logback.xml
agent-codeless/src/main/resources/rp-logger-config/diagnostics.appender.xml
agent-codeless/src/main/resources/rp-logger-config/user-logfile.appender.xml
agent-codeless/src/test/java/com/microsoft/applicationinsights/agentc/internal/diagnostics/DiagnosticsTestHelper.java
agent-codeless/src/test/java/com/microsoft/applicationinsights/agentc/internal/diagnostics/log/ApplicationInsightsDiagnosticsLogFilterTests.java
agent-codeless/src/test/java/com/microsoft/applicationinsights/agentc/internal/diagnostics/status/StatusFileTests.java
gradle.properties
test/smoke/testApps/VerifyShading/src/main/java/com/microsoft/ajl/simple/TestController.java

<strike>APPLICATIONINSIGHTS_LOGDIR overrides user accessible log directory, which also overrides the 'site.logdir' value.</strike>
APPLICATIONINSIGHTS_DIAGNOSTICS_OUTPUT_DIRECTORY is linux only and overrides the internal log directory.
Updated package to contain different configs for windows and linux.

Fix appsvc windows log config and env var config 

---

azure-application-insights-spring-boot-starter/src/main/java/com/microsoft/applicationinsights/autoconfigure/ApplicationInsightsTelemetryAutoConfiguration.java

In Spring 2.2.x, adding this new flag to `application.properties`:
```
spring.main.lazy-initialization=true
```
causes our spring boot starter not to create and register the `TelemetryChannel` (because no one depends on that bean, so it is never created in "lazy" mode), and so `NopTelemetryChannel` is used and no telemetry is sent.

Fix Spring Boot Starter failing with lazy init

---

web/src/main/java/com/microsoft/applicationinsights/web/internal/SdkBridgeImpl.java

We weren't passing `Request-Context` when backcompat is enabled, which means if a downstream service is in a different Application Insights resource, it won't be able to link back up to the original request (until the new distributed tracing indexer is in place, but that could be some time still).

Fix W3C BackCompat

---

core/src/main/java/com/microsoft/applicationinsights/internal/quickpulse/QuickPulse.java

For short-running applications that never perform a GC, this non-daemon thread used during startup is never collected and prevents normal termination at the end of the `main` method.

Fix shutdown issue due to non-daemon thread

---

core/src/main/java/com/microsoft/applicationinsights/internal/channel/common/TransmissionFileSystemOutput.java

File.lastModified() may be not enough precise to order files.
Some Filesystem only keep 1 second precision for this date.
I suggest to include a timestamp in temp file name so that
we can order files by names.
Fix # .

Fix potential file ordering issue.

---

CHANGELOG.md
core/native.gradle
core/src/main/java/com/microsoft/applicationinsights/internal/perfcounter/JniPCConnector.java
core/src/main/java/com/microsoft/applicationinsights/internal/system/SystemInformation.java
gradle.properties

I made the logs more specific and added info messages when we find the PID from the MXBean.

Improve logging/exception handling loading JNI perf counter lib

---

agent/agent-bootstrap/src/main/java/com/microsoft/applicationinsights/agent/bootstrap/MainEntryPoint.java
agent/agent-bootstrap/src/main/java/com/microsoft/applicationinsights/agent/bootstrap/diagnostics/etw/EtwAppender.java
agent/agent/src/main/java/io/opentelemetry/auto/bootstrap/AgentBootstrap.java
agent/exporter/src/main/java/com/microsoft/applicationinsights/agent/Exceptions.java
core/spotbugs.exclude.xml
core/src/main/java/com/microsoft/applicationinsights/TelemetryClient.java
core/src/main/java/com/microsoft/applicationinsights/channel/concrete/TelemetryChannelBase.java
core/src/main/java/com/microsoft/applicationinsights/internal/jmx/JmxDataFetcher.java
core/src/main/java/com/microsoft/applicationinsights/internal/perfcounter/JniPCConnector.java
core/src/main/java/com/microsoft/applicationinsights/internal/perfcounter/PerformanceCounterContainer.java
core/src/main/java/com/microsoft/applicationinsights/internal/perfcounter/UnixProcessIOPerformanceCounter.java
core/src/main/java/com/microsoft/applicationinsights/internal/perfcounter/UnixTotalCpuPerformanceCounter.java
core/src/main/java/com/microsoft/applicationinsights/internal/util/LimitsEnforcer.java
core/src/main/java/com/microsoft/applicationinsights/internal/util/PeriodicTaskPool.java
core/src/main/java/com/microsoft/applicationinsights/web/internal/correlation/CdsProfileFetcher.java
etw/README.md
etw/java/src/main/java/com/microsoft/applicationinsights/agent/bootstrap/diagnostics/etw/events/model/IpaEtwEventBase.java
etw/java/src/main/java/com/microsoft/applicationinsights/agent/bootstrap/diagnostics/etw/events/model/IpaEtwEventErrorBase.java
etw/java/src/test/java/com/microsoft/applicationinsights/agent/bootstrap/diagnostics/etw/EtwProviderTests.java
etw/native/src/main/cpp/etw_provider.cpp
etw/native/src/main/headers/etw_provider.h

The removes the fields _Logger_, _ResourceType_, _InstrumentationKey_, _Exception_ and _Operation_. 
I updated the message to this format: 
* `[logger/operation] message\n stacktrace`
* `[-/operation] message`
* `[logger] message`
* `[] message`
* `[]`
The variations shown illustrate what **msg** will look like if some variables are empty.

Update ETW fields

---

core/src/main/java/com/microsoft/applicationinsights/common/CommonUtils.java

`InetAddress.getCanonicalHostName()` looks up FQDN, which can be very slow on some systems.
This is already fixed in the 3.0 preview branch.

Fix perf issue resolving FQDN for localhost

---

core/src/main/java/com/microsoft/applicationinsights/internal/channel/common/ErrorHandler.java
core/src/main/java/com/microsoft/applicationinsights/internal/channel/common/TransmissionSendResult.java

Fixes an issue where read timeout (and other networking related exceptions) are not retried, e.g.
```
AI: ERROR 09-07-2020 06:02:52.258+0000, 547(ActiveTransmissionNetworkOutput_1-4): Failed to send.
Stack Trace:
java.net.SocketTimeoutException: Read timed out
at java.net.SocketInputStream.socketRead0(Native Method)
at java.net.SocketInputStream.socketRead(SocketInputStream.java:116)
at java.net.SocketInputStream.read(SocketInputStream.java:171)
at java.net.SocketInputStream.read(SocketInputStream.java:141)
at sun.security.ssl.InputRecord.readFully(InputRecord.java:465)
at sun.security.ssl.InputRecord.read(InputRecord.java:503)
at sun.security.ssl.SSLSocketImpl.readRecord(SSLSocketImpl.java:975)
at sun.security.ssl.SSLSocketImpl.readDataRecord(SSLSocketImpl.java:933)
at …
```

Retry transmission on client side exception

---

CHANGELOG.md
web/src/main/java/com/microsoft/applicationinsights/web/internal/WebRequestTrackingFilter.java

Fix #1281 by adding a simple null check in WebRquestTrackingFilter
If needed, here's a line for CHANGELOG.md (I don't know what version to tag it under. I'm happy to add this to my PR if I know where to put it):
* Fixed NullPointer when testing with MockMvc ([#](https://github.com/microsoft/ApplicationInsights-Java/issues/1281))

Resolve NullPointer exception when running under test with MockMvc

---

agent/agent-bootstrap/src/main/java/com/microsoft/applicationinsights/agent/bootstrap/configuration/ConfigurationBuilder.java
agent/agent-bootstrap/src/main/java/com/microsoft/applicationinsights/agent/bootstrap/configuration/InstrumentationSettings.java
core/src/main/java/com/microsoft/applicationinsights/internal/jmx/JmxDataFetcher.java
core/src/main/java/com/microsoft/applicationinsights/internal/perfcounter/AbstractJmxPerformanceCounter.java

Fix [#8242793](https://msazure.visualstudio.com/One/_boards/board/t/Azure%20Attach%20(Java%20NET)/Features/?workitem=8242793), [#8087964](https://msazure.visualstudio.com/One/_boards/board/t/Azure%20Attach%20(Java%20NET)/Features/?workitem=8087964), [#7965248](https://msazure.visualstudio.com/One/_boards/board/t/Azure%20Attach%20(Java%20NET)/Features/?workitem=7965248)
boolean JMX counter will look like the following in Application Insights:
Testing was done manually using the spring-petclinic application.

Improve JMX performance counter

---

core/spotbugs.exclude.xml

Remove the SimpleHttpChannel from the Spotbug exclusions since it doesn't exists anymore :)

SimpleHttpChannel has been deleted

---

agent/exporter/src/main/java/com/microsoft/applicationinsights/agent/Exporter.java

All telemetry records already have a timestamp. This property is further confusing because the date format is hard-coded (see #1322).

Remove unnecessary custom property

---

agent/agent-tooling/src/main/java/com/microsoft/applicationinsights/agent/internal/sampling/FixedRateSampler.java
agent/exporter/src/main/java/com/microsoft/applicationinsights/agent/Exporter.java
test/smoke/testApps/HttpClients/src/smokeTest/java/com/microsoft/applicationinsights/smoketestapp/HttpClientSmokeTest.java
test/smoke/testApps/JMS/src/smokeTest/java/com/microsoft/applicationinsights/smoketest/JmsTest.java
test/smoke/testApps/Kafka/src/smokeTest/java/com/microsoft/applicationinsights/smoketest/KafkaTest.java
test/smoke/testApps/SpringBootTest/src/smokeTest/java/com/springbootstartertest/smoketest/SpringbootSmokeTest.java
test/smoke/testApps/SpringCloudStream/src/smokeTest/java/com/microsoft/applicationinsights/smoketest/SpringCloudStreamTest.java
test/smoke/testApps/WebFlux/src/smokeTest/java/com/microsoft/applicationinsights/smoketest/WebFluxTest.java
test/smoke/testApps/gRPC/src/smokeTest/java/com/microsoft/applicationinsights/smoketest/GrpcTest.java

Users will be able to use config-based telemetry processors to bring back old names if really desired.

Use span name directly for telemetry name

---

agent/agent-bootstrap/src/main/java/com/microsoft/applicationinsights/agent/bootstrap/configuration/Configuration.java
agent/agent-tooling/src/main/java/com/microsoft/applicationinsights/agent/internal/BeforeAgentInstaller.java
agent/agent-tooling/src/main/java/com/microsoft/applicationinsights/agent/internal/SamplingPercentage.java
agent/agent-tooling/src/test/java/com/microsoft/applicationinsights/agent/internal/SamplingPercentageTest.java

* Round sampling percentage to the nearest 100/N, and log warning if the result is "significantly" different from what the user configured
* Make OpenTelemetry API support opt-in prior to OTel GA

More configuration changes

---

core/src/main/java/com/microsoft/applicationinsights/internal/perfcounter/JmxMetricPerformanceCounter.java
core/src/main/java/com/microsoft/applicationinsights/internal/perfcounter/ProcessMemoryPerformanceCounter.java
core/src/main/java/com/microsoft/applicationinsights/internal/perfcounter/jvm/DeadLockDetectorPerformanceCounter.java
core/src/main/java/com/microsoft/applicationinsights/internal/perfcounter/jvm/GCPerformanceCounter.java
core/src/main/java/com/microsoft/applicationinsights/internal/perfcounter/jvm/JvmHeapMemoryUsedPerformanceCounter.java
test/smoke/testApps/AutoPerfCounters/src/smokeTest/java/com/microsoft/applicationinsights/smoketest/PerfCountersDataTest.java

CustomMetrics:
"Private Bytes"
“Heap Memory Used (MB)”
“GC Total Time”
“GC Total Count”
"Loaded Class Count"
"Current Thread Count"
"Suspected Deadlocked Threads"
Keep the following in PerformanceCounter (used by the Performance blade on the portal):
“Available Bytes”
“% Processor Time”
“IO Data Bytes/sec”

Send JMX metrics to CustomMetrics instead of PerformanceCounter

---

agent/agent-tooling/src/main/java/com/microsoft/applicationinsights/agent/internal/sampling/TraceIdBasedSampler.java
agent/exporter/src/main/java/com/microsoft/applicationinsights/agent/Exporter.java

No need to remove semantic attributes during mapping, since not capturing any of them anyways.

Exporter code simplification

---

CHANGELOG.md
agent/agent-tooling/src/main/java/com/microsoft/applicationinsights/agent/internal/processors/AgentProcessor.java
agent/agent-tooling/src/test/java/com/microsoft/applicationinsights/agent/internal/processors/ExporterWithAttributeProcessorTest.java

fix for issue where null pointer exception is thrown when attribute value is not provided and matchType is regexp

fix for issue where null pointer exception is thrown when attribute value is not provided and matchType is regexp

---

agent/agent-tooling/src/main/java/com/microsoft/applicationinsights/agent/internal/BeforeAgentInstaller.java

Supports:
```
{
"instrumentation": {
"x": {
"enabled": false
}
}
}
```
for `x` in (`mongo`, `cassandra`, `redis`, `kafka`)
Resolves #1294

Add configuration for disabling dependencies

---

agent/agent-tooling/src/main/java/com/microsoft/applicationinsights/agent/internal/BeforeAgentInstaller.java
test/smoke/appServers/global-resources/logging_applicationinsights.json
test/smoke/testApps/TraceJavaUtilLoggingUsingAgent/src/smokeTest/java/com/microsoft/applicationinsights/smoketest/TraceJavaUtilLoggingTest.java
test/smoke/testApps/TraceLog4j1_2/src/smokeTest/java/com/microsoft/applicationinsights/smoketest/TraceLog4j1_2Test.java
test/smoke/testApps/TraceLog4j1_2UsingAgent/src/smokeTest/java/com/microsoft/applicationinsights/smoketest/TraceLog4j1_2Test.java
test/smoke/testApps/TraceLog4j2/src/smokeTest/java/com/microsoft/applicationinsights/smoketest/TraceLog4j2Test.java
test/smoke/testApps/TraceLog4j2UsingAgent/src/smokeTest/java/com/microsoft/applicationinsights/smoketest/TraceLog4j2Test.java
test/smoke/testApps/TraceLogBack/src/smokeTest/java/com/microsoft/applicationinsights/smoketest/TraceLogBackTest.java
test/smoke/testApps/TraceLogBackUsingAgent/src/smokeTest/java/com/microsoft/applicationinsights/smoketest/TraceLogBackTest.java

The code was using `level` in one place and `threshold` in another.
`level` is correct (and what's in documentation).
This PR also improves the tests so that the would have caught this issue.
Resolves #1415

Fix logging configuration

---

agent/agent-tooling/src/main/java/com/microsoft/applicationinsights/agent/internal/BeforeAgentInstaller.java

Resolves #1294
The underlying opentelemetry instrumentation project changed configuration property names from `ota.integration.*` to `otel.instrumentation.*`.

Fix disabling of dependencies

---

agent/agent-bootstrap/src/main/java/com/microsoft/applicationinsights/agent/bootstrap/MainEntryPoint.java

Muzzle is very verbose at WARN level, default should be ERROR.

Fix default muzzle logging level

---

agent/agent-bootstrap/src/main/java/com/microsoft/applicationinsights/agent/bootstrap/configuration/ConfigurationBuilder.java
agent/agent-bootstrap/src/test/java/com/microsoft/applicationinsights/agent/bootstrap/configuration/ConfigurationTest.java
agent/agent-tooling/src/main/java/com/microsoft/applicationinsights/agent/internal/BeforeAgentInstaller.java
core/src/main/java/com/microsoft/applicationinsights/internal/config/TelemetryConfigurationFactory.java

Resolves #1428
The problem is with this code that was introduced in 3.0.1-BETA:
https://github.com/microsoft/ApplicationInsights-Java/blob/1ec91209c6fe14ee4e38cbae030bde6ceea82405/agent/agent-tooling/src/main/java/io/opentelemetry/javaagent/tooling/TracerInstaller.java#L43-L49
Because `APPLICATIONINSIGHTS_CONNECTION_STRING` was being resolved later on instead of up front in the config object like other env vars.
This PR moves the resolving of both `APPLICATIONINSIGHTS_CONNECTION_STRING` and the legacy `APPINSIGHTS_INSTRUMENTATIONKEY` to `ConfigurationBuilder`, which makes this code correct.

Fix APPLICATIONINSIGHTS_CONNECTION_STRING env var

---

agent/agent-tooling/src/main/java/com/microsoft/applicationinsights/agent/internal/BeforeAgentInstaller.java
agent/agent-tooling/src/main/java/com/microsoft/applicationinsights/agent/internal/DuplicateAgentClassFileTransformer.java
agent/agent-tooling/src/main/java/com/microsoft/applicationinsights/agent/internal/JulListeningClassFileTransformer.java
agent/agent-tooling/src/main/java/com/microsoft/applicationinsights/agent/internal/instrumentation/sdk/UnshadedSdkPackageName.java
agent/agent/src/main/java/io/opentelemetry/javaagent/OpenTelemetryAgent.java

This PR makes sure that, as long as the 3.0.0 java agent is the first `-javaagent` on the command line, that it will suppress other Application Insights java agents.
This is primarily helpful for App Services attach, where we use `JAVA_TOOL_OPTIONS` (which is prepended to the command line args).
This also resolves #1345 😄 (https://stackoverflow.com/questions/60838748/intellij-idea-java-instrumentation-premain-gets-called-twice-when-directly-run).

Suppress duplicate AI agents

---

agent/agent-tooling/src/main/java/com/microsoft/applicationinsights/agent/internal/BeforeAgentInstaller.java

Simpler when there is just one way to configure a particular behavior.
In this case, we can already suppress log capture using APPLICATIONINSIGHTS_INSTRUMENTATION_LOGGING_LEVEL=OFF (and similar in json).

Remove duplicate configuration setting for suppressing logging

---

agent/agent-tooling/build.gradle

The agent jar file got really big with latest otel update, trimming it back down to normal here.

Remove unnecessary dependencies

---

agent/agent-tooling/src/main/java/com/microsoft/applicationinsights/agent/internal/BeforeAgentInstaller.java

Fix disabling micrometer

---

agent/agent-tooling/src/main/java/com/microsoft/applicationinsights/agent/internal/wasbootstrap/ConfigOverride.java
agent/instrumentation/build.gradle
test/smoke/testApps/CoreAndFilter/src/smokeTest/java/com/microsoft/applicationinsights/smoketest/CoreAndFilterTests.java
test/smoke/testApps/OpenTelemetryApiSupport/build.gradle
test/smoke/testApps/OpenTelemetryApiSupport/src/main/java/com/microsoft/ajl/simple/TestController.java
test/smoke/testApps/OpenTelemetryApiSupport/src/smokeTest/java/com/microsoft/applicationinsights/smoketest/OpenTelemetryApiSupportTest.java
test/smoke/testApps/SpringBootTest/src/smokeTest/java/com/springbootstartertest/smoketest/SpringbootSmokeTest.java
test/smoke/testApps/SpringCloudStream/src/smokeTest/java/com/microsoft/applicationinsights/smoketest/SpringCloudStreamTest.java
test/smoke/testApps/WebFlux/src/main/java/com/microsoft/ajl/simple/TestController.java

Adds the following instrumentation:
* opentelemetry-annotations
* reactor-netty (this is important to spring ecosystem)
* kotlinx-coroutintes (this was split out of java-concurrent instrumentation)
* tomcat (this captures server requests earlier, which can lead to correctly capturing response code in cases where it wasn't previously)
Only added smoke test for `opentelemetry-annotations`. The others I think are ok to only rely on OpenTelemetry tests.

Add more instrumentation

---

.github/workflows/pr.yaml

Noticed that the CI build (on merge) wasn't running GHA.

Fix GHA branch name

---

agent/exporter/src/main/java/com/microsoft/applicationinsights/agent/Exporter.java

This is just re-ordering of code inside of Exporter to make it easier to compare and see differences with https://github.com/Azure/azure-sdk-for-java/blob/master/sdk/monitor/azure-monitor-opentelemetry-exporter/src/main/java/com/azure/monitor/opentelemetry/exporter/AzureMonitorTraceExporter.java

Re-order Exporter to match Azure SDK Exporter

---

agent/agent-tooling/src/main/java/com/microsoft/applicationinsights/agent/internal/propagator/AiLegacyPropagator.java
core/src/main/java/com/microsoft/applicationinsights/internal/channel/common/TransmissionPolicyManager.java

Generally preserving info logging (which is logged by default) for startup logging.
These two places can be downgraded to debug level.

Downgrade some info logging to debug level

---

agent/agent-tooling/src/main/java/com/microsoft/applicationinsights/agent/internal/wasbootstrap/configuration/ConfigurationBuilder.java
agent/agent-tooling/src/test/java/com/microsoft/applicationinsights/agent/internal/wasbootstrap/configuration/ConfigurationTest.java

This will be a popular preview feature, given azure sdk interop depends on it, so want to make it easy to enable in compute environments where we rely on env var configuration.

Add env var for otel preview

---

agent/agent-bootstrap/src/main/java/com/microsoft/applicationinsights/agent/bootstrap/diagnostics/DiagnosticsHelper.java
agent/agent-bootstrap/src/main/java/com/microsoft/applicationinsights/agent/bootstrap/diagnostics/status/StatusFile.java
agent/agent-bootstrap/src/test/java/com/microsoft/applicationinsights/agent/bootstrap/diagnostics/DiagnosticsTestHelper.java
agent/agent-bootstrap/src/test/java/com/microsoft/applicationinsights/agent/bootstrap/diagnostics/log/ApplicationInsightsDiagnosticsLogFilterTests.java
agent/agent-bootstrap/src/test/java/com/microsoft/applicationinsights/agent/bootstrap/diagnostics/status/StatusFileTests.java
agent/agent-tooling/src/main/java/com/microsoft/applicationinsights/agent/internal/AiComponentInstaller.java
agent/agent-tooling/src/main/java/com/microsoft/applicationinsights/agent/internal/wasbootstrap/MainEntryPoint.java
agent/agent-tooling/src/main/java/com/microsoft/applicationinsights/agent/internal/wasbootstrap/configuration/ConfigurationBuilder.java

Two sdk name improvements:
* use `f*r_java` when running in Azure Functions on App Services (instead of `awr_java`)
* use `s*r_java` when running in Spring Cloud with `springcloud.codeless` marker file
(and removed the restriction on using json files with attach, since spring cloud uses one)

Sdk name improvements

---

agent/agent-tooling/src/main/java/com/microsoft/applicationinsights/agent/internal/wasbootstrap/MainEntryPoint.java
agent/agent-tooling/src/main/java/com/microsoft/applicationinsights/agent/internal/wasbootstrap/configuration/ConfigurationBuilder.java
agent/agent-tooling/src/test/java/com/microsoft/applicationinsights/agent/internal/wasbootstrap/configuration/ConfigurationTest.java

Also introduces env var `APPLICATIONINSIGHTS_SELF_DIAGNOSTICS_FILE_PATH`, which can also be helpful in this case for redirecting log file to another location.

Always write to log on startup failure

---

gradle.properties

Next version will probably be 3.0.3 (GA), but bumping to 3.0.3-BETA.2 in the meantime so that snapshot builds don't still say 3.0.3-BETA-SNAPSHOT.

Bump version to 3.0.3-BETA.2

---

agent/instrumentation/build.gradle

Found this when comparing jar file sizes between 3.0.2 and 3.0.3-BETA

Remove unneeded dependency

---

agent/agent-tooling/src/main/java/com/microsoft/applicationinsights/agent/internal/sampling/Samplers.java

This way non-remote spans (e.g. dependencies) will just re-use the parent decision instead of re-calculating based on the trace id (same end result).

Use parent-based sampler mostly

---

agent/agent-tooling/src/main/java/com/microsoft/applicationinsights/agent/internal/AiComponentInstaller.java
agent/agent-tooling/src/main/java/com/microsoft/applicationinsights/agent/internal/RpConfigurationPolling.java
agent/agent-tooling/src/main/java/com/microsoft/applicationinsights/agent/internal/sampling/AiSampler.java
agent/agent-tooling/src/main/java/com/microsoft/applicationinsights/agent/internal/sampling/Samplers.java
agent/agent-tooling/src/main/java/com/microsoft/applicationinsights/agent/internal/wasbootstrap/OpenTelemetryConfigurer.java
agent/agent-tooling/src/main/java/com/microsoft/applicationinsights/agent/internal/wasbootstrap/configuration/Configuration.java
agent/agent-tooling/src/main/java/com/microsoft/applicationinsights/agent/internal/wasbootstrap/configuration/ConfigurationBuilder.java
agent/agent-tooling/src/main/java/com/microsoft/applicationinsights/agent/internal/wasbootstrap/configuration/RpConfiguration.java
agent/agent-tooling/src/test/java/com/microsoft/applicationinsights/agent/internal/RpConfigurationPollingTest.java
test/smoke/appServers/global-resources/telemetryfiltering2_applicationinsights.json
test/smoke/testApps/Sampling/src/smokeTest/java/com/microsoft/applicationinsights/smoketest/SamplingTest.java
test/smoke/testApps/TelemetryFiltering/src/main/java/com/microsoft/applicationinsights/smoketestapp/TelemetryFilteringTestServlet.java
test/smoke/testApps/TelemetryFiltering/src/smokeTest/java/com/microsoft/applicationinsights/smoketestapp/TelemetryFiltering2SmokeTest.java
test/smoke/testApps/TelemetryFiltering/src/smokeTest/java/com/microsoft/applicationinsights/smoketestapp/TelemetryFilteringSmokeTest.java

For example, if upstream span decides to sample 100% of `/login` requests, then downstream spans should respect that decision (as long as there is no specific override match for the downstream span), instead of applying the default sampling percentage to the downstream spans.

Respect parent sampled unless override match

---

agent/agent-tooling/src/main/java/com/microsoft/applicationinsights/agent/internal/sampling/Samplers.java
agent/agent-tooling/src/main/java/com/microsoft/applicationinsights/agent/internal/wasbootstrap/configuration/Configuration.java

This was a mistake to change this behavior for now reverting back to prior behavior by default.

Change default preview config setting

---

agent/agent-tooling/src/main/java/com/microsoft/applicationinsights/agent/internal/instrumentation/sdk/BytecodeUtilImpl.java
agent/agent-tooling/src/main/java/com/microsoft/applicationinsights/agent/internal/propagator/DelegatingPropagator.java
agent/agent-tooling/src/main/java/com/microsoft/applicationinsights/agent/internal/sampling/AiSampler.java
agent/agent-tooling/src/main/java/com/microsoft/applicationinsights/agent/internal/sampling/Samplers.java
agent/agent-tooling/src/main/java/com/microsoft/applicationinsights/agent/internal/sampling/SamplingOverrides.java
agent/agent-tooling/src/test/java/com/microsoft/applicationinsights/agent/internal/RpConfigurationPollingTest.java
agent/exporter/src/main/java/com/microsoft/applicationinsights/agent/Exporter.java
test/smoke/testApps/Sampling/build.gradle
test/smoke/testApps/Sampling/src/main/java/com/microsoft/ajl/simplecalc/SimpleSamplingServlet.java
test/smoke/testApps/Sampling/src/smokeTest/java/com/microsoft/applicationinsights/smoketest/SamplingTest.java

Refreshed #1477
We do have a need for variable sampling percentages now with [sampling overrides](https://docs.microsoft.com/en-us/azure/azure-monitor/app/java-standalone-sampling-overrides), so I think it makes sense to go ahead with using trace state, even if it's a bit hacky until the OTel spec is (hopefully) completed, at which time we can propagate the trace state over the wire too.

Fix sampling rate recorded for dependencies

---

agent/agent-tooling/src/main/java/com/microsoft/applicationinsights/agent/internal/wasbootstrap/ConfigOverride.java
agent/agent-tooling/src/main/java/com/microsoft/applicationinsights/agent/internal/wasbootstrap/configuration/Configuration.java
agent/agent-tooling/src/main/java/com/microsoft/applicationinsights/agent/internal/wasbootstrap/configuration/ConfigurationBuilder.java
agent/agent-tooling/src/test/java/com/microsoft/applicationinsights/agent/internal/wasbootstrap/configuration/ConfigurationTest.java
test/smoke/appServers/global-resources/azuresdk_applicationinsights.json

Improved the new preview config option to be consistent with non-preview options:
```
{
"preview": {
"instrumentation": {
"azureSdk": {
"enabled": true
}
}
}
}
```

Update azure sdk preview config

---

core/src/main/java/com/microsoft/applicationinsights/internal/perfcounter/PerformanceCounterContainer.java

This resulted in an incorrect error message when the interval was set to 1 second.

Fix wrong comparison operator

---

test/smoke/testApps/Sampling/src/main/java/com/microsoft/applicationinsights/smoketestapp/SimpleSamplingServlet.java
test/smoke/testApps/Sampling/src/smokeTest/java/com/microsoft/applicationinsights/smoketest/SamplingTest.java

Resolves #1620
The problem is that the sampling test sends 100 requests in rapid succession, and the downstream dependency connection to www.bing.com sometimes fails. The downstream dependency test is not really needed, as the test already has downstream custom event to make sure sampling affects downstream spans.

Fix sporadic CI failure

---

agent/agent-bootstrap/src/main/java/com/microsoft/applicationinsights/agent/bootstrap/BytecodeUtil.java
agent/agent-tooling/src/main/java/com/microsoft/applicationinsights/agent/internal/AiComponentInstaller.java
agent/agent-tooling/src/main/java/com/microsoft/applicationinsights/agent/internal/instrumentation/sdk/BytecodeUtilImpl.java
agent/agent-tooling/src/main/java/com/microsoft/applicationinsights/agent/internal/instrumentation/sdk/TelemetryClientClassFileTransformer.java
agent/exporter/src/main/java/com/microsoft/applicationinsights/agent/Exporter.java
core/src/main/java/com/microsoft/applicationinsights/TelemetryClient.java
test/smoke/appServers/global-resources/opentelemetryapisupport_applicationinsights.json
test/smoke/testApps/CoreAndFilter/build.gradle
test/smoke/testApps/CoreAndFilter/src/main/java/com/microsoft/applicationinsights/smoketestapp/SimpleTestRequestSlowWithResponseTime.java
test/smoke/testApps/CoreAndFilter/src/main/java/com/microsoft/applicationinsights/smoketestapp/SimpleTrackPageViewServlet.java
test/smoke/testApps/CoreAndFilter/src/main/java/com/microsoft/applicationinsights/smoketestapp/SlowRequestCpuBoundServlet.java
test/smoke/testApps/CoreAndFilter/src/smokeTest/java/com/microsoft/applicationinsights/smoketest/CoreAndFilterTests.java
test/smoke/testApps/OpenTelemetryApiSupport/src/main/java/com/microsoft/applicationinsights/smoketestapp/TestController.java
test/smoke/testApps/OpenTelemetryApiSupport/src/smokeTest/java/com/microsoft/applicationinsights/smoketest/OpenTelemetryApiSupportTest.java

Support overriding ikey, cloud role name and cloud role instance.
Example 1: Overriding on the current request
```
RequestTelemetry telemetry = ThreadContext.getRequestTelemetryContext().getHttpRequestTelemetry();
telemetry.getContext().setInstrumentationKey("...");
telemetry.getContext().getCloud().setRole("...");
telemetry.getContext().getCloud().setRoleInstance("...");
```
Example 2: Overriding on custom telemetry
```
EventTelemetry telemetry = new EventTelemetry("...");
requestTelemetry.getContext().setInstrumentationKey("...");
requestTelemetry.getContext().getCloud().setRole("...");
requestTelemetry.getContext().getCloud().setRoleInstance("...");
```
Example 3: Overriding using telemetry processor
Use span names:
* `ai.preview.instrumentation_key`
* `ai.preview.service_name`
* …

Support overriding ikey, cloud role name and cloud role instance per telemetry

---

agent/exporter/src/main/java/com/microsoft/applicationinsights/agent/Exporter.java
test/smoke/testApps/Jdbc/build.gradle
test/smoke/testApps/Jdbc/src/main/java/com/microsoft/applicationinsights/smoketestapp/JdbcTestServlet.java
test/smoke/testApps/Jdbc/src/smokeTest/java/com/microsoft/applicationinsights/smoketestapp/JdbcTest.java

Update otel fork submodule, see: #1645
Updates Jdbc smoke tests due to the new (better) target attribute.
Fixes an unrelated issue where the Jdbc smoke tests just started failing due to recent update in mysql image that requires enabling TLSv1.3 in the driver
Resolves #1640
Attaching SNAPSHOT release from this PR: [applicationinsights-agent-3.0.4-BETA-SNAPSHOT.jar.zip](https://github.com/microsoft/ApplicationInsights-Java/files/6362473/applicationinsights-agent-3.0.4-BETA-SNAPSHOT.jar.zip)

Fix for jdbc target and duplicate headers

---

CHANGELOG.md
agent/agent-tooling/src/main/java/com/microsoft/applicationinsights/agent/internal/wasbootstrap/OpenTelemetryConfigurer.java
agent/agent-tooling/src/main/java/com/microsoft/applicationinsights/agent/internal/wasbootstrap/configuration/Configuration.java
agent/agent-tooling/src/main/java/com/microsoft/applicationinsights/agent/internal/wasbootstrap/configuration/ConfigurationBuilder.java
agent/exporter/src/main/java/com/microsoft/applicationinsights/agent/Exporter.java
gradle.properties
test/smoke/appServers/global-resources/azuresdk_applicationinsights.json
test/smoke/appServers/global-resources/customdimensions_applicationinsights.json
test/smoke/appServers/global-resources/custominstrumentation_applicationinsights.json
test/smoke/appServers/global-resources/default_applicationinsights.json
test/smoke/appServers/global-resources/disabled_cassandra_applicationinsights.json
test/smoke/appServers/global-resources/disabled_jdbc_applicationinsights.json
test/smoke/appServers/global-resources/disabled_jms_applicationinsights.json
test/smoke/appServers/global-resources/disabled_kafka_applicationinsights.json
test/smoke/appServers/global-resources/disabled_micrometer_applicationinsights.json
test/smoke/appServers/global-resources/disabled_mongo_applicationinsights.json
test/smoke/appServers/global-resources/disabled_redis_applicationinsights.json
test/smoke/appServers/global-resources/disabled_springscheduling_applicationinsights.json
test/smoke/appServers/global-resources/fastheartbeat_applicationinsights.json
test/smoke/appServers/global-resources/fastmetrics_applicationinsights.json
test/smoke/appServers/global-resources/logging_applicationinsights.json
test/smoke/appServers/global-resources/micrometer_applicationinsights.json
test/smoke/appServers/global-resources/opentelemetryapisupport_applicationinsights.json
test/smoke/appServers/global-resources/sampling_applicationinsights.json
test/smoke/appServers/global-resources/telemetryfiltering2_applicationinsights.json
test/smoke/appServers/global-resources/telemetryfiltering_applicationinsights.json
test/smoke/appServers/global-resources/telemetryprocessors_applicationinsights.json

Bumping version to 3.1.0 since this is a significant change, will add "Upgrade from 3.0" page to official doc site to mention this.

Capture http method in operation name

---

core/src/main/java/com/microsoft/applicationinsights/internal/perfcounter/OshiPerformanceCounter.java

recurring nullpointerexception in AppSvc environment log.
`2021-05-12 20:49:59.904Z ERROR c.m.a.i.p.PerformanceCounterContainer - Exception while reporting performance counter 'JSDK_OshiPerformanceCounter'
java.lang.NullPointerException: null
at com.microsoft.applicationinsights.internal.perfcounter.OshiPerformanceCounter.updateAttributes(OshiPerformanceCounter.java:88)
at com.microsoft.applicationinsights.internal.perfcounter.OshiPerformanceCounter.report(OshiPerformanceCounter.java:65)
at com.microsoft.applicationinsights.internal.perfcounter.PerformanceCounterContainer$1.run(PerformanceCounterContainer.java:231)
at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308)
at …

Fix a NullPointerException in appsvc testing env.

---

agent/agent-profiler/agent-service-profiler/gradle/dependency-locks/compileClasspath.lockfile
agent/agent-profiler/agent-service-profiler/gradle/dependency-locks/runtimeClasspath.lockfile
agent/agent-profiler/agent-service-profiler/src/main/java/com/microsoft/applicationinsights/serviceprofilerapi/profiler/JfrProfiler.java
agent/instrumentation/gradle/dependency-locks/runtimeClasspath.lockfile
gradle/dependencies.gradle

Older Java 8s do not have the Mxbean that we used to control JFR. This fixes the initialisation where if the Mxbean is not available it will try using the alternate Diagnostic Command method.

Fix bug in initialising JFR integration when used with older Java 8

---

core/src/main/java/com/microsoft/applicationinsights/internal/statsbeat/BaseStatsbeat.java
core/src/main/java/com/microsoft/applicationinsights/internal/statsbeat/Instrumentations.java
core/src/main/java/com/microsoft/applicationinsights/internal/util/ExceptionStats.java

This also fixed an NullPointerException when trying to retrieve a custom instrumentation name from the Statsbeat instrumentation map. 
Using scheduleWithFixedDelay, I can no longer reproduce the duplicate attach Statsbeat with the same timestamp.

Fix attach statsbeat duplicates when computer resumes from sleep

---

core/src/main/java/com/microsoft/applicationinsights/telemetry/BaseTelemetry.java
core/src/test/java/com/microsoft/applicationinsights/telemetry/BaseTelemetryTest.java

Fix [#9860567](https://msazure.visualstudio.com/One/_sprints/taskboard/TelReachSDKTeam/One/AEP/Cobalt/2105?workitem=9860567)
sample envelopes with this change:

Use envelope name as the telemetry name and reduce payload

---

core/src/main/java/com/microsoft/applicationinsights/telemetry/RemoteDependencyTelemetry.java

Fix typo on the javadoc of the RemoteDependencyTelemetry constructor

Fix typo in javadoc

---

agent/agent-tooling/src/main/java/com/microsoft/applicationinsights/agent/internal/AiComponentInstaller.java
core/src/main/java/com/microsoft/applicationinsights/internal/schemav2/StackFrame.java
core/src/main/java/com/microsoft/applicationinsights/telemetry/ExceptionTelemetry.java

2021-05-20 17:44:13.245-07 DEBUG c.m.applicationinsights.agent - ############# current stack depth: 8943
2021-05-20 17:44:13.266-07 DEBUG c.m.a.telemetry.ExceptionTelemetry - parsedStack is exceeding 65536 bytes capacity. It is truncated from full **1024** frames to partial **308** frames.
@trask method call depth (8943) does not equal to the number of stack frames (total 1024). What i showed you earlier in Fiddler is the full stack.
When we add stack frame to ExceptionTelemetry, it's already in the reversed order.
Fix #482

Truncate exception telemetry's parsedStack when there is a deep stack trace exceeding 65536 bytes

---

core/src/main/java/com/microsoft/applicationinsights/internal/statsbeat/Feature.java
core/src/main/java/com/microsoft/applicationinsights/internal/statsbeat/FeatureStatsbeat.java
core/src/main/java/com/microsoft/applicationinsights/internal/statsbeat/Instrumentations.java
core/src/main/java/com/microsoft/applicationinsights/internal/statsbeat/NetworkStatsbeat.java
core/src/test/java/com/microsoft/applicationinsights/internal/statsbeat/FeatureTest.java
core/src/test/java/com/microsoft/applicationinsights/internal/statsbeat/InstrumentationsTest.java
core/src/test/java/com/microsoft/applicationinsights/internal/statsbeat/NetworkStatsbeatTest.java
core/src/test/java/com/microsoft/applicationinsights/internal/statsbeat/StatsbeatHelperTest.java
core/src/test/java/com/microsoft/applicationinsights/internal/statsbeat/StatsbeatTestUtils.java

kusto doesn't support converting base64 encoded string back to long.  
need to send it as UTF-8 string for instrumentation and feature.

Send instrumentation and feature as UTF-8 strings for Statsbeat

---

core/src/main/java/com/microsoft/applicationinsights/internal/profiler/ProfilerServiceInitializer.java

Emit profiler events that allow the back end to monitor when profiling starts/stops.

Emit Profiler start/stop events

---

agent/agent-tooling/src/main/java/com/microsoft/applicationinsights/agent/internal/instrumentation/sdk/BytecodeUtilImpl.java
core/src/main/java/com/microsoft/applicationinsights/extensibility/context/OperationContext.java
test/smoke/testApps/CoreAndFilter/src/main/java/com/microsoft/applicationinsights/smoketestapp/SimpleTrackPageViewServlet.java
test/smoke/testApps/CoreAndFilter/src/smokeTest/java/com/microsoft/applicationinsights/smoketest/CoreAndFilterTests.java

Attaching SNAPSHOT for testing: [applicationinsights-agent-3.1.1-BETA-SNAPSHOT.jar.zip](https://github.com/microsoft/ApplicationInsights-Java/files/6543566/applicationinsights-agent-3.1.1-BETA-SNAPSHOT.jar.zip)

2.x SDK explicit operation id / operation parent id should take precedence

---

agent/agent-tooling/spotbugs.exclude.xml
agent/agent-tooling/src/main/java/com/microsoft/applicationinsights/agent/internal/AiComponentInstaller.java
agent/agent-tooling/src/main/java/com/microsoft/applicationinsights/agent/internal/processors/AgentProcessor.java
agent/agent-tooling/src/main/java/com/microsoft/applicationinsights/agent/internal/processors/AttributeProcessor.java
agent/agent-tooling/src/main/java/com/microsoft/applicationinsights/agent/internal/sampling/SamplingOverrides.java
agent/agent-tooling/src/main/java/com/microsoft/applicationinsights/agent/internal/wasbootstrap/OpenTelemetryConfigurer.java
agent/agent-tooling/src/main/java/com/microsoft/applicationinsights/agent/internal/wasbootstrap/configuration/Configuration.java
agent/agent-tooling/src/test/java/com/microsoft/applicationinsights/agent/internal/processors/ExporterWithAttributeProcessorTest.java
agent/agent-tooling/src/test/java/com/microsoft/applicationinsights/agent/internal/processors/ExporterWithLogProcessorTest.java
agent/agent-tooling/src/test/java/com/microsoft/applicationinsights/agent/internal/processors/ExporterWithSpanProcessorTest.java
agent/agent-tooling/src/test/java/com/microsoft/applicationinsights/agent/internal/sampling/SamplingOverridesTest.java
agent/agent-tooling/src/test/java/com/microsoft/applicationinsights/agent/internal/wasbootstrap/configuration/ConfigurationTest.java
agent/agent-tooling/src/test/resources/ApplicationInsights_SpanProcessor.json
core/src/main/java/com/microsoft/applicationinsights/MetricFilter.java
core/src/main/java/com/microsoft/applicationinsights/TelemetryClient.java
core/src/main/java/com/microsoft/applicationinsights/TelemetryConfiguration.java
test/smoke/appServers/global-resources/micrometer_applicationinsights.json
test/smoke/testApps/Micrometer/src/main/java/com/microsoft/applicationinsights/smoketestapp/TestController.java
test/smoke/testApps/Micrometer/src/smokeTest/java/com/microsoft/applicationinsights/smoketest/MicrometerTest.java

Add metric filtering capability

---

agent/agent-tooling/src/main/java/com/microsoft/applicationinsights/agent/internal/wasbootstrap/configuration/ConfigurationBuilder.java
agent/agent-tooling/src/test/java/com/microsoft/applicationinsights/agent/internal/wasbootstrap/configuration/ConfigurationTest.java
agent/agent-tooling/src/test/resources/applicationinsights_aadauthenv.json
test/smoke/testApps/CoreAndFilter/src/smokeTest/java/com/microsoft/applicationinsights/smoketest/CoreAndFilterTests.java

Scenario: Customer wants to use a System-Assigned Managed Identity to authenticate Application Insights services (Codeless experience, Profiler/Snapshot, etc)
APPLICATIONINSIGHTS_AUTHENTICATION_STRING = Authorization=AAD
Scenario: Customer wants to use a User-Assigned Managed Identity to authenticate Application Insights services (Codeless experience, Profiler/Snapshot, etc)
APPLICATIONINSIGHTS_AUTHENTICATION_STRING = Authorization=AAD;AppId={ClientId of user-assigned identity}

Add env variable support for aad auth

---

core/src/main/java/com/microsoft/applicationinsights/internal/quickpulse/DefaultQuickPulseDataFetcher.java
core/src/main/java/com/microsoft/applicationinsights/internal/quickpulse/DefaultQuickPulsePingSender.java

Regression in 3.1.1, live metrics role names show up both quoted and unquoted (should only show up unquoted).
https://portal.microsofticm.com/imp/v3/incidents/details/246058224/home

Fix live metrics roles

---

agent/agent-tooling/src/main/java/com/microsoft/applicationinsights/agent/internal/localstorage/LocalFileCache.java
agent/agent-tooling/src/main/java/com/microsoft/applicationinsights/agent/internal/localstorage/LocalFileLoader.java
agent/agent-tooling/src/main/java/com/microsoft/applicationinsights/agent/internal/localstorage/LocalFileWriter.java
agent/agent-tooling/src/main/java/com/microsoft/applicationinsights/agent/internal/localstorage/PersistenceHelper.java
agent/agent-tooling/src/main/java/com/microsoft/applicationinsights/agent/internal/statsbeat/AttachStatsbeat.java
agent/agent-tooling/src/main/java/com/microsoft/applicationinsights/agent/internal/statsbeat/AzureMetadataService.java
agent/agent-tooling/src/main/java/com/microsoft/applicationinsights/agent/internal/statsbeat/FeatureStatsbeat.java
agent/agent-tooling/src/main/java/com/microsoft/applicationinsights/agent/internal/statsbeat/NetworkStatsbeat.java
agent/agent-tooling/src/main/java/com/microsoft/applicationinsights/agent/internal/telemetry/EndpointProvider.java
agent/agent-tooling/src/main/java/com/microsoft/applicationinsights/agent/internal/telemetry/TelemetryClient.java
agent/agent-tooling/src/test/java/com/microsoft/applicationinsights/agent/internal/localstorage/IntegrationTests.java
agent/agent-tooling/src/test/java/com/microsoft/applicationinsights/agent/internal/localstorage/LocalFileLoaderTests.java
agent/agent-tooling/src/test/java/com/microsoft/applicationinsights/agent/internal/localstorage/LocalFileWriterTests.java
agent/agent-tooling/src/test/java/com/microsoft/applicationinsights/agent/internal/telemetry/ConnectionStringParsingTests.java

- send statsbeat in a different batch because its endpoint is not the same as the customer iKey.
- persist statsbeat on disk under "statsbeat" subfolder
- persist regular telemetries on disk under "telemetries" subfolder
- address other todo(s).

Fix some todo

---

agent/agent-tooling/src/main/java/com/microsoft/applicationinsights/agent/internal/exporter/Exporter.java
test/smoke/testApps/TraceJavaUtilLoggingUsingAgent/src/smokeTest/java/com/microsoft/applicationinsights/smoketest/TraceJavaUtilLoggingTest.java
test/smoke/testApps/TraceLog4j1_2/src/smokeTest/java/com/microsoft/applicationinsights/smoketest/TraceLog4j12Test.java
test/smoke/testApps/TraceLog4j1_2UsingAgent/src/smokeTest/java/com/microsoft/applicationinsights/smoketest/TraceLog4j12Test.java
test/smoke/testApps/TraceLog4j2/src/smokeTest/java/com/microsoft/applicationinsights/smoketest/TraceLog4j2Test.java
test/smoke/testApps/TraceLog4j2UsingAgent/src/smokeTest/java/com/microsoft/applicationinsights/smoketest/TraceLog4j2Test.java
test/smoke/testApps/TraceLogBack/src/smokeTest/java/com/microsoft/applicationinsights/smoketest/TraceLogBackTest.java
test/smoke/testApps/TraceLogBackUsingAgent/src/smokeTest/java/com/microsoft/applicationinsights/smoketest/TraceLogBackTest.java

Add thread name to log capture

---

agent/agent-tooling/src/main/java/com/microsoft/applicationinsights/agent/internal/configuration/ConfigurationBuilder.java
agent/agent-tooling/src/main/java/com/microsoft/applicationinsights/agent/internal/configuration/ConfigurationLogger.java
agent/agent-tooling/src/test/java/com/microsoft/applicationinsights/agent/internal/configuration/ConfigurationTest.java

Resolves #1684
Supports system properties for the main "coordinates":
* applicationinsights.connection.string
* applicationinsights.role.name
* applicationinsights.role.instance
Also logs warning if using undocumented `APPLICATIONINSIGHTS_JMX_METRICS` (planning to remove support for this undocumented env var in the future).
Also renames `APPLICATIONINSIGHTS_PROFILER_ENABLED` to `APPLICATIONINSIGHTS_PREVIEW_PROFILER_ENABLED` (cc: @johnoliver).

Support system properties for the main "coordinates"

---

agent/agent-profiler/agent-service-profiler/src/main/java/com/microsoft/applicationinsights/serviceprofilerapi/client/ProfilerFrontendClientV2.java
agent/agent-tooling/src/main/java/com/microsoft/applicationinsights/agent/internal/httpclient/LazyHttpClient.java
agent/agent-tooling/src/main/java/com/microsoft/applicationinsights/agent/internal/quickpulse/QuickPulseDataSender.java
agent/agent-tooling/src/main/java/com/microsoft/applicationinsights/agent/internal/quickpulse/QuickPulsePingSender.java
agent/agent-tooling/src/main/java/com/microsoft/applicationinsights/agent/internal/telemetry/TelemetryChannel.java

Fixes an issue that started in 3.2.0-BETA.1 after swapping out ingestion http client with Azure SDK / reactor netty.
```
ERROR io.netty.util.ResourceLeakDetector - LEAK: ByteBuf.release() was not called before it's garbage-collected. See https://netty.io/wiki/reference-counted-objects.html for more information.
```

Fix netty ByteBuf leak

---

agent/agent-tooling/src/main/java/com/microsoft/applicationinsights/agent/internal/init/LoggingConfigurator.java
agent/agent-tooling/src/main/java/com/microsoft/applicationinsights/agent/internal/init/MainEntryPoint.java

Three changes:
* Adds PID to startup message. This will help support customers who need to take a thread/heap dump for any reason.
* Clearer timezone identifier on logs (`-07:00` instead of `-07`)
* `applicationinsights.testing.etw.disabled` just for use during testing (I've needed this twice now, so committing it now)

Misc logging improvements

---

agent/agent-tooling/src/main/java/com/microsoft/applicationinsights/agent/internal/common/Strings.java
agent/agent-tooling/src/main/java/com/microsoft/applicationinsights/agent/internal/configuration/ConfigurationBuilder.java
agent/agent-tooling/src/main/java/com/microsoft/applicationinsights/agent/internal/exporter/Exceptions.java
agent/agent-tooling/src/test/java/com/microsoft/applicationinsights/agent/internal/common/StringsTest.java
agent/agent-tooling/src/test/java/com/microsoft/applicationinsights/agent/internal/configuration/ConfigurationBuilderTest.java
agent/agent-tooling/src/test/java/com/microsoft/applicationinsights/agent/internal/exporter/ExceptionsTest.java
buildSrc/src/main/kotlin/ai.java-conventions.gradle.kts
buildSrc/src/main/kotlin/ai.smoke-test.gradle.kts

Resolves:
```
ERROR c.m.a.a.internal.exporter.Exporter - begin 64, end 63, length 4992
java.lang.StringIndexOutOfBoundsException: begin 64, end 63, length 4992
at java.base/java.lang.String.checkBoundsBeginEnd(String.java:3319)
at java.base/java.lang.String.substring(String.java:1874)
at com.microsoft.applicationinsights.agent.internal.exporter.Exceptions.minimalParse(Exceptions.java:48)
at com.microsoft.applicationinsights.agent.internal.exporter.Exporter.trackTraceAsException(Exporter.java:373)
at com.microsoft.applicationinsights.agent.internal.exporter.Exporter.exportLogSpan(Exporter.java:325)
at com.microsoft.applicationinsights.agent.internal.exporter.Exporter.export(Exporter.java:174)
at com.microsoft.applicationinsights.agent.internal.exporter.Exporter.export(Exporter.java:155)
at …
```

Fix StringIndexOutOfBoundsException

---

agent/agent-tooling/src/main/java/com/microsoft/applicationinsights/agent/internal/configuration/Configuration.java
agent/agent-tooling/src/main/java/com/microsoft/applicationinsights/agent/internal/init/TelemetryClientInitializer.java
agent/agent-tooling/src/main/java/com/microsoft/applicationinsights/agent/internal/perfcounter/AvailableJmxMetricLogger.java
agent/agent-tooling/src/main/java/com/microsoft/applicationinsights/agent/internal/perfcounter/PerformanceCounterContainer.java
agent/agent-tooling/src/test/java/com/microsoft/applicationinsights/agent/internal/perfcounter/AvailableJmxMetricLoggerTest.java

Debug logging now dumps all available jmx metrics (objectName + attributes, but not values).
This will help provide easier answer to common question [How do I know what metrics are available to configure?](https://docs.microsoft.com/en-us/azure/azure-monitor/app/java-jmx-metrics-configuration#how-do-i-know-what-metrics-are-available-to-configure), especially on linux servers with no UI to run Java Mission Control.

Log all available jmx metrics at debug level

---

agent/agent-tooling/src/main/java/com/microsoft/applicationinsights/agent/internal/quickpulse/QuickPulseDataCollector.java

Currently live metrics is under-reporting the request/dependency/exception counts because we are not factoring sampling into consideration.

Fix live metrics sampled counts

---

agent/agent-tooling/src/main/java/com/microsoft/applicationinsights/agent/internal/exporter/Exporter.java

Based on @lmolkova's https://github.com/Azure/azure-sdk-for-java/pull/21668#discussion_r685572619 and https://github.com/Azure/azure-sdk-for-java/pull/21668#pullrequestreview-725874372

Fix service bus mapping

---

agent/agent-tooling/src/main/java/com/microsoft/applicationinsights/agent/internal/heartbeat/DefaultHeartBeatPropertyProvider.java
agent/agent-tooling/src/main/java/com/microsoft/applicationinsights/agent/internal/heartbeat/WebAppsHeartbeatProvider.java
test/smoke/testApps/HeartBeat/src/smokeTest/java/com/microsoft/applicationinsights/smoketest/HeartBeatTest.java

Add App Map to App service/function view support

Add App Map to App service/function view support

---

agent/agent-tooling/src/main/java/com/microsoft/applicationinsights/agent/internal/statsbeat/FeatureStatsbeat.java
test/smoke/testApps/Statsbeat/src/smokeTest/java/com/microsoft/applicationinsights/smoketest/StatsbeatSmokeTest.java

sent type 0 (feature) and 1(instrumentation)
use the same "Feature" metric name for instrumentation. 
This is easier for querying data on the Kusto end and consistent with nodejs SDK.

Be consistent with other SDK

---

agent/agent-tooling/src/main/java/com/microsoft/applicationinsights/agent/internal/exporter/Exporter.java
agent/agent-tooling/src/main/java/com/microsoft/applicationinsights/agent/internal/exporter/UrlParser.java
agent/agent-tooling/src/test/java/com/microsoft/applicationinsights/agent/internal/exporter/UrlParserTest.java
test/smoke/testApps/HttpClients/src/smokeTest/java/com/microsoft/applicationinsights/smoketestapp/HttpClientSmokeTest.java
test/smoke/testApps/JMS/src/smokeTest/java/com/microsoft/applicationinsights/smoketest/JmsControllerSpansDisabledTest.java
test/smoke/testApps/JMS/src/smokeTest/java/com/microsoft/applicationinsights/smoketest/JmsDisabledTest.java
test/smoke/testApps/JMS/src/smokeTest/java/com/microsoft/applicationinsights/smoketest/JmsTest.java
test/smoke/testApps/Kafka/src/smokeTest/java/com/microsoft/applicationinsights/smoketest/KafkaControllerSpansDisabledTest.java
test/smoke/testApps/Kafka/src/smokeTest/java/com/microsoft/applicationinsights/smoketest/KafkaDisabledTest.java
test/smoke/testApps/Kafka/src/smokeTest/java/com/microsoft/applicationinsights/smoketest/KafkaTest.java
test/smoke/testApps/NonDaemonThreads/src/smokeTest/java/com/microsoft/applicationinsights/smoketest/SpringBootAutoTest.java
test/smoke/testApps/SpringBootTest/src/smokeTest/java/com/microsoft/applicationinsights/smoketest/SpringBootControllerSpansDisabledTest.java
test/smoke/testApps/SpringBootTest/src/smokeTest/java/com/microsoft/applicationinsights/smoketest/SpringBootTest.java

~Built on top of #1890~ EDIT: no longer as #1890 has been merged to `main`

Update http dependency name

---

agent/agent-tooling/src/main/java/com/microsoft/applicationinsights/agent/internal/configuration/Configuration.java
agent/agent-tooling/src/main/java/com/microsoft/applicationinsights/agent/internal/init/ConfigOverride.java
agent/agent-tooling/src/main/java/com/microsoft/applicationinsights/agent/internal/statsbeat/Feature.java
agent/agent-tooling/src/main/java/com/microsoft/applicationinsights/agent/internal/statsbeat/FeatureStatsbeat.java
agent/agent-tooling/src/main/java/com/microsoft/applicationinsights/agent/internal/statsbeat/Instrumentations.java
agent/instrumentation/build.gradle.kts
agent/instrumentation/gradle.lockfile

Add Quartz and Apache Camel preview instrumentations

---

agent/agent-bootstrap/src/main/java/com/microsoft/applicationinsights/agent/bootstrap/diagnostics/log/ApplicationInsightsJsonLayout.java
agent/agent-bootstrap/src/test/java/com/microsoft/applicationinsights/agent/bootstrap/diagnostics/log/ApplicationInsightsJsonLayoutTests.java

App Service linux diagnostic log is missing language column because we didn't provide that. 
it's hard to distinguish logs from node.js and dotnetcore since they all have language column populated.

Fix Linux diagnostic log missing language column

---

agent/agent-tooling/src/main/java/com/microsoft/applicationinsights/agent/internal/legacysdk/BytecodeUtilImpl.java

Metrics are not correlated with other telemetry, and have different mechanism (interval) to control cost.
Resolves #1902

Do not apply sampling to metrics

---

agent/agent-bootstrap/gradle.lockfile
agent/agent-tooling/gradle.lockfile
agent/agent-tooling/src/main/java/com/microsoft/applicationinsights/agent/internal/init/LoggingConfigurator.java
agent/agent-tooling/src/main/java/com/microsoft/applicationinsights/agent/internal/logbackpatch/FileNamePattern.java
agent/agent-tooling/src/main/java/com/microsoft/applicationinsights/agent/internal/logbackpatch/FixedWindowRollingPolicy.java
agent/agent-tooling/src/test/java/com/microsoft/applicationinsights/agent/internal/logbackpatch/FileNamePatternTest.java
agent/agent-tooling/src/test/java/com/microsoft/applicationinsights/agent/internal/logbackpatch/FixedWindowRollingPolicyTest.java
agent/agent/gradle.lockfile
dependencyManagement/build.gradle.kts

Currently the agent fails to start when it's located in a weird folder name like `test%20-test`.

Handle weird folder names

---

agent/agent-tooling/src/main/java/com/microsoft/applicationinsights/agent/internal/httpclient/LazyHttpClient.java

attaching snapshot for testing: [applicationinsights-agent-3.2.3-BETA-SNAPSHOT.jar.zip](https://github.com/microsoft/ApplicationInsights-Java/files/7463135/applicationinsights-agent-3.2.3-BETA-SNAPSHOT.jar.zip)

Reduce netty pool size

---

agent/agent-tooling/src/main/java/com/microsoft/applicationinsights/agent/internal/configuration/Configuration.java
agent/agent-tooling/src/main/java/com/microsoft/applicationinsights/agent/internal/init/ConfigOverride.java
agent/agent-tooling/src/main/java/com/microsoft/applicationinsights/agent/internal/statsbeat/Feature.java
agent/agent-tooling/src/main/java/com/microsoft/applicationinsights/agent/internal/statsbeat/FeatureStatsbeat.java
agent/agent-tooling/src/main/java/com/microsoft/applicationinsights/agent/internal/statsbeat/Instrumentations.java
agent/instrumentation/build.gradle.kts
agent/instrumentation/gradle.lockfile

Add play framework support as preview instrumentation, as OTEL already has this instrumentation.

Add play framework preview instrumentation

---

instrumentation/micrometer-1.0/javaagent/src/main/java/io/opentelemetry/javaagent/instrumentation/micrometer/AzureMonitorMeterRegistry.java

Fixes some micrometer metrics showing up with count 1 in customMetrics table

Otel fork: fix some micrometer metrics showing up with count 1 in customMetrics table

---

logging/log4j2/build.gradle
logging/log4j2/gradle/dependency-locks/compileClasspath.lockfile
logging/log4j2/gradle/dependency-locks/runtimeClasspath.lockfile
test/smoke/testApps/Jdbc/build.gradle
test/smoke/testApps/Jdbc/src/main/java/com/microsoft/applicationinsights/smoketestapp/JdbcTestServlet.java

The 2.x SDK log4j2 appender is designed for users who are already using log4j2. It should not pull in log4j2 on its own. Users should already be bringing their own version of log4j2 (and should be upgrading that version or applying the mitigation steps from [CVE-2021-44228](https://msrc-blog.microsoft.com/2021/12/11/microsofts-response-to-cve-2021-44228-apache-log4j2/)). The PR ensures that users *have* to bring their own version of log4j2.

Update 2.x SDK log4j2 appender to not pull in log4j2 on its own

---

test/smoke/testApps/TraceLog4j2/build.gradle.kts
test/smoke/testApps/TraceLog4j2UsingAgent/build.gradle.kts

Updating Log4j version to 2.17.0 because of CVE-2021-45105 vulnerability.
https://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2021-45105

Update Log4j to 2.17.0 to address CVE-2021-45105

---

test/smoke/testApps/TraceLog4j2/build.gradle.kts
test/smoke/testApps/TraceLog4j2UsingAgent/build.gradle.kts

Updating Log4j version to 2.17.1 because of CVE-2021-44832 vulnerability.
https://nvd.nist.gov/vuln/detail/CVE-2021-44832

Update Log4j to 2.17.1 to address CVE-2021-44832

---

agent/agent-tooling/src/main/java/com/microsoft/applicationinsights/agent/internal/configuration/Configuration.java
agent/agent-tooling/src/main/java/com/microsoft/applicationinsights/agent/internal/init/AiComponentInstaller.java
agent/agent-tooling/src/main/java/com/microsoft/applicationinsights/agent/internal/telemetry/BatchSpanProcessor.java
agent/agent-tooling/src/main/java/com/microsoft/applicationinsights/agent/internal/telemetry/BatchSpanProcessorBuilder.java
agent/agent-tooling/src/main/java/com/microsoft/applicationinsights/agent/internal/telemetry/TelemetryClient.java
gradle.properties

Creates a separate metrics channel batcher, since metrics are bursty (e.g. reported once a minute) and small so good to have a larger queue size for them.

Separate queue for metrics to avoid dropping telemetry

---

agent/agent-tooling/src/main/java/com/microsoft/applicationinsights/agent/internal/exporter/Exporter.java
agent/agent-tooling/src/main/java/com/microsoft/applicationinsights/agent/internal/exporter/UrlParser.java
agent/agent-tooling/src/test/java/com/microsoft/applicationinsights/agent/internal/exporter/UrlParserPathTest.java
agent/agent-tooling/src/test/java/com/microsoft/applicationinsights/agent/internal/exporter/UrlParserTargetTest.java

Fixes this error
```
WARN c.m.a.a.internal.exporter.Exporter - Parsing http.url: Illegal character in query at index 167: REDACTED
at java.net.URI$Parser.fail(URI.java:2845)
at java.net.URI$Parser.checkChars(URI.java:3018)
at java.net.URI$Parser.parseHierarchical(URI.java:3108)
at java.net.URI$Parser.parse(URI.java:3050)
at java.net.URI.<init>(URI.java:588)
at com.microsoft.applicationinsights.agent.internal.exporter.Exporter.getTargetForHttpClientSpan(Exporter.java:546)
at com.microsoft.applicationinsights.agent.internal.exporter.Exporter.applyHttpClientSpan(Exporter.java:479)
at com.microsoft.applicationinsights.agent.internal.exporter.Exporter.applySemanticConventions(Exporter.java:324)
at com.microsoft.applicationinsights.agent.internal.exporter.Exporter.exportRemoteDependency(Exporter …
```

Fix URI parse error

---

agent/agent-tooling/src/main/java/com/microsoft/applicationinsights/agent/internal/localstorage/LocalFileLoader.java
agent/agent-tooling/src/main/java/com/microsoft/applicationinsights/agent/internal/localstorage/LocalFileSender.java
agent/agent-tooling/src/main/java/com/microsoft/applicationinsights/agent/internal/telemetry/TelemetryChannel.java
agent/agent-tooling/src/test/java/com/microsoft/applicationinsights/agent/internal/localstorage/IntegrationTests.java
agent/agent-tooling/src/test/java/com/microsoft/applicationinsights/agent/internal/localstorage/LocalFileLoaderTests.java

Related to #2064, which we never noticed since we didn't log it.
Now the error in #2064 would be logged as:
```
2022-01-21 15:30:10.108-08:00 WARN  c.m.a.a.i.telemetry.TelemetryChannel - Sending telemetry to the ingestion service (telemetry will be stored to disk on failure and retried later): 109: Field 'message' on type 'ExceptionDetails' is required but missing or empty. Expected: string, Actual: undefined (future warnings will be aggregated and logged once every 5 minutes)
```

Log ingestion error on 206 response

---

agent/agent-tooling/src/main/java/com/microsoft/applicationinsights/agent/internal/configuration/Configuration.java
agent/agent-tooling/src/main/java/com/microsoft/applicationinsights/agent/internal/init/ConfigOverride.java
agent/agent-tooling/src/main/java/com/microsoft/applicationinsights/agent/internal/statsbeat/Feature.java
agent/agent-tooling/src/main/java/com/microsoft/applicationinsights/agent/internal/statsbeat/FeatureStatsbeat.java

initially added in 3.2.5-BETA, ok to switch it to preview prior to 3.2.5 GA. will make it on-by-default in the future after getting positive feedback for the preview instrumentation
linking to original request: #1651

Make vertx opt-in preview instrumentation for now

---

agent/agent-tooling/src/main/java/com/microsoft/applicationinsights/agent/internal/exporter/Exceptions.java
agent/agent-tooling/src/main/java/com/microsoft/applicationinsights/agent/internal/exporter/Exporter.java
agent/agent-tooling/src/test/java/com/microsoft/applicationinsights/agent/internal/exporter/ExceptionsTest.java

Fixes issue where breeze rejects exception telemetry due to empty message:
```
{"itemsReceived":2,"itemsAccepted":1,"errors":[{"index":1,"statusCode":400,"message":"109: Field 'message' on type 'ExceptionDetails' is required but missing or empty. Expected: string, Actual:  "}]}
```

Fix ingestion error on missing exception message

---

test/smoke/testApps/Jdbc/build.gradle.kts
test/smoke/testApps/Jdbc/src/smokeTest/java/com/microsoft/applicationinsights/smoketestapp/JdbcTest.java

I added more diagnostics recently to debug sporadic jdbc smoke test failures, and found that the sql server container is failing to start sometimes:
```
2022-01-25 21:56:52.81 spid29s     The activated proc '[dbo].[sp_syspolicy_events_reader]' running on queue 'msdb.dbo.syspolicy_event_queue' output the following:  'Transaction (Process ID 29) was deadlocked on lock resources with another process and has been chosen as the deadlock victim. Rerun the transaction.'
2022-01-25 21:56:57.81 spid31s     Error: 1205, Severity: 13, State: 55.
2022-01-25 21:56:57.81 spid31s     Transaction (Process ID 31) was deadlocked on lock resources with another process and has been chosen as the deadlock victim. Rerun the transaction.
2022-01-25 21:56:57.83 spid31s     The default language (LCID 0) failed to …
```

Bump sql server docker image

---

agent/agent/src/main/java/com/microsoft/applicationinsights/agent/StartupProfiler.java

Startup profiling isn't writing out anything to the file because the PrintWriter is constructed in a try-with-resources block and so getting closed before it can be written to.
Also added a max 10 minute limit for startup profiling, so the file doesn't get enormous if someone forgets about it.

Fix startup profiling

---

CHANGELOG.md
gradle.properties

azure doc pr: https://github.com/MicrosoftDocs/azure-docs-pr/pull/187423

3.2.6 GA release

---

agent/agent-tooling/src/main/java/com/microsoft/applicationinsights/agent/internal/configuration/Configuration.java
agent/agent-tooling/src/main/java/com/microsoft/applicationinsights/agent/internal/configuration/ConfigurationBuilder.java
agent/agent-tooling/src/main/java/com/microsoft/applicationinsights/agent/internal/configuration/RpConfiguration.java

Important: this is a potentially breaking change and needs to be highlighted at https://docs.microsoft.com/en-us/azure/azure-monitor/app/java-in-process-agent#download-the-jar-file
Related to [#1883](https://github.com/microsoft/ApplicationInsights-Java/issues/1883#issuecomment-1054106724)

Respect traceflags sampling decision by default

---

agent/agent-tooling/src/main/java/com/azure/monitor/opentelemetry/exporter/implementation/localstorage/LocalFileCache.java
agent/agent-tooling/src/main/java/com/azure/monitor/opentelemetry/exporter/implementation/localstorage/LocalFilePurger.java

I've noticed a couple of times getting breeze errors that telemetry has expired, because files are loaded from disk at startup before purge happens

Don't load expired telemetry

---

CHANGELOG.md
agent/agent-tooling/src/main/java/com/azure/monitor/opentelemetry/exporter/implementation/builders/Exceptions.java
agent/agent-tooling/src/main/java/com/microsoft/applicationinsights/agent/internal/init/OpenTelemetryConfigurer.java
agent/agent-tooling/src/main/java/com/microsoft/applicationinsights/agent/internal/telemetry/BatchItemProcessor.java
agent/agent-tooling/src/main/java/com/microsoft/applicationinsights/agent/internal/telemetry/BatchItemProcessorBuilder.java
agent/agent-tooling/src/main/java/com/microsoft/applicationinsights/agent/internal/telemetry/TelemetryClient.java
agent/agent-tooling/src/test/java/com/azure/monitor/opentelemetry/exporter/implementation/utils/ExceptionsTest.java

Did not merge #2210, as that is handled differently now in `vnext` by not registering a `DiagnosticTelemetryPipelineListener` at all for the statsbeat channel.
Note: merge don't squash this PR

Merge main into vnext

---

agent/agent-tooling/src/main/java/com/microsoft/applicationinsights/agent/internal/init/OpenTelemetryConfigurer.java

Add scheduled delay for batch span processor

---

.github/workflows/ci.yaml

Agent jar is not currently getting attached to CI builds. It looks like I fixed this for PR builds already.

Fix build attachment

---

agent/agent-tooling/src/main/java/com/microsoft/applicationinsights/agent/internal/configuration/Configuration.java

With runtime attachment, `applicationinsights.log` file is now located in user dir because the agent jar is located in a temp folder that is dropped when the JVM shuts down.

With runtime attachment, applicationinsights.log file is now located in user dir

---

agent/agent-tooling/src/main/java/com/microsoft/applicationinsights/agent/internal/init/AiConfigPropertySource.java

this was a regression in 3.3.0-BETA
correct name is here: https://github.com/open-telemetry/opentelemetry-java-instrumentation/blob/4f29770f73c6225b6698be88bbcb9ad5c832fa01/instrumentation/spring/spring-rabbit-1.0/javaagent/src/main/java/io/opentelemetry/javaagent/instrumentation/spring/rabbit/SpringRabbitInstrumentationModule.java#L18

Fix spring-rabbit instrumentation name

---

agent/agent-tooling/src/main/java/com/microsoft/applicationinsights/agent/internal/init/AiConfigPropertySource.java

I realized the default upstream span suppression strategy changed recently and I think we want to preserve the old behavior. Also see https://github.com/open-telemetry/opentelemetry.io/pull/1486

Update span suppression strategy

---

agent/runtime-attach/src/main/java/com/microsoft/applicationinsights/attach/AppInsightAgentFileProvider.java
agent/runtime-attach/src/main/java/com/microsoft/applicationinsights/attach/ApplicationInsights.java

Improve the error message when the runtime attachment fails with a JRE

Improve the error message when the runtime attachment fails with a JRE or a read-only file system

---

.github/workflows/build-daily-no-build-cache.yml
.github/workflows/build-daily.yml
.github/workflows/reusable-open-issue-on-failure.yml

build cached failed while restoring the gradle cache, which is something we see upstream a lot too, and would open issue each time, which I don't think is necessary in this repo

Reduce issue noise

---

agent/azure-monitor-exporter/src/main/java/com/azure/monitor/opentelemetry/exporter/implementation/quickpulse/QuickPulseDataCollector.java
agent/azure-monitor-exporter/src/main/java/com/azure/monitor/opentelemetry/exporter/implementation/quickpulse/QuickPulseDataFetcher.java
agent/azure-monitor-exporter/src/main/java/com/azure/monitor/opentelemetry/exporter/implementation/quickpulse/model/QuickPulseMetrics.java

per comment https://github.com/microsoft/ApplicationInsights-Java/pull/2407#discussion_r926950701

Change weight to be int

---

agent/agent-tooling/src/main/java/com/microsoft/applicationinsights/agent/internal/exporter/AgentLogExporter.java
smoke-tests/apps/Sampling/src/main/java/com/microsoft/applicationinsights/smoketestapp/SimpleSamplingServlet.java
smoke-tests/apps/Sampling/src/smokeTest/java/com/microsoft/applicationinsights/smoketest/SamplingTest.java

Logs stopped getting sampled in 3.3.0, this restores previous (3.0-3.2.x) behavior.

Fix log sampling

---

agent/agent-profiler/agent-service-profiler/src/main/java/com/microsoft/applicationinsights/serviceprofilerapi/upload/ServiceProfilerUploader.java

Currently jfr files are incorrectly temporarily held in /tmp/

Ensure that the jfr file is written to the Application Insights temp dir

---

agent/agent-tooling/src/main/java/com/microsoft/applicationinsights/agent/internal/init/CommandExecutor.java
agent/agent-tooling/src/main/java/com/microsoft/applicationinsights/agent/internal/init/FirstEntryPoint.java
agent/agent-tooling/src/main/java/com/microsoft/applicationinsights/agent/internal/init/JvmCompiler.java
agent/agent-tooling/src/main/java/com/microsoft/applicationinsights/agent/internal/init/StartupDiagnostics.java

Add start-up diagnostics:
* Disable C2 compiler during start-up
* _JVM flags (removed from this PR)_
* Resident-set size
* Native memory tracking

Add start-up diagnostics

---

agent/agent-tooling/src/main/java/com/microsoft/applicationinsights/agent/internal/init/FirstEntryPoint.java

Add the following info to the self-diagnostics:
* Class path
* Input arguments (what is added by the users: JVM options, properties, ...)

Add classpath and input arguments to the self-diagnostics

---

agent/agent-tooling/src/main/java/com/microsoft/applicationinsights/agent/internal/configuration/Configuration.java
agent/agent-tooling/src/main/java/com/microsoft/applicationinsights/agent/internal/configuration/ConfigurationBuilder.java
agent/agent-tooling/src/main/java/com/microsoft/applicationinsights/agent/internal/exporter/AgentLogExporter.java
agent/agent-tooling/src/main/java/com/microsoft/applicationinsights/agent/internal/init/RpConfigurationPolling.java
agent/agent-tooling/src/main/java/com/microsoft/applicationinsights/agent/internal/sampling/AiOverrideSampler.java
agent/agent-tooling/src/main/java/com/microsoft/applicationinsights/agent/internal/sampling/AiSampler.java
agent/agent-tooling/src/main/java/com/microsoft/applicationinsights/agent/internal/sampling/Samplers.java
agent/agent-tooling/src/main/java/com/microsoft/applicationinsights/agent/internal/sampling/SamplingOverrides.java
agent/agent-tooling/src/test/java/com/microsoft/applicationinsights/agent/internal/sampling/SamplingOverridesTest.java
smoke-tests/apps/RateLimitedSampling/src/smokeTest/resources/applicationinsights.json

TODO add ConfigurationBuilder log warning if still using `limitPerSecond` or `includingStandaloneTelemetry`

Update standalone sampling behavior

---

gradle.properties

I think 3.4.1 is warranted for #2531, but will hold on the release for a bit to see if anything else arises.

Bump next version to 3.4.1

---

agent/agent-tooling/src/main/java/com/microsoft/applicationinsights/agent/internal/profiler/triggers/AlertTriggerSpanProcessor.java
agent/agent-tooling/src/main/java/com/microsoft/applicationinsights/agent/internal/sampling/AiOverrideSampler.java
agent/agent-tooling/src/main/java/com/microsoft/applicationinsights/agent/internal/sampling/AiSampler.java
agent/azure-monitor-exporter/src/main/java/com/azure/monitor/opentelemetry/exporter/implementation/RequestChecker.java
agent/azure-monitor-exporter/src/main/java/com/azure/monitor/opentelemetry/exporter/implementation/SpanDataMapper.java

[`SpanDataMapper` class](https://github.com/microsoft/ApplicationInsights-Java/blob/main/agent/azure-monitor-exporter/src/main/java/com/azure/monitor/opentelemetry/exporter/implementation/SpanDataMapper.java) contains almost 1000 lines.
This class may have too many responsibilities.
The check of the request case does not seem to be the responsibility of the `SpanDataMapper` class. So, this PR has extracted several public methods of SpandDataMapper to a `RequestChecker` class.

Extract RequestChecker class

---

agent/runtime-attach/src/main/java/com/microsoft/applicationinsights/attach/ApplicationInsights.java
smoke-tests/apps/SpringBootAttachInMain/src/main/java/com/microsoft/applicationinsights/smoketestapp/SpringBootApp.java

Ability to set the configuration file from the classpath of runtime attachment

---

agent/agent-bootstrap/src/main/java/com/microsoft/applicationinsights/agent/bootstrap/AzureFunctionsCustomDimensions.java
agent/agent-tooling/src/main/java/com/microsoft/applicationinsights/agent/internal/init/AzureFunctionsLogProcessor.java
agent/agent-tooling/src/main/java/com/microsoft/applicationinsights/agent/internal/init/SecondEntryPoint.java
agent/azure-monitor-exporter/src/main/java/com/azure/monitor/opentelemetry/exporter/implementation/AiSemanticAttributes.java
agent/azure-monitor-exporter/src/main/java/com/azure/monitor/opentelemetry/exporter/implementation/LogDataMapper.java
agent/instrumentation/azure-functions/src/main/java/io/opentelemetry/javaagent/instrumentation/azurefunctions/InvocationInstrumentation.java
agent/instrumentation/azure-functions/src/main/java/io/opentelemetry/javaagent/instrumentation/azurefunctions/InvocationRequestExtractAdapter.java

processId doesn't match azure function logs. that's up to function team to fix it if it's an issue.

Fix duplicate azure functions logs

---

smoke-tests/apps/RateLimitedSampling/src/smokeTest/java/com/microsoft/applicationinsights/smoketest/RateLimitedSamplingTest.java

There was a sporadic failure because number of requests captured was exactly 20 (instead of less than 20), I think it's ok to bump the threshold on this test a bit.

Fix sporadic failure

---

agent/agent-tooling/src/main/java/com/microsoft/applicationinsights/agent/internal/configuration/Configuration.java
agent/agent-tooling/src/main/java/com/microsoft/applicationinsights/agent/internal/exporter/AgentLogExporter.java
agent/agent-tooling/src/main/java/com/microsoft/applicationinsights/agent/internal/init/AzureFunctionsInitializer.java
agent/agent-tooling/src/main/java/com/microsoft/applicationinsights/agent/internal/init/SecondEntryPoint.java

Fix OFF logging threshold

---

agent/azure-monitor-exporter/src/main/java/com/azure/monitor/opentelemetry/exporter/implementation/SpanDataMapper.java

I realized I should have kept backwards compatibility in mind when upgrading to otel 1.19, for (manual) instrumentation that may still be using older semantic convention.

Add back compat for http.host attribute

---

dependencyManagement/build.gradle.kts

I did some testing, and it looks like dependabot understands this kind of variable usage, and will update the variable, which should save us several updates (and resulting conflicting merges).

Consolidate dependabot updates

---

agent/agent-tooling/src/main/java/com/microsoft/applicationinsights/agent/internal/init/FirstEntryPoint.java

my thought here is that JAVA_OPT and JAVA_OPTIONS are just conventions that some app servers use to populate the command line args, so those should show up in "Input arguments", while JAVA_TOOL_OPTIONS and _JAVA_OPTIONS are read directly by the JVM, so don't show up in the command line args

Update debug logging

---

agent/agent-tooling/src/main/java/com/microsoft/applicationinsights/agent/internal/init/FirstEntryPoint.java

Add environment variables and system properties to the self-diagnostics

Add environment variables and system properties to the self-diagnostics

---

smoke-tests/framework/build.gradle.kts

`org.eclipse.jetty.aggregate:jetty-all` appears to be discontinued after version 9
will let dependabot take care of trying to update us to the latest

Update Jetty artifact

---

.github/CODEOWNERS

So that his approval can be used to merge without resorting to admin override.

Add ramthi to CODEOWNERS

---

agent/azure-monitor-exporter/src/main/java/com/azure/monitor/opentelemetry/exporter/implementation/SpanDataMapper.java
agent/azure-monitor-exporter/src/main/java/com/azure/monitor/opentelemetry/exporter/implementation/utils/UrlParser.java
agent/azure-monitor-exporter/src/test/java/com/azure/monitor/opentelemetry/exporter/implementation/utils/UrlParserPathTest.java
agent/azure-monitor-exporter/src/test/java/com/azure/monitor/opentelemetry/exporter/implementation/utils/UrlParserTargetTest.java

Fix Azure SDK target mapping

---

.github/workflows/reusable-create-docs-pull-request.yml

the 2.x doc (which is excluded in the PR update) was renamed

Fix doc PR

---

etw/native/build.gradle

Tool: BinSkim: Rule: BA2008 (EnableControlFlowGuard). https://github.com/microsoft/binskim/blob/main/docs/BinSkimRules.md#rule-BA2008EnableControlFlowGuard

Enable etw dll control flow guard for component govenance

---

agent/agent-tooling/src/main/java/com/microsoft/applicationinsights/agent/internal/configuration/Configuration.java
agent/agent-tooling/src/main/java/com/microsoft/applicationinsights/agent/internal/configuration/ConfigurationBuilder.java

Support metircIntervalSeconds backward compatibility 

---

agent/agent-tooling/src/main/java/com/microsoft/applicationinsights/agent/internal/profiler/AlternativeJfrConfigurations.java
agent/agent-tooling/src/test/java/com/microsoft/applicationinsights/agent/internal/profiler/AlternativeJfrConfigurationsTest.java

Currently if enableDiagnostics is set to true, the user must also use the DIAGNOSTIC_PROFILE ProfileType. At the moment enabling diagnostics with a different profile is _probably_ an incorrect configuration as it is unlikely to work. 
This PR:
1. If enableDiagnostics == true && a custom JFR config is provided by the user:
- A warning is logged that this is unlikely to work, however continues to use the custom profile
2. If enableDiagnostics == true && an alternative inbuilt config was selected by the user:
- The configuration is overridden to the DIAGNOSTIC_PROFILE  and a warning is logged that this has happened.
3. If enableDiagnostics == true && the user has not configured any profile setting:
- The configuration is overridden to the DIAGNOSTIC_PROFILE.

When diagnostics are enabled, automatically use DIAGNOSTIC_PROFILE

---

agent/agent-tooling/src/main/java/com/microsoft/applicationinsights/agent/internal/profiler/config/ProfilerConfiguration.java
agent/agent-tooling/src/test/java/com/microsoft/applicationinsights/agent/internal/profiler/config/ProfilerConfigurationTest.java

Fix NPE when pulling profiler configuration

---

.github/workflows/build-common.yml
.github/workflows/codeql-daily.yml
.github/workflows/owasp-dependency-check-daily.yml
buildSrc/src/main/kotlin/ai.java-conventions.gradle.kts
buildSrc/src/main/kotlin/ai.smoke-test.gradle.kts

Doesn't seem to help with #3020, but worth doing anyways. Note: this doesn't affect end-user Java compatibility as the target Java version is still Java 8, it only affects the Java version that is used to run the builds themselves.

Update gradle toolchain to Java 17

---

agent/agent-gc-monitor/gc-monitor-tests/src/test/java/com/microsoft/gcmonitortests/VariousCollectorsTest.java

This test kept failing on our release build pipeline and it prevents us making a new release.
@johnoliver can you help me take a look at it when you can? In the meantime, i would need to disable it temporarily. 
here is the stack trace:

Disable testShenandoah

---

agent/agent-tooling/src/main/java/com/microsoft/applicationinsights/agent/internal/profiler/service/ServiceProfilerClient.java
agent/azure-monitor-exporter/src/main/java/com/azure/monitor/opentelemetry/exporter/implementation/quickpulse/QuickPulsePingSender.java

need to consume the body or close the response, otherwise get netty ByteBuf leak warnings: io.netty.util.ResourceLeakDetector - LEAK: ByteBuf.release() was not called before it's garbage-collected (see https://github.com/Azure/azure-sdk-for-java/issues/10467)
related: #1822 and #2179

Fix netty leak

---

agent/agent-tooling/src/main/java/com/microsoft/applicationinsights/agent/internal/init/SecondEntryPoint.java
agent/agent-tooling/src/main/java/com/microsoft/applicationinsights/agent/internal/init/TimestampingLogRecordProcessor.java
smoke-tests/apps/Log4j2/src/smokeTest/java/com/microsoft/applicationinsights/smoketest/Log4j2Test.java

this is needed temporarily until https://github.com/open-telemetry/opentelemetry-java-instrumentation/pull/8761

Fix log4j timestamp

---

buildscripts/dependency-check-suppressions.xml

Closes #3133
CVE-2023-35116 is not a valid CVE, see comment from library maintainer https://github.com/FasterXML/jackson-databind/issues/3972#issuecomment-1596308216
Also removed some suppressions which are no longer needed.
Tested against my fork: https://github.com/trask/ApplicationInsights-Java/actions/runs/5317965027/jobs/9629003133

Suppress invalid CVE

---

agent/agent/build.gradle.kts
settings.gradle.kts

This prevented me from importing the project into Intellij on my new dev box (not sure why, something to do with folder name matching case sensitive)

Fix Intellij import

---

agent/agent-tooling/src/main/java/com/microsoft/applicationinsights/agent/internal/init/StatsbeatSpanExporter.java

@heyams @trask 
I'm sorry I gave you the wrong prefix for Azure SDK instrumentation scope name. We don't include group id and use artifact id as is. So, it should be not "com.azure:", but "azure-".
This should fix it.

Change azure instrumentation scope name prefix for statsbeats

---

.github/workflows/build-common.yml
.github/workflows/codeql-daily.yml
.github/workflows/owasp-dependency-check-daily.yml
.github/workflows/pull-request-helper.yml

The version pin was needed previously to remove a (false-positive) github security warning, but is no longer needed now that the warning has cleared

Remove gradle-build-action minor version pin

---

agent/agent-bootstrap/src/main/java/com/microsoft/applicationinsights/agent/bootstrap/diagnostics/DiagnosticsHelper.java
agent/agent-tooling/src/main/java/com/microsoft/applicationinsights/agent/internal/configuration/ConfigurationBuilder.java
agent/agent-tooling/src/test/java/com/microsoft/applicationinsights/agent/internal/configuration/ConfigurationTest.java

Restrict connectionString to app service only

---

agent/agent-tooling/src/main/java/com/microsoft/applicationinsights/agent/internal/configuration/ConfigurationBuilder.java

Fix applicationinsights.json config is not loaded in manual rp attach scenario

---

agent/agent-tooling/src/main/java/com/microsoft/applicationinsights/agent/internal/diagnostics/DiagnosticsHelper.java

AKS_ARM_NAMESPACE_ID serves two purposes:
- act as an AKS attach rate numerator
- distinguish AKS from other Kubernetes service
We don't want to collect any Statsbeat telemetry for other Kubernetes service.

Add AKS unique env var

---

agent/agent-bootstrap/src/main/java/com/microsoft/applicationinsights/agent/bootstrap/AzureFunctionsCustomDimensions.java
agent/agent-tooling/src/main/java/com/microsoft/applicationinsights/agent/internal/init/AzureFunctionsLogProcessor.java
agent/agent-tooling/src/main/java/com/microsoft/applicationinsights/agent/internal/init/AzureMonitorLogProcessor.java
agent/agent-tooling/src/main/java/com/microsoft/applicationinsights/agent/internal/init/AzureMonitorSpanProcessor.java
agent/instrumentation/azure-functions/src/main/java/io/opentelemetry/javaagent/instrumentation/azurefunctions/InvocationInstrumentation.java

Fix #3066
OperationName will set it directly to _**operation_name**_ column.
no need to update it in LogDataMapper::setFunctionExtraTraceAttributes, i.e. it's not available in _**customDimensions**_ column.

Send operation name for function

---

agent/agent-tooling/src/main/java/com/microsoft/applicationinsights/agent/internal/configuration/ConfigurationBuilder.java

The following error messages were displayed for cases not related to a misconfiguration of a connection string from a file:
`Error loading connection string from a file`
```
Please use this format instead:
{ "connectionString": "${file:connection-string-file.txt}" }
```
For example `totoInstrumentationKey` for a connection string creates these error messages.
It can be misleading for the users.
Related to #3707

Fix misleading connection string message

---

agent/agent-tooling/build.gradle.kts
agent/agent/build.gradle.kts
licenses/more-licenses.md

Fix #3755
new OWASP run https://github.com/microsoft/ApplicationInsights-Java/actions/runs/9862118673
We have the latest azure-identity, but we also have an earlier version because of this hack using `resolveStrategy`. We didn't clean up after a newer version became available.

Fix CVE-2024-35255

---

agent/agent/src/main/java/com/microsoft/applicationinsights/agent/StartupProfiler.java

default path:  C:\Users\<username>\AppData\Local\Temp\applicationinsights
now, customer can configure it to anywhere they want via APPLICATIONINSIGHTS_STARTUP_PROFILTER_FILE_PATH.
todo: update wiki when this is released https://github.com/microsoft/ApplicationInsights-Java/wiki/Thread-dump

Make thread dump file configurable through env var

---

agent/runtime-attach/build.gradle.kts
dependencyManagement/build.gradle.kts

Once this is merged, hopefully dependabot will auto-update runtime-attach to 1.37.0-alpha

Fix auto-updating of runtime-attach dependency

---

agent/runtime-attach/build.gradle.kts

Disable publication of gradle modeule metadata for runtime-attach

---

smoke-tests/apps/SpringBoot/src/smokeTest/java/com/microsoft/applicationinsights/smoketest/SpringBootControllerSpansEnabledTest.java
smoke-tests/apps/SpringBoot/src/smokeTest/java/com/microsoft/applicationinsights/smoketest/SpringBootTest.java
smoke-tests/apps/SpringScheduling/src/main/java/com/microsoft/applicationinsights/smoketestapp/SpringSchedulingApp.java
smoke-tests/apps/SpringScheduling/src/smokeTest/java/com/microsoft/applicationinsights/smoketest/SpringSchedulingTest.java

Improving smoke tests and testing the fix in https://github.com/Azure/azure-sdk-for-java/pull/42241

Improve smoke tests around exceptions

---

agent/runtime-attach/build.gradle.kts
dependencyManagement/build.gradle.kts

Follow-up from https://github.com/microsoft/ApplicationInsights-Java/pull/3900#discussion_r1794255788

Rename gradle property

---

agent/agent-gc-monitor/gc-monitor-tests/src/test/java/com/microsoft/gcmonitortests/VariousCollectorsTest.java
agent/instrumentation/micrometer-1.0/build.gradle.kts
agent/instrumentation/micrometer-1.0/src/test/java/MicrometerTest.java
smoke-tests/apps/JmxMetric/src/smokeTest/java/com/microsoft/applicationinsights/smoketest/JmxMetricTest.java

Hopefully will fix the sporadically failing test on #3936 and #3941.

Fix some sporadically failing tests

---

.github/workflows/codeql-daily.yml

Now needs explicit declared permissions.
Confirmed this PR fixed the issue: https://github.com/microsoft/ApplicationInsights-Java/actions/runs/11767099299

Fix CodeQL failures due to recent org-level permission changes

---

.github/workflows/codeql-daily.yml
.github/workflows/owasp-dependency-check-daily.yml
.github/workflows/reusable-scheduled-job-notification.yml

This workflow is failing due to recent org-level permission changes, now needs explicit declared permissions.
Confirmed this fixes the issue:
* https://github.com/microsoft/ApplicationInsights-Java/actions/runs/11767285777
* https://github.com/microsoft/ApplicationInsights-Java/issues/3953

Fix issue notification workflow permissions

---

.github/workflows/owasp-dependency-check-daily.yml

This should fix the OWASP sporadic failures:
> An NVD API Key was not provided - it is highly recommended to use an NVD API key as the update can take a VERY long time without an API Key

Fix OWASP check

---

agent/agent-for-testing/build.gradle.kts
agent/agent/build.gradle.kts

See https://github.com/microsoft/ApplicationInsights-Java/issues/4026#issuecomment-2607795255

Exclude META-INF/maven from shaded libraries

---

CHANGELOG.md

Modified changelog for next release

Update changelog for 3.7.0 release

---

smoke-tests/apps/AutoPerfCounters/src/smokeTest/java/com/microsoft/applicationinsights/smoketest/AutoPerfCountersTest.java
smoke-tests/apps/gRPC/src/smokeTest/java/com/microsoft/applicationinsights/smoketest/GrpcTest.java
smoke-tests/framework/src/main/java/com/microsoft/applicationinsights/smoketest/DependencyAssert.java
smoke-tests/framework/src/main/java/com/microsoft/applicationinsights/smoketest/MetricAssert.java
smoke-tests/framework/src/main/java/com/microsoft/applicationinsights/smoketest/RequestAssert.java
smoke-tests/framework/src/main/java/com/microsoft/applicationinsights/smoketest/SmokeTestExtension.java
smoke-tests/framework/src/main/java/com/microsoft/applicationinsights/smoketest/TraceAssert.java
smoke-tests/framework/src/main/java/com/microsoft/applicationinsights/smoketest/fakeingestion/MockedAppInsightsIngestionServer.java
smoke-tests/framework/src/main/java/com/microsoft/applicationinsights/smoketest/fakeingestion/MockedAppInsightsIngestionServlet.java
smoke-tests/framework/src/main/java/com/microsoft/applicationinsights/smoketest/schemav2/AvailabilityData.java
smoke-tests/framework/src/main/java/com/microsoft/applicationinsights/smoketest/schemav2/Base.java
smoke-tests/framework/src/main/java/com/microsoft/applicationinsights/smoketest/schemav2/Data.java
smoke-tests/framework/src/main/java/com/microsoft/applicationinsights/smoketest/schemav2/DataPoint.java
smoke-tests/framework/src/main/java/com/microsoft/applicationinsights/smoketest/schemav2/Domain.java
smoke-tests/framework/src/main/java/com/microsoft/applicationinsights/smoketest/schemav2/Envelope.java
smoke-tests/framework/src/main/java/com/microsoft/applicationinsights/smoketest/schemav2/EventData.java
smoke-tests/framework/src/main/java/com/microsoft/applicationinsights/smoketest/schemav2/ExceptionData.java
smoke-tests/framework/src/main/java/com/microsoft/applicationinsights/smoketest/schemav2/ExceptionDetails.java
smoke-tests/framework/src/main/java/com/microsoft/applicationinsights/smoketest/schemav2/MessageData.java
smoke-tests/framework/src/main/java/com/microsoft/applicationinsights/smoketest/schemav2/MetricData.java
smoke-tests/framework/src/main/java/com/microsoft/applicationinsights/smoketest/schemav2/PageViewData.java
smoke-tests/framework/src/main/java/com/microsoft/applicationinsights/smoketest/schemav2/RemoteDependencyData.java
smoke-tests/framework/src/main/java/com/microsoft/applicationinsights/smoketest/schemav2/RequestData.java
smoke-tests/framework/src/main/java/com/microsoft/applicationinsights/smoketest/schemav2/StackFrame.java

Easier to read, also more aligned with upstream OpenTelemetry which uses similar assertj wrappers

Nicer smoke test assertions

---

agent/agent-tooling/src/main/java/com/microsoft/applicationinsights/agent/internal/init/PerformanceCounterInitializer.java
agent/agent-tooling/src/main/java/com/microsoft/applicationinsights/agent/internal/perfcounter/AbstractJmxPerformanceCounter.java

Log as warn invalid JMX metrics

---

smoke-tests/apps/LiveMetrics/build.gradle.kts
smoke-tests/apps/OpenTelemetryApiLogBridge/src/main/java/com/microsoft/applicationinsights/smoketestapp/TestController.java
smoke-tests/apps/OpenTelemetryApiLogBridge/src/smokeTest/java/com/microsoft/applicationinsights/smoketest/OpenTelemetryApiLogBridgeTest.java

This PR adds a smoke test to confirm that custom events emitted via the OTel API are received by the java agent and sent to breeze.

Smoke test for custom events with OTel API

---

agent/agent-profiler/agent-alerting-api/src/main/java/com/microsoft/applicationinsights/alerting/aiconfig/AlertingConfig.java
agent/agent-tooling/src/test/java/com/microsoft/applicationinsights/agent/internal/profiler/config/ProfilerConfigurationTest.java
agent/agent-tooling/src/test/resources/profile-configs/sample-alert-config.json

Add fix for hyphens in enum values

---

smoke-tests/apps/SamplingOverrides/build.gradle.kts
smoke-tests/apps/SamplingOverrides/src/smokeTest/java/com/microsoft/applicationinsights/smoketest/SamplingOverrides4Test.java

Hopefully resolves #4306 by giving more time for all of the telemetry to arrive, and at the same time not waiting any longer than necessary

Hopefully resolve sporadic test failure

---

dependencyManagement/build.gradle.kts

This was making it silently ignore a newer version of azure-monitor-opentelemetry-autoconfigure when we specify one.
Luckily not an active issue since the latest bom has the latest autoconfigure, but could cause issues in the future.
(and does cause issues today when trying to test with 1.3.0-beta.1 snapshots)

Change enforcedPlatform to platform

---

.github/scripts/build-azure-monitor-dependency.sh
.github/workflows/build-common.yml

This makes it easier to work across the two repos (which is still painful).
Tested in #4314

Simplify running against azure-monitor-opentelemetry-autoconfigure snapshots

---

buildSrc/src/main/kotlin/ai.errorprone-conventions.gradle.kts

Most of these are just rearranged to match the upstream file: https://github.com/open-telemetry/opentelemetry-java-instrumentation/blob/main/conventions/src/main/kotlin/otel.errorprone-conventions.gradle.kts
so that it will be easier to keep in sync going forward

Sync ErrorProne configuration with OpenTelemetry Java instrumentation
