microsoft/ApplicationInsights-Java

core/src/main/java/com/microsoft/applicationinsights/internal/perfcounter/JvmPerformanceCountersModule.java
Replace <CODE></CODE> with <PRE>{@CODE}</PRE>
=> fix javadoc code sample

.gitignore, gradle/common-java.gradle
Support for Visual Studio Code based on https://marketplace.visualstudio.com/items?itemName=georgewfraser.vscode-javac
=> Add Visual Studio Code editing support

core/src/main/java/com/microsoft/applicationinsights/TelemetryClient.java, core/src/main/java/com/microsoft/applicationinsights/channel/TelemetryChannel.java, core/src/main/java/com/microsoft/applicationinsights/extensibility/TelemetryInitializer.java, core/src/main/java/com/microsoft/applicationinsights/extensibility/TelemetryModule.java, core/src/main/java/com/microsoft/applicationinsights/extensibility/initializer/SequencePropertyInitializer.java, core/src/main/java/com/microsoft/applicationinsights/extensibility/initializer/docker/DockerContextInitializer.java, core/src/main/java/com/microsoft/applicationinsights/extensibility/initializer/docker/internal/Constants.java, core/src/main/java/com/microsoft/applicationinsights/telemetry/EventTelemetry.java, core/src/main/java/com/microsoft/applicationinsights/telemetry/ExceptionTelemetry.java, core/src/main/java/com/microsoft/applicationinsights/telemetry/JsonTelemetryDataSerializer.java, core/src/main/java/com/microsoft/applicationinsights/telemetry/MetricTelemetry.java, core/src/main/java/com/microsoft/applicationinsights/telemetry/RemoteDependencyTelemetry.java, core/src/main/java/com/microsoft/applicationinsights/telemetry/SessionStateTelemetry.java, core/src/main/java/com/microsoft/applicationinsights/telemetry/TelemetryContext.java, core/src/main/java/com/microsoft/applicationinsights/telemetry/TraceTelemetry.java
I believe I have changed only comments, but PLEASE CHECK THAT THIS BUILDS OK. I don't have a Java dev env on my machine.
=> Doc comment edits

core/src/main/java/com/microsoft/applicationinsights/internal/channel/common/TransmissionNetworkOutput.java
Instead of retrying the failed send immediately in the case of a connection failure, retry again in 5 minutes which is less aggressive.
=> Delaying retry on send when no connection is found

gradle.properties
=> Increasing version number to 1.0.10

ThirdPartyNotices.txt
=> Adding ThirdPartyNotices.txt

ThirdPartyNotices.txt
Updating ThirdPartyNotices.txt according to IP Scan results.
=> Updating Thirdpartynotices according to IP Scan result

core/src/test/java/com/microsoft/applicationinsights/internal/channel/samplingV2/FixedRateSamplingTelemetryProcessorTest.java
This fixes one test for fixed rate sampling PR preventing build fail
=> fixing test for Fixed Rate Sampling

core/src/main/java/com/microsoft/applicationinsights/telemetry/BaseTelemetry.java, core/src/main/java/com/microsoft/applicationinsights/telemetry/EventTelemetry.java, core/src/main/java/com/microsoft/applicationinsights/telemetry/ExceptionTelemetry.java, core/src/main/java/com/microsoft/applicationinsights/telemetry/MetricTelemetry.java, core/src/main/java/com/microsoft/applicationinsights/telemetry/PageViewTelemetry.java, core/src/main/java/com/microsoft/applicationinsights/telemetry/PerformanceCounterTelemetry.java, core/src/main/java/com/microsoft/applicationinsights/telemetry/RemoteDependencyTelemetry.java, core/src/main/java/com/microsoft/applicationinsights/telemetry/RequestTelemetry.java, core/src/main/java/com/microsoft/applicationinsights/telemetry/SessionStateTelemetry.java, core/src/main/java/com/microsoft/applicationinsights/telemetry/TraceTelemetry.java, core/src/test/java/com/microsoft/applicationinsights/internal/schemav2/SessionStateDataTest.java, core/src/test/java/com/microsoft/applicationinsights/telemetry/BaseTelemetryTest.java
Fix #462 telemetry name miss instrumentation key.
=> Fix bug462 telemetry naming miss instrumentation key

CHANGELOG.md, gradle.properties
Bumping the version number to 2.0.0-BETA and updating in changelog also according to #469
=> Update version number to beta

README.md
=> Minor proposal

test/smoke/README.md
This includes sections on adding additional application servers.
=> finished writing README for smoketests

test/smoke/testApps/SimpleTelemetryData/src/main/java/com/microsoft/ajl/simplecalc/SimpleTrackDependencyServlet.java, test/smoke/testApps/SimpleTelemetryData/src/main/java/com/microsoft/ajl/simplecalc/SimpleTrackHttpRequestServlet.java, test/smoke/testApps/SimpleTelemetryData/src/main/java/com/microsoft/ajl/simplecalc/SimpleTrackMetricServlet.java, test/smoke/testApps/SimpleTelemetryData/src/main/webapp/index.jsp, test/smoke/testApps/SimpleTelemetryData/src/smokeTest/java/com/microsoft/applicationinsights/smoketest/SimpleTrackDependencyDataTest.java, test/smoke/testApps/SimpleTelemetryData/src/smokeTest/java/com/microsoft/applicationinsights/smoketest/SimpleTrackHttpRequestDataTest.java, test/smoke/testApps/SimpleTelemetryData/src/smokeTest/java/com/microsoft/applicationinsights/smoketest/SimpleTrackMetricDataTest.java
@littleaj @grlima @dhaval24 
Hi all, I have added track dependency,  httprequest, and metric test case into SimpleTelemetryData.
=> add track Dependency, Http Request, Metric test case

README.md
I've added the roadmap inline into the readme, and made a few other small edits.
=> Add Roadmap to Readme

README.md
This update addresses @grlima's comments on PR https://github.com/Microsoft/ApplicationInsights-Java/pull/560
=> Tweak to Readme

logging/logback/build.gradle
=> upgrade to logback v1.2.3

.gitignore, logging/log4j1_2/appenderSrc/test/java/com/microsoft/applicationinsights/log4j/v1_2/ApplicationInsightsAppenderTests.java, logging/log4j1_2/appenderSrc/test/resources/log4j.xml, logging/log4j2/appenderSrc/test/java/com/microsoft/applicationinsights/log4j/v2/ApplicationInsightsAppenderTests.java, logging/logback/appenderSrc/test/java/com/microsoft/applicationinsights/logback/ApplicationInsightsAppenderTests.java, logging/logging.gradle
Fix #569.
Suppressed logging for HttpClient in QuickPulse code.
=> Fix appender tests

test/smoke/appServers/Tomcat.7/resources/linux/startServer.sh, test/smoke/appServers/Tomcat.7/resources/linux/stopServer.sh, test/smoke/appServers/Tomcat.7/resources/linux/tailLastLog.sh, test/smoke/appServers/Tomcat.7/resources/linux/undeploy.sh, test/smoke/appServers/Tomcat.7/tomcat7.linux.partial.dockerfile
I'm wanting to use these in other tests, but they are in the memory leak fix branch which is blocked right now; so I cherry-picked them into this branch.
=> Revised scripts for tomcat smoke tests

test/smoke/testApps/CoreAndFilter/src/smokeTest/java/com/microsoft/applicationinsights/smoketest/CoreAndFilterTests.java
=> Adding auto failed request with result code

test/smoke/testApps/CoreAndFilter/src/main/java/com/microsoft/ajl/simplecalc/SimpleTestRequestSlowWithResponseTime.java, test/smoke/testApps/CoreAndFilter/src/smokeTest/java/com/microsoft/applicationinsights/smoketest/CoreAndFilterTests.java
=> Adding request slow with response time

CHANGELOG.md, gradle.properties
This PR fixes the missing changelog updates and bumps version number.
=> Update Changelog and version number

core/src/main/java/com/microsoft/applicationinsights/internal/jmx/JmxDataFetcher.java, core/src/main/java/com/microsoft/applicationinsights/internal/perfcounter/ProcessBuiltInPerformanceCountersFactory.java, core/src/main/java/com/microsoft/applicationinsights/internal/perfcounter/ProcessPerformanceCountersModule.java, core/src/main/java/com/microsoft/applicationinsights/internal/perfcounter/UnixTotalMemoryPerformanceCounter.java, core/src/main/java/com/microsoft/applicationinsights/internal/perfcounter/WindowsPerformanceCounterAsPC.java
I think all that would be missing here is the log message. It shouldn't have affected any core functionality.
=> fix incorrect format string and some spacing

test/smoke/testApps/CoreAndFilter/src/main/java/com/microsoft/ajl/simplecalc/SimpleThrowExceptionServlet.java, test/smoke/testApps/CoreAndFilter/src/smokeTest/java/com/microsoft/applicationinsights/smoketest/CoreAndFilterTests.java
=> Adding testAutoExceptionWithFailedRequest case

agent/src/main/java/com/microsoft/applicationinsights/agent/internal/logger/InternalAgentLogger.java, agent/src/test/java/com/microsoft/applicationinsights/agent/internal/logger/InternalAgentLoggerTest.java, core/src/main/java/com/microsoft/applicationinsights/internal/logger/InternalLogger.java, core/src/test/java/com/microsoft/applicationinsights/internal/logger/InternalLoggerTest.java
=> Logging should have millisecond granularity

CHANGELOG.md, gradle.properties
=> updated version for 2.1.0 release. added changelog entries

test/smoke/testApps/TraceLog4j1_2/build.gradle, test/smoke/testApps/TraceLog4j1_2/src/main/java/com/microsoft/ajl/simplecalc/SimpleTestTraceLog4j1_2WithExceptionServlet.java, test/smoke/testApps/TraceLog4j1_2/src/main/webapp/WEB-INF/web.xml, test/smoke/testApps/TraceLog4j1_2/src/smokeTest/java/com/microsoft/applicationinsights/smoketest/TraceLog4j1_2Test.java
=> remove useless code and add trace log4j1.2 with exception test case

settings.gradle, test/smoke/testApps/HeartBeat/build.gradle, test/smoke/testApps/HeartBeat/src/main/resources/ApplicationInsights.xml, test/smoke/testApps/HeartBeat/src/main/webapp/WEB-INF/web.xml, test/smoke/testApps/HeartBeat/src/main/webapp/index.jsp, test/smoke/testApps/HeartBeat/src/smokeTest/java/com/microsoft/applicationinsights/smoketest/HeartBeatTest.java, test/smoke/testApps/HeartBeat/src/smokeTest/resources/appServers.txt
@dhaval24 @littleaj @grlima 
Hi guys, I have completed heartbeat test case. Please review it.
=> Adding HeartBeat test case

test/smoke/testApps/HeartBeat/src/smokeTest/java/com/microsoft/applicationinsights/smoketest/HeartBeatTest.java
This PR adds the additional additional fields to validate in HeartBeat payload.
=> adding field validations

CHANGELOG.md, gradle.properties
update version number and changelog.
=> update version and Changelog

azure-application-insights-spring-boot-starter/README.md
=> fix the artifact name in readme

azure-application-insights-spring-boot-starter/README.md
=> Fix spring boot read me

settings.gradle, test/smoke/testApps/TraceLog4j2/build.gradle, test/smoke/testApps/TraceLog4j2/src/main/java/com/microsoft/ajl/simplecalc/ServletFuncs.java, test/smoke/testApps/TraceLog4j2/src/main/java/com/microsoft/ajl/simplecalc/SimpleTestTraceLog4j2Servlet.java, test/smoke/testApps/TraceLog4j2/src/main/java/com/microsoft/ajl/simplecalc/SimpleTestTraceLog4j2WithExceptionServlet.java, test/smoke/testApps/TraceLog4j2/src/main/resources/ApplicationInsights.xml, test/smoke/testApps/TraceLog4j2/src/main/resources/log4j2.xml, test/smoke/testApps/TraceLog4j2/src/main/webapp/WEB-INF/web.xml, test/smoke/testApps/TraceLog4j2/src/main/webapp/index.jsp, test/smoke/testApps/TraceLog4j2/src/smokeTest/java/com/microsoft/applicationinsights/smoketest/TraceLog4j2Test.java, test/smoke/testApps/TraceLog4j2/src/smokeTest/resources/appServers.txt
@littleaj @dhaval24 @grlima  
Hi guys, I have completed trace log4j2 test case. Please review it.
=> adding trace log4j2 test case

settings.gradle, test/smoke/testApps/TraceLogBack/build.gradle, test/smoke/testApps/TraceLogBack/src/main/java/com/microsoft/ajl/simplecalc/ServletFuncs.java, test/smoke/testApps/TraceLogBack/src/main/java/com/microsoft/ajl/simplecalc/SimpleTestTraceLogBackServlet.java, test/smoke/testApps/TraceLogBack/src/main/java/com/microsoft/ajl/simplecalc/SimpleTestTraceLogBackWithExceptionServlet.java, test/smoke/testApps/TraceLogBack/src/main/resources/ApplicationInsights.xml, test/smoke/testApps/TraceLogBack/src/main/resources/logback.xml, test/smoke/testApps/TraceLogBack/src/main/webapp/WEB-INF/web.xml, test/smoke/testApps/TraceLogBack/src/main/webapp/index.jsp, test/smoke/testApps/TraceLogBack/src/smokeTest/java/com/microsoft/applicationinsights/smoketest/TraceLogBackTest.java, test/smoke/testApps/TraceLogBack/src/smokeTest/resources/appServers.txt
@littleaj  @dhaval24  @grlima 
Hi guys, I have completed trace logback test case. Please review it. Thanks.
=> adding trace logback test case

azure-application-insights-spring-boot-starter/README.md
Add the way to configure JMX counters in Springboot in Readme file.
=> updating readme with jmx configuration

CHANGELOG.md, core/build.gradle
=> Fix guava thirdparty shadow

azure-application-insights-spring-boot-starter/gradle.properties, gradle.properties
=> updating version number

CHANGELOG.md, web/src/main/java/com/microsoft/applicationinsights/web/internal/WebRequestTrackingFilter.java
=> added required attributes and others to @WebFilter

core/src/main/java/com/microsoft/applicationinsights/internal/channel/common/TransmissionFileSystemOutput.java, core/src/test/java/com/microsoft/applicationinsights/internal/channel/common/TransmissionFileSystemOutputTest.java
=> fix channel capacity check to be actually mb, fix associated tests

azure-application-insights-spring-boot-starter/src/main/java/com/microsoft/applicationinsights/boot/ApplicationInsightsModuleConfiguration.java, azure-application-insights-spring-boot-starter/src/main/java/com/microsoft/applicationinsights/boot/ApplicationInsightsTelemetryAutoConfiguration.java, azure-application-insights-spring-boot-starter/src/main/java/com/microsoft/applicationinsights/boot/ApplicationInsightsWebModuleConfiguration.java, azure-application-insights-spring-boot-starter/src/test/java/com/microsoft/applicationinsights/boot/ApplicationInsightsTelemetryAutoConfigurationTests.java
Fix #691 
This fixes the cyclic reference error in SpringBoot Starter.
=> Fix cyclic reference in starter

test/smoke/testApps/CoreAndFilter/src/smokeTest/java/com/microsoft/applicationinsights/smoketest/CoreAndFilterTests.java
@littleaj @dhaval24 @grlima 
Hi guys, I have completed request jsp test case. Please review it. Thanks.
=> Adding request jsp test case

core/src/main/java/com/microsoft/applicationinsights/telemetry/RemoteDependencyTelemetry.java, test/smoke/framework/testCases/src/main/java/com/microsoft/applicationinsights/smoketest/CustomAiTestCases.java, test/smoke/framework/testCases/src/main/java/com/microsoft/applicationinsights/smoketest/FixedAiTestCases.java, test/smoke/testApps/PerfTestApp/build.gradle, test/smoke/testApps/PerfTestApp/src/main/java/com/microsoft/applicationinsights/testapps/perf/servlets/TrackServlet.java, test/smoke/testApps/PerfTestApp/src/main/resources/ApplicationInsights.xml, test/smoke/testApps/PerfTestApp/src/main/webapp/index.jsp
I was using this to test #723, and decided to split this out into its own PR.
FYI, this did need one method (RemoteDependencyTelemetry.getMetrics) which is included in #723.
=> Expanded PerfTestApp 

core/src/main/java/com/microsoft/applicationinsights/internal/channel/common/TransmissionFileSystemOutput.java
<del>Not sure if we want to merge this yet. Let's let the build run and see if this fixes it.</del>
Yup, this was the issue. Let's merge this.
=> Fix possible open streams which could be causing the failing tests.

CHANGELOG.md, web/src/main/java/com/microsoft/applicationinsights/web/internal/ApplicationInsightsServletContextListener.java, web/src/main/java/com/microsoft/applicationinsights/web/internal/WebRequestTrackingFilter.java
<del>Waiting on smoketests before merging.</del>
=> Removed Servlet 3 annotations

.gitignore
Add pom.xml file to be ignored from git tracking.
=> add pom.xml to git ignore

azure-application-insights-spring-boot-starter/build.gradle
This PR is an attempt to fix the starter build script, after the grpc dependency update.
=> Fix starter build script

web/src/main/java/com/microsoft/applicationinsights/web/internal/correlation/tracecontext/Traceparent.java, web/src/main/java/com/microsoft/applicationinsights/web/internal/correlation/tracecontext/Tracestate.java
=> Implement W3C tracestate

web/build.gradle
=> fix pom configuration

ApplicationInsightsInternalLogger/build.gradle, ApplicationInsightsInternalLogger/src/main/java/com/microsoft/applicationinsights/internal/logger/FileLoggerOutput.java, ApplicationInsightsInternalLogger/src/main/java/com/microsoft/applicationinsights/internal/logger/InternalLogger.java, agent/src/main/java/com/microsoft/applicationinsights/agent/internal/config/XmlAgentConfigurationBuilder.java, core/build.gradle, web/src/main/java/com/microsoft/applicationinsights/web/internal/correlation/TraceContextCorrelation.java, web/src/main/java/com/microsoft/applicationinsights/web/internal/correlation/tracecontext/Traceparent.java
Apache-commons has all the utilites we need.
Fix #799 .
=> removed dependency on guava

web/src/main/java/com/microsoft/applicationinsights/web/internal/httputils/AIHttpServletListener.java
Add bare bone structure of AsyncListener
Related #444
=> Add Async Listener Strucutre

test/smoke/framework/utils/src/main/java/com/microsoft/applicationinsights/smoketest/HttpHelper.java
=> reconfigure smoketest httpclient to disable retries

web/src/main/java/com/microsoft/applicationinsights/web/internal/WebRequestTrackingFilter.java
Fixes duplicate Telemetry Item generation, when using Async request.
Caught while writing integration tests.
Design ideas taken from: 
https://github.com/openzipkin/brave/blob/8d44c92a65b346ed9b348dd0c7103057d7455e86/instrumentation/servlet/src/main/java/brave/servlet/TracingFilter.java
Problem that we are trying to solve:  When an async request is created it enters the doFilter() method twice. The first time it hits the filter it comes via as `REQUEST` dispatch and from `ASYNC` dispatch in order. We do not want to instrument the same request twice and henceforth prevent handleStart() and handleEnd() from triggering. 
The proposed solution marks the request as processed with by setting an attribute to request object.
=> prevent duplicate telemetry items creation in async

agent/src/main/java/com/microsoft/applicationinsights/agent/internal/config/XmlAgentConfigurationBuilder.java
https://cwe.mitre.org/data/definitions/611.html
https://github.com/OWASP/CheatSheetSeries/blob/master/cheatsheets/XML_External_Entity_Prevention_Cheat_Sheet.md
=> disable unsafe xml features

test/smoke/testApps/FixedRateSampling/src/smokeTest/java/com/microsoft/applicationinsights/smoketest/FixedRateSamplingTest.java
=> fixed method call after merge

web/build.gradle
=> fix web testCompile dependencies

agent/src/main/java/com/microsoft/applicationinsights/agent/internal/agent/AgentImplementation.java, core/src/main/java/com/microsoft/applicationinsights/internal/channel/common/TransmissionFileSystemOutput.java, core/src/main/java/com/microsoft/applicationinsights/internal/channel/simplehttp/SimpleHttpChannel.java, test/smoke/framework/fakeIngestion/standalone/src/main/java/com/microsoft/applicationinsights/test/fakeingestion/MockedAppInsightsIngestionServer.java, test/smoke/framework/testCore/src/main/java/com/microsoft/applicationinsights/smoketest/AiSmokeTest.java, web/src/main/java/com/microsoft/applicationinsights/web/internal/httputils/AIHttpServletListener.java
Several Closable resources were either left open or incorrectly closed.
=> Fixed closable resources

CHANGELOG.md
This confused us and we assumed everything in here was released, maybe add something to clarify at a glance what is released in the latest version
=> Clarify changelog status

core/src/main/java/com/microsoft/applicationinsights/internal/util/LocalStringsUtils.java
Recreating the random object each time does not guarantee sufficient randomness.
=> Created constant to reuse Random instance

agent/src/main/java/com/microsoft/applicationinsights/agent/internal/agent/sql/PreparedStatementClassVisitor.java
=> fixed possible npe

azure-application-insights-spring-boot-starter/src/main/java/com/microsoft/applicationinsights/autoconfigure/HeartBeatProvider/SpringBootHeartBeatProvider.java, core/src/main/java/com/microsoft/applicationinsights/internal/channel/common/TransmissionFileSystemOutput.java, core/src/main/java/com/microsoft/applicationinsights/internal/heartbeat/DefaultHeartBeatPropertyProvider.java, core/src/main/java/com/microsoft/applicationinsights/internal/heartbeat/MiscUtils.java, core/src/main/java/com/microsoft/applicationinsights/internal/heartbeat/WebAppsHeartbeatProvider.java, core/src/main/java/com/microsoft/applicationinsights/internal/perfcounter/ProcessCpuPerformanceCounter.java, core/src/main/java/com/microsoft/applicationinsights/internal/processor/MetricTelemetryFilter.java, core/src/main/java/com/microsoft/applicationinsights/internal/processor/PageViewTelemetryFilter.java, core/src/main/java/com/microsoft/applicationinsights/internal/processor/RequestTelemetryFilter.java, core/src/main/java/com/microsoft/applicationinsights/internal/processor/SyntheticSourceFilter.java, core/src/main/java/com/microsoft/applicationinsights/internal/processor/TelemetryEventFilter.java, test/smoke/testApps/PerfTestAppSpringBoot/src/main/java/com/microsoft/applicationinsights/testapps/perf/boot/SpringBootPerfTestHelper.java
This conflicts with #847. I'll need to address that before merge.
=> Fix throw/return statments in finally blocks

test/smoke/framework/testCore/src/main/java/com/microsoft/applicationinsights/smoketest/AiSmokeTest.java, test/smoke/framework/testCore/src/main/java/com/microsoft/applicationinsights/smoketest/docker/AiDockerClient.java
=> SmokTest improvements: extra logging; container name trim/strip

core/src/main/java/com/microsoft/applicationinsights/internal/processor/TraceTelemetryFilter.java
=> fixed throw inside finally

CHANGELOG.md, core/src/main/java/com/microsoft/applicationinsights/internal/quickpulse/DefaultQuickPulseDataFetcher.java, core/src/test/java/com/microsoft/applicationinsights/internal/quickpulse/DefaultQuickPulseDataFetcherTests.java
=> Fix SDK Version sent from QuickPulse channel

CHANGELOG.md, core/src/main/java/com/microsoft/applicationinsights/internal/quickpulse/QuickPulseDataCollector.java
=> Add implementation of dependency metric collection for Livemetrics

core/src/main/java/com/microsoft/applicationinsights/extensibility/initializer/SdkVersionContextInitializer.java
=> Nit: clean import

gradle/wrapper/gradle-wrapper.properties
https://docs.gradle.org/current/userguide/gradle_wrapper.html
=> include gradle sources/javadoc for better experience with IDEs

web/src/main/java/com/microsoft/applicationinsights/web/extensibility/modules/WebRequestTrackingTelemetryModule.java, web/src/main/java/com/microsoft/applicationinsights/web/extensibility/modules/WebSessionTrackingTelemetryModule.java, web/src/main/java/com/microsoft/applicationinsights/web/extensibility/modules/WebTelemetryModule.java, web/src/main/java/com/microsoft/applicationinsights/web/extensibility/modules/WebUserTrackingTelemetryModule.java, web/src/main/java/com/microsoft/applicationinsights/web/internal/WebModulesContainer.java, web/src/main/java/com/microsoft/applicationinsights/web/internal/httputils/HttpServerHandler.java, web/src/test/java/com/microsoft/applicationinsights/web/extensibility/modules/WebRequestTrackingTelemetryModuleTests.java, web/src/test/java/com/microsoft/applicationinsights/web/internal/httputils/HttpServerHandlerTest.java
This issue was introduced in 2.4.0-BETA (ea9ee4b735f96e12b4dab888741d9a524580c131).
=> Fix concurrency issue

ApplicationInsightsInternalLogger/src/main/java/com/microsoft/applicationinsights/internal/logger/DefaultLogFileProxy.java, ApplicationInsightsInternalLogger/src/main/java/com/microsoft/applicationinsights/internal/logger/FileLoggerOutput.java, ApplicationInsightsInternalLogger/src/main/java/com/microsoft/applicationinsights/internal/logger/InternalLogger.java, ApplicationInsightsInternalLogger/src/main/java/com/microsoft/applicationinsights/internal/logger/LocalFileSystemUtils.java
=> Internallogger findbugs fixes

core/src/main/java/com/microsoft/applicationinsights/internal/config/JaxbAppInsightsConfigurationBuilder.java, core/src/main/java/com/microsoft/applicationinsights/internal/config/TelemetryConfigurationFactory.java, core/src/test/java/com/microsoft/applicationinsights/internal/config/JaxbAppInsightsConfigurationBuilderTest.java
=> Remove printstacktrace and rework resource handling

web/src/main/java/com/microsoft/applicationinsights/web/extensibility/modules/WebRequestTrackingTelemetryModule.java, web/src/main/java/com/microsoft/applicationinsights/web/extensibility/modules/WebSessionTrackingTelemetryModule.java, web/src/main/java/com/microsoft/applicationinsights/web/extensibility/modules/WebTelemetryModule.java, web/src/main/java/com/microsoft/applicationinsights/web/extensibility/modules/WebUserTrackingTelemetryModule.java, web/src/main/java/com/microsoft/applicationinsights/web/internal/WebModulesContainer.java, web/src/main/java/com/microsoft/applicationinsights/web/internal/WebRequestTrackingFilter.java, web/src/main/java/com/microsoft/applicationinsights/web/internal/httputils/AIHttpServletListener.java, web/src/main/java/com/microsoft/applicationinsights/web/internal/httputils/HttpServerHandler.java, web/src/test/java/com/microsoft/applicationinsights/web/internal/WebRequestTrackingFilterTests.java, web/src/test/java/com/microsoft/applicationinsights/web/internal/httputils/AIHttpServletListenerTest.java, web/src/test/java/com/microsoft/applicationinsights/web/internal/httputils/HttpServerHandlerTest.java
The interface also did not have type parameters in 2.3.1.
=> removed type parameters from public interface.

CHANGELOG.md, azure-application-insights-spring-boot-starter/build.gradle, azure-application-insights-spring-boot-starter/gradle.properties
Removes beta tag from spring boot starter version number.
=> updated version number

CHANGELOG.md, core/src/main/java/com/microsoft/applicationinsights/internal/quickpulse/QuickPulseDataCollector.java, core/src/test/java/com/microsoft/applicationinsights/internal/quickpulse/QuickPulseDataCollectorTests.java, test/smoke/testApps/CoreAndFilter/src/smokeTest/java/com/microsoft/applicationinsights/smoketest/CoreAndFilterTests.java
=> counter variables should not be static

azure-application-insights-spring-boot-starter/build.gradle
=> fix spring boot starter pom

gradle/publishing.gradle
this will simplify the build definition
=> flatten artifacts in staging directory

core/src/main/java/com/microsoft/applicationinsights/internal/quickpulse/DefaultQuickPulseDataFetcher.java, core/src/main/java/com/microsoft/applicationinsights/internal/quickpulse/QuickPulse.java, core/src/main/java/com/microsoft/applicationinsights/internal/quickpulse/QuickPulseDataCollector.java, core/src/test/java/com/microsoft/applicationinsights/internal/quickpulse/DefaultQuickPulseDataFetcherTests.java
=> Fix live metrics to use ikey when it is set programmatically

core/src/windows/cpp/CppPerfCounters.cpp, core/src/windows/cpp/CppPerfCounters.vcxproj
* enable static analysis
* fix constant name
* fix warnings
=> Update cpp project

agent/src/main/java/com/microsoft/applicationinsights/agent/internal/AIAgentXmlLoader.java
E.g. this was not working in AI-Agent.xml:
<Logging enabled="false" />
=> Fix disabling instrumentation not working in agent

agent/build.gradle, agent/src/main/java/com/microsoft/applicationinsights/agent/internal/AIAgentXmlLoader.java, agent/src/main/java/com/microsoft/applicationinsights/agent/internal/MainEntryPoint.java, agent/src/main/java/com/microsoft/applicationinsights/agent/internal/config/AgentConfiguration.java, agent/src/main/java/com/microsoft/applicationinsights/agent/internal/config/ClassInstrumentationData.java, agent/src/main/java/com/microsoft/applicationinsights/agent/internal/config/MethodInfo.java, agent/src/main/java/com/microsoft/applicationinsights/agent/internal/config/builder/BuiltInInstrumentationBuilder.java, agent/src/main/java/com/microsoft/applicationinsights/agent/internal/config/builder/XmlAgentConfigurationBuilder.java, agent/src/main/java/com/microsoft/applicationinsights/agent/internal/config/builder/XmlParserUtils.java, agent/src/main/java/com/microsoft/applicationinsights/agent/internal/model/AsyncQuerySpanImpl.java, agent/src/main/java/com/microsoft/applicationinsights/agent/internal/model/LocalSpanImpl.java, agent/src/main/java/com/microsoft/applicationinsights/agent/internal/model/QuerySpanImpl.java, agent/src/main/java/com/microsoft/applicationinsights/agent/internal/model/ThreadContextImpl.java, agent/src/test/java/com/microsoft/applicationinsights/agent/internal/AIAgentXmlLoaderTest.java, agent/src/test/java/com/microsoft/applicationinsights/agent/internal/model/LocalSpanImplTest.java, test/smoke/appServers/global-resources/CustomInstrumentation_AI-Agent.xml, test/smoke/testApps/SpringBootTest/src/main/java/com/springbootstartertest/controller/CustomInstrumentationController.java, test/smoke/testApps/SpringBootTest/src/main/java/com/springbootstartertest/controller/TargetObject.java, test/smoke/testApps/SpringBootTest/src/smokeTest/java/com/springbootstartertest/smoketest/CustomInstrumentationTest.java
=> Bring back custom agent instrumentation

gradle.properties
So local builds will be 2.5.0-BETA.3-SNAPSHOT
=> Update version number

core/src/main/java/com/microsoft/applicationinsights/internal/quickpulse/QuickPulse.java
To improve startup performance.
Merge after BETA.2.
=> Initialize quickpulse in the background

gradle/common-java.gradle, test/fakeIngestion/servlet/build.gradle, test/fakeIngestion/servlet/src/main/java/com/microsoft/applicationinsights/test/fakeingestion/MockedAppInsightsIngestionServlet.java, test/fakeIngestion/standalone/build.gradle, test/smoke/framework/testCases/build.gradle, test/smoke/framework/testCore/build.gradle, test/smoke/framework/utils/build.gradle, test/smoke/framework/utils/src/main/java/com/microsoft/applicationinsights/smoketest/JsonHelper.java, test/smoke/testApps/AutoPerfCounters/build.gradle, test/smoke/testApps/CachingCalculator/build.gradle, test/smoke/testApps/CoreAndFilter/build.gradle, test/smoke/testApps/FixedRateSampling/build.gradle, test/smoke/testApps/HeartBeat/build.gradle, test/smoke/testApps/SpringBoot1_3Auto/build.gradle, test/smoke/testApps/SpringBootAuto/build.gradle, test/smoke/testApps/SpringBootTest/build.gradle, test/smoke/testApps/TraceLog4j1_2/build.gradle, test/smoke/testApps/TraceLog4j1_2UsingAgent/build.gradle, test/smoke/testApps/TraceLog4j2/build.gradle, test/smoke/testApps/TraceLog4j2UsingAgent/build.gradle, test/smoke/testApps/TraceLogBack/build.gradle, test/smoke/testApps/TraceLogBackUsingAgent/build.gradle, test/smoke/testApps/WebAuto/build.gradle, test/webapps/PerfTestApp/build.gradle, test/webapps/PerfTestAppSpringBoot/build.gradle
The new version of gradle had some issue with the `tasks.withType` method. This seemed to work just fine.
=> Correct the source/target compatibility property usage

core/src/main/java/com/microsoft/applicationinsights/channel/concrete/TelemetryChannelBase.java, core/src/main/java/com/microsoft/applicationinsights/channel/concrete/localforwarder/LocalForwarderTelemetryChannel.java, core/src/main/java/com/microsoft/applicationinsights/extensibility/initializer/docker/internal/DockerContextPoller.java, core/src/main/java/com/microsoft/applicationinsights/internal/channel/common/ActiveTransmissionLoader.java, core/src/main/java/com/microsoft/applicationinsights/internal/channel/common/PartialSuccessHandler.java, core/src/main/java/com/microsoft/applicationinsights/internal/channel/common/SenderThreadLocalBackOffData.java, core/src/main/java/com/microsoft/applicationinsights/internal/channel/common/TransmissionFileSystemOutput.java, core/src/main/java/com/microsoft/applicationinsights/internal/config/ConfigurationFileLocator.java, core/src/main/java/com/microsoft/applicationinsights/internal/jmx/JmxDataFetcher.java, core/src/main/java/com/microsoft/applicationinsights/internal/quickpulse/DefaultQuickPulseCoordinator.java, core/src/main/java/com/microsoft/applicationinsights/internal/quickpulse/QuickPulse.java, test/smoke/framework/testCore/src/main/java/com/microsoft/applicationinsights/smoketest/AiSmokeTest.java
* fix some potential NPEs
* fix String equality check
* fix InterruptedException handling
* remove redundant conditional/logging
=> Static analysis fixes

web/src/main/java/com/microsoft/applicationinsights/web/internal/correlation/TelemetryCorrelationUtils.java, web/src/test/java/com/microsoft/applicationinsights/web/internal/correlation/TelemetryCorrelationUtilsTests.java
=> reworked uuid tostring

CHANGELOG.md
Forgot to update the changelog
=> update changelog with bug fix notes

test/smoke/framework/testCore/src/main/java/com/microsoft/applicationinsights/smoketest/AiSmokeTest.java
I needed this in codeless branch, but seems good for 2.5.0 as well.
=> Fix sporadic test failure

CHANGELOG.md, gradle/common-java.gradle, web/src/main/java/com/microsoft/applicationinsights/web/internal/correlation/TelemetryCorrelationUtils.java, web/src/test/java/com/microsoft/applicationinsights/web/internal/correlation/TelemetryCorrelationUtilsTests.java
=> Merge 2.4.1

azure-application-insights-spring-boot-starter/dependency-check-suppressions.xml
=> update spring boot suppressions

ApplicationInsightsInternalLogger/src/main/java/com/microsoft/applicationinsights/internal/logger/InternalLogger.java, core/src/main/java/com/microsoft/applicationinsights/internal/channel/samplingV2/FixedRateSamplingTelemetryProcessor.java, core/src/main/java/com/microsoft/applicationinsights/internal/heartbeat/HeartbeatDefaultPayload.java, core/src/main/java/com/microsoft/applicationinsights/internal/heartbeat/MiscUtils.java, core/src/main/java/com/microsoft/applicationinsights/telemetry/BaseTelemetry.java
Some style changes, some log message clarification, removed some redundancy
=> Minor reworkings

web/src/test/java/com/microsoft/applicationinsights/web/internal/httputils/HttpServerHandlerTest.java
I think this is why the test is failing
=> Test is being flaky

test/smoke/testApps/SpringBootTest/src/smokeTest/java/com/springbootstartertest/smoketest/SpringbootSmokeTest.java, web/src/main/java/com/microsoft/applicationinsights/web/internal/WebRequestTrackingFilter.java, web/src/main/java/com/microsoft/applicationinsights/web/internal/httputils/AIHttpServletListener.java, web/src/main/java/com/microsoft/applicationinsights/web/internal/httputils/HttpServerHandler.java
=> add asserts to verify response code.

agent/build.gradle, core/build.gradle, test/smoke/testApps/CustomInstrumentation/src/smokeTest/java/com/microsoft/applicationinsights/smoketestapp/CustomInstrumentationTest.java, test/smoke/testApps/HttpClients/src/main/java/com/microsoft/applicationinsights/smoketestapp/HttpClientTestServlet.java, test/smoke/testApps/HttpClients/src/smokeTest/java/com/microsoft/applicationinsights/smoketestapp/HttpClientSmokeTest.java, test/smoke/testApps/Jdbc/src/smokeTest/java/com/microsoft/applicationinsights/smoketestapp/JdbcSmokeTest.java
This was fixed in glowroot instrumentation 0.14.4, see https://github.com/glowroot/instrumentation/commit/ea65a9b3672f3130ab14772fddd11e7ff8862a28
=> Fix illegal state exception

NOTICE, agent/build.gradle, core/build.gradle
=> Update to glowroot instrumentation 0.14.5

CHANGELOG.md, gradle.properties
Don't merge this PR yet, just queueing it up.
=> Prepare 2.5.0-BETA.5 release

CHANGELOG.md, gradle.properties
=> bump version

core/src/main/java/com/microsoft/applicationinsights/web/internal/RequestTelemetryContext.java, core/src/main/java/com/microsoft/applicationinsights/web/internal/correlation/TraceContextCorrelationCore.java
the release build fails with invalid javadoc
=> fix javadoc

core/src/main/java/com/microsoft/applicationinsights/internal/channel/ConfiguredTransmissionOutput.java, core/src/main/java/com/microsoft/applicationinsights/internal/channel/common/TransmissionNetworkOutput.java, test/smoke/framework/testCore/src/main/java/com/microsoft/applicationinsights/smoketest/AiSmokeTest.java, test/smoke/testApps/AutoPerfCounters/src/main/resources/ApplicationInsights.xml, test/smoke/testApps/CachingCalculator/src/main/resources/ApplicationInsights.xml, test/smoke/testApps/CoreAndFilter/src/main/resources/ApplicationInsights.xml, test/smoke/testApps/CustomInstrumentation/src/main/resources/ApplicationInsights.xml, test/smoke/testApps/FixedRateSampling/src/main/resources/ApplicationInsights.xml, test/smoke/testApps/HeartBeat/src/main/resources/ApplicationInsights.xml, test/smoke/testApps/HttpClients/src/main/resources/ApplicationInsights.xml, test/smoke/testApps/Jdbc/src/main/resources/ApplicationInsights.xml, test/smoke/testApps/SpringBoot1_3Auto/src/main/resources/ApplicationInsights.xml, test/smoke/testApps/SpringBootAuto/src/main/resources/ApplicationInsights.xml, test/smoke/testApps/SpringBootTest/src/main/resources/application.properties, test/smoke/testApps/TraceLog4j1_2/src/main/resources/ApplicationInsights.xml, test/smoke/testApps/TraceLog4j1_2UsingAgent/src/main/resources/ApplicationInsights.xml, test/smoke/testApps/TraceLog4j2/src/main/resources/ApplicationInsights.xml, test/smoke/testApps/TraceLog4j2UsingAgent/src/main/resources/ApplicationInsights.xml, test/smoke/testApps/TraceLogBack/src/main/resources/ApplicationInsights.xml, test/smoke/testApps/TraceLogBackUsingAgent/src/main/resources/ApplicationInsights.xml, test/smoke/testApps/WebAuto/src/main/resources/ApplicationInsights.xml, web/src/main/java/com/microsoft/applicationinsights/web/internal/correlation/TraceContextCorrelation.java
<strike>Waiting on #1003 to merge (this is a subbranch)</strike>
Adds connections string to smoketest app configs
=> smoketest updates for connection strings

core/build.gradle
=> fix xmlpull shading

ApplicationInsightsInternalLogger/README.md
I was on a call today and there was some confusion about the purpose of this library.
=> add readme for internal logger lib

azure-application-insights-spring-boot-starter/dependency-check-suppressions.xml, build.gradle
=> update dependency check version and suppressions

CHANGELOG.md, gradle.properties
=> bumped version & updated changelog for 2.5.1-beta.2

agent-codeless/src/main/java/com/microsoft/applicationinsights/agentc/internal/model/AuxThreadContextImpl.java, agent-codeless/src/main/java/com/microsoft/applicationinsights/agentc/internal/model/ThreadContextImpl.java
The same issue was captured and tracked down in glowroot instrumentation test harness, via the play framework instrumentation.
=> Fix async thread tracking

agent-codeless/src/main/java/com/microsoft/applicationinsights/agentc/internal/AgentImpl.java, agent-codeless/src/main/java/com/microsoft/applicationinsights/agentc/internal/model/IncomingSpanImpl.java
It was trying (and silently failing) to parse message as an URL.
=> Improve JMS capture

agent-codeless/src/main/java/com/microsoft/applicationinsights/agentc/internal/AgentImpl.java, agent-codeless/src/main/java/com/microsoft/applicationinsights/agentc/internal/Configuration.java, agent-codeless/src/main/java/com/microsoft/applicationinsights/agentc/internal/diagnostics/AgentExtensionVersionFinder.java, agent-codeless/src/main/java/com/microsoft/applicationinsights/agentc/internal/diagnostics/DiagnosticsHelper.java, agent-codeless/src/main/java/com/microsoft/applicationinsights/agentc/internal/diagnostics/PidFinder.java, agent-codeless/src/main/java/com/microsoft/applicationinsights/agentc/internal/diagnostics/status/StatusFile.java, agent-codeless/src/main/java/com/microsoft/applicationinsights/agentc/internal/model/IncomingSpanImpl.java, agent-codeless/src/main/java/com/microsoft/applicationinsights/agentc/internal/model/LoggerSpans.java, agent-codeless/src/test/java/com/microsoft/applicationinsights/agentc/internal/diagnostics/DiagnosticsTestHelper.java, agent-codeless/src/test/java/com/microsoft/applicationinsights/agentc/internal/diagnostics/status/StatusFileTests.java
Applied Intellij default formatting to `agent-codeless` module, let me know if you want to revise settings.
Moved `@Nullable` from type-annotation to field-annotation (since Java 7).
Moved a couple of end-of-line comments to above-the-line comments because they wrapped when formatting was applied.
=> Just formatting

NOTICE, agent/build.gradle, core/build.gradle
New version brings Java 13 support.
=> Update instrumentation version

agent-codeless/package/Microsoft.ApplicationInsights.JavaCodelessAgent.nuspec
=> fix jar version in nuspec

.lgtm.yml, agent/src/main/java/com/microsoft/applicationinsights/agent/internal/Premain.java, core/src/main/java/com/microsoft/applicationinsights/internal/channel/common/TransmissionFileSystemOutput.java
Add config file and suppress false positives
=> lgtm config

test/smoke/testApps/CachingCalculator/src/smokeTest/java/com/microsoft/applicationinsights/smoketest/SampleTestWithDependencyContainer.java, test/smoke/testApps/CoreAndFilter/src/smokeTest/java/com/microsoft/applicationinsights/smoketest/CoreAndFilterTests.java, test/smoke/testApps/CustomInstrumentation/src/smokeTest/java/com/microsoft/applicationinsights/smoketestapp/CustomInstrumentationTest.java, test/smoke/testApps/HttpClients/src/smokeTest/java/com/microsoft/applicationinsights/smoketestapp/HttpClientSmokeTest.java, test/smoke/testApps/Jdbc/src/smokeTest/java/com/microsoft/applicationinsights/smoketestapp/JdbcSmokeTest.java, test/smoke/testApps/MongoDB/src/smokeTest/java/com/microsoft/applicationinsights/smoketestapp/MongoSmokeTest.java, test/smoke/testApps/SpringBootTest/src/smokeTest/java/com/springbootstartertest/smoketest/SpringbootSmokeTest.java, test/smoke/testApps/TraceLog4j1_2UsingAgent/src/smokeTest/java/com/microsoft/applicationinsights/smoketest/TraceLog4j1_2Test.java, test/smoke/testApps/TraceLog4j2UsingAgent/src/smokeTest/java/com/microsoft/applicationinsights/smoketest/TraceLog4j2Test.java, test/smoke/testApps/TraceLogBackUsingAgent/src/smokeTest/java/com/microsoft/applicationinsights/smoketest/TraceLogBackTest.java, web/src/main/java/com/microsoft/applicationinsights/web/extensibility/initializers/WebOperationIdTelemetryInitializer.java, web/src/main/java/com/microsoft/applicationinsights/web/internal/SdkBridgeImpl.java, web/src/main/java/com/microsoft/applicationinsights/web/internal/correlation/TraceContextCorrelation.java, web/src/test/java/com/microsoft/applicationinsights/web/extensibility/initializers/WebOperationIdTelemetryInitializerTests.java, web/src/test/java/com/microsoft/applicationinsights/web/extensibility/modules/WebRequestTrackingTelemetryModuleTests.java, web/src/test/java/com/microsoft/applicationinsights/web/internal/correlation/TraceContextCorrelationTests.java
=> Id format changes in W3C mode

test/smoke/testApps/Jdbc/src/main/java/com/microsoft/applicationinsights/smoketestapp/JdbcTestServlet.java, test/smoke/testApps/Jdbc/src/smokeTest/java/com/microsoft/applicationinsights/smoketestapp/JdbcSmokeTest.java
There were some updates to the database containers which needed to be addressed. We'll need to merge this over to codeless also.
=> fix jdbc tests

.gitignore, .idea/codeStyles/Project.xml, .idea/codeStyles/codeStyleConfig.xml
@trask, let me know if you see anything that you think shouldn't be sync'ed (or if there's anything you'd like to add)
=> sync intellij project settings

web/src/main/java/com/microsoft/applicationinsights/web/internal/correlation/TraceContextCorrelation.java
Blocked by an exception when running an application:
```
java.lang.ArrayIndexOutOfBoundsException: Index 1 out of bounds for length 1
at com.microsoft.applicationinsights.web.internal.correlation.TraceContextCorrelation.generateChildDependencyTarget(TraceContextCorrelation.java:381)
at com.microsoft.applicationinsights.web.internal.SdkBridgeImpl.generateChildDependencyTarget(SdkBridgeImpl.java:57)
at com.microsoft.applicationinsights.agent.internal.model.OutgoingSpanImpl.toHttpTelemetry(OutgoingSpanImpl.java:163)
at com.microsoft.applicationinsights.agent.internal.model.OutgoingSpanImpl.endInternal(OutgoingSpanImpl.java:111)
at com.microsoft.applicationinsights.agent.internal.model.OutgoingSpanImpl.end(OutgoingSpanImpl.java:72)
at …
```
=> Fix index out of bounds exception

agent/agent-bootstrap/src/main/resources/rp-logger-config/diagnostics.appender.xml
Missing elements. Probably from the merge from codeless.
=> fix xml file

agent/agent-bootstrap/src/main/resources/rp-logger-config/diagnostics.appender.xml, agent/agent-bootstrap/src/main/resources/rp-logger-config/user-logfile.appender.xml
This change (3899f063c9dc5367f1355ee18a73f7ff293b5c79) was lost in the codeless branch merge
=> Remove a dash in log file name

agent/agent-bootstrap/src/main/java/com/microsoft/applicationinsights/agent/bootstrap/diagnostics/etw/EtwAppender.java, agent/agent-bootstrap/src/main/resources/applicationinsights.appsvc.logback.xml, agent/agent-bootstrap/src/main/resources/rp-logger-config/diagnostics.appender.xml, agent/agent-bootstrap/src/main/resources/rp-logger-config/etw.appender.xml, agent/agent-bootstrap/src/main/resources/rp-logger-config/user-logfile.appender.xml, agent/agent/build.gradle, etw/java/build.gradle, etw/java/spotbugs.exclude.xml, etw/java/src/main/java/com/microsoft/applicationinsights/agent/bootstrap/diagnostics/etw/DllFileUtils.java, etw/java/src/main/java/com/microsoft/applicationinsights/agent/bootstrap/diagnostics/etw/events/model/IpaEtwEventBase.java, etw/java/src/main/java/com/microsoft/applicationinsights/agent/bootstrap/diagnostics/etw/events/model/IpaEtwEventErrorBase.java, etw/java/src/main/jni/com/microsoft/applicationinsights/agent/bootstrap/diagnostics/etw/EtwProvider.java, etw/java/src/test/java/com/microsoft/applicationinsights/agent/bootstrap/diagnostics/etw/EtwProviderTests.java, gradle/common-java.gradle
Removed dependencies from ETW library.
=> Fix ETW build

web/src/main/java/com/microsoft/applicationinsights/web/internal/httputils/HttpServerHandler.java
=> [#1247] Fixed RequestTelemetryContext initialization

azure-application-insights-spring-boot-starter/README.md
Add azure.application-insights.telemetry-processor.sampling.enabled property to the spring-boot-starter's readme.
=> Update README with sampling.enabled property

core/src/main/java/com/microsoft/applicationinsights/web/internal/correlation/CdsProfileFetcher.java
This should resolve second occurrence of #1260
=> Fix non-daemon thread pool

ApplicationInsightsInternalLogger/src/main/java/com/microsoft/applicationinsights/internal/logger/InternalLogger.java, core/src/main/java/com/microsoft/applicationinsights/internal/channel/common/TransmissionFileSystemOutput.java, core/src/test/java/com/microsoft/applicationinsights/internal/channel/common/ActiveTransmissionLoaderTest.java, core/src/test/java/com/microsoft/applicationinsights/internal/logger/LoggerTestHelper.java, gradle/common-java.gradle
Wrapped ObjectInputStream to only allow specific classes to be deserialized.
=> Object deserialization improvements

core/native.gradle
Needed for static analysis scans
=> add debug build for native perf counter dlls

agent/agent/package/Microsoft.ApplicationInsights.JavaCodelessAgent.nuspec, agent/agent/package/README
waiting on #1268 
Update nuspec to use the version variable. Now we will have to pack it with the `-Version` parameter, but this now synchronizes the version with the rest of the branch.
=> Parameterize nuspec

agent/agent-bootstrap/src/main/java/com/microsoft/applicationinsights/agent/bootstrap/diagnostics/etw/EtwAppender.java, agent/agent-bootstrap/src/main/java/com/microsoft/applicationinsights/agent/bootstrap/diagnostics/status/StatusFile.java, etw/java/src/main/java/com/microsoft/applicationinsights/agent/bootstrap/diagnostics/etw/events/IpaVerbose.java, etw/java/src/main/java/com/microsoft/applicationinsights/agent/bootstrap/diagnostics/etw/events/model/IpaEtwEventId.java, etw/java/src/test/java/com/microsoft/applicationinsights/agent/bootstrap/diagnostics/etw/EtwProviderTests.java, etw/native/src/main/cpp/etw_provider.cpp, etw/native/src/main/headers/etw_provider.h
waiting on #1268
This will also require a change to the ETW consumer config. They should have the level set to >=4 (info).
=> Add validation for ETW appender on start

ApplicationInsightsInternalLogger/src/main/java/com/microsoft/applicationinsights/internal/logger/InternalLogger.java, CHANGELOG.md, README.md, core/native.gradle, core/src/main/java/com/microsoft/applicationinsights/common/CommonUtils.java, core/src/main/java/com/microsoft/applicationinsights/internal/channel/common/ErrorHandler.java, core/src/main/java/com/microsoft/applicationinsights/internal/channel/common/TransmissionFileSystemOutput.java, core/src/main/java/com/microsoft/applicationinsights/internal/channel/common/TransmissionSendResult.java, core/src/main/java/com/microsoft/applicationinsights/internal/perfcounter/JniPCConnector.java, core/src/main/java/com/microsoft/applicationinsights/internal/system/SystemInformation.java, core/src/test/java/com/microsoft/applicationinsights/internal/channel/common/ActiveTransmissionLoaderTest.java, core/src/test/java/com/microsoft/applicationinsights/internal/logger/LoggerTestHelper.java, gradle/common-java.gradle
Need to merge #1285 first to fix build
=> Merge from master

agent/agent-bootstrap/src/main/java/com/microsoft/applicationinsights/agent/bootstrap/BytecodeUtil.java, agent/agent-tooling/build.gradle, agent/agent-tooling/src/main/java/com/microsoft/applicationinsights/agent/internal/BeforeAgentInstaller.java, agent/agent-tooling/src/main/java/com/microsoft/applicationinsights/agent/internal/instrumentation/sdk/ApplicationInsightsAppenderClassFileTransformer.java, agent/agent-tooling/src/main/java/com/microsoft/applicationinsights/agent/internal/instrumentation/sdk/BytecodeUtilImpl.java, agent/agent-tooling/src/main/java/com/microsoft/applicationinsights/agent/internal/instrumentation/sdk/TelemetryClientClassFileTransformer.java, test/smoke/testApps/CoreAndFilter/src/smokeTest/java/com/microsoft/applicationinsights/smoketest/CoreAndFilterTests.java
Fix [#7699539](https://msazure.visualstudio.com/One/_boards/board/t/Azure%20Attach%20(Java%20NET)/Features/?workitem=7699539)
=> Implement trackTrace and remove duplicate logging by manipulating ApplicationInsightsAppender bytecode

agent/agent-tooling/src/main/java/com/microsoft/applicationinsights/agent/internal/BeforeAgentInstaller.java, test/smoke/testApps/Kafka/src/main/java/com/microsoft/ajl/simple/HelloController.java, test/smoke/testApps/SpringCloudStream/src/main/java/com/microsoft/ajl/simple/GreetingsController.java, test/smoke/testApps/TraceJavaUtilLoggingUsingAgent/src/smokeTest/java/com/microsoft/applicationinsights/smoketest/TraceJavaUtilLoggingTest.java, test/smoke/testApps/TraceLog4j1_2/src/smokeTest/java/com/microsoft/applicationinsights/smoketest/TraceLog4j1_2Test.java, test/smoke/testApps/TraceLog4j1_2UsingAgent/src/smokeTest/java/com/microsoft/applicationinsights/smoketest/TraceLog4j1_2Test.java, test/smoke/testApps/TraceLog4j2/src/smokeTest/java/com/microsoft/applicationinsights/smoketest/TraceLog4j2Test.java, test/smoke/testApps/TraceLog4j2UsingAgent/src/smokeTest/java/com/microsoft/applicationinsights/smoketest/TraceLog4j2Test.java, test/smoke/testApps/TraceLogBack/src/smokeTest/java/com/microsoft/applicationinsights/smoketest/TraceLogBackTest.java, test/smoke/testApps/TraceLogBackUsingAgent/src/smokeTest/java/com/microsoft/applicationinsights/smoketest/TraceLogBackTest.java
Fix [#8089850](https://msazure.visualstudio.com/One/_boards/board/t/Azure%20Attach%20(Java%20NET)/Features/?workitem=8089850)
=> Change default logging from WARN to INFO

.gitmodules, agent/exporter/src/main/java/com/microsoft/applicationinsights/agent/Exporter.java, test/smoke/testApps/TraceLog4j1_2/src/main/java/com/microsoft/ajl/simplecalc/SimpleTestTraceLog4j1_2Servlet.java, test/smoke/testApps/TraceLog4j1_2/src/main/java/com/microsoft/ajl/simplecalc/SimpleTestTraceLog4j1_2WithExceptionServlet.java, test/smoke/testApps/TraceLog4j1_2/src/smokeTest/java/com/microsoft/applicationinsights/smoketest/TraceLog4j1_2Test.java, test/smoke/testApps/TraceLog4j1_2UsingAgent/src/main/java/com/microsoft/ajl/simplecalc/SimpleTestTraceLog4j1_2Servlet.java, test/smoke/testApps/TraceLog4j1_2UsingAgent/src/main/java/com/microsoft/ajl/simplecalc/SimpleTestTraceLog4j1_2WithExceptionServlet.java, test/smoke/testApps/TraceLog4j1_2UsingAgent/src/smokeTest/java/com/microsoft/applicationinsights/smoketest/TraceLog4j1_2Test.java, test/smoke/testApps/TraceLog4j2/src/main/java/com/microsoft/ajl/simplecalc/SimpleTestTraceLog4j2Servlet.java, test/smoke/testApps/TraceLog4j2/src/main/java/com/microsoft/ajl/simplecalc/SimpleTestTraceLog4j2WithExceptionServlet.java, test/smoke/testApps/TraceLog4j2/src/smokeTest/java/com/microsoft/applicationinsights/smoketest/TraceLog4j2Test.java, test/smoke/testApps/TraceLog4j2UsingAgent/src/main/java/com/microsoft/ajl/simplecalc/SimpleTestTraceLog4j2Servlet.java, test/smoke/testApps/TraceLog4j2UsingAgent/src/main/java/com/microsoft/ajl/simplecalc/SimpleTestTraceLog4j2WithExceptionServlet.java, test/smoke/testApps/TraceLog4j2UsingAgent/src/smokeTest/java/com/microsoft/applicationinsights/smoketest/TraceLog4j2Test.java, test/smoke/testApps/TraceLogBack/src/main/java/com/microsoft/ajl/simplecalc/SimpleTestTraceLogBackServlet.java, test/smoke/testApps/TraceLogBack/src/main/java/com/microsoft/ajl/simplecalc/SimpleTestTraceLogBackWithExceptionServlet.java, test/smoke/testApps/TraceLogBack/src/smokeTest/java/com/microsoft/applicationinsights/smoketest/TraceLogBackTest.java, test/smoke/testApps/TraceLogBackUsingAgent/src/main/java/com/microsoft/ajl/simplecalc/SimpleTestTraceLogBackServlet.java, test/smoke/testApps/TraceLogBackUsingAgent/src/main/java/com/microsoft/ajl/simplecalc/SimpleTestTraceLogBackWithExceptionServlet.java, test/smoke/testApps/TraceLogBackUsingAgent/src/smokeTest/java/com/microsoft/applicationinsights/smoketest/TraceLogBackTest.java
Fix [#6620601](https://msazure.visualstudio.com/One/_boards/board/t/Azure%20Attach%20(Java%20NET)/Features/?workitem=6620601)
=> Fix MDC logging

agent/agent-bootstrap/src/main/java/com/microsoft/applicationinsights/agent/bootstrap/BytecodeUtil.java, agent/agent-tooling/build.gradle, agent/agent-tooling/src/main/java/com/microsoft/applicationinsights/agent/internal/BeforeAgentInstaller.java, agent/agent-tooling/src/main/java/com/microsoft/applicationinsights/agent/internal/instrumentation/sdk/BytecodeUtilImpl.java, agent/agent-tooling/src/main/java/com/microsoft/applicationinsights/agent/internal/instrumentation/sdk/TelemetryClientClassFileTransformer.java, agent/agent-tooling/src/main/java/com/microsoft/applicationinsights/agent/internal/instrumentation/sdk/WebRequestTrackingFilterClassFileTransformer.java, test/smoke/testApps/CoreAndFilter/src/main/java/com/microsoft/ajl/simplecalc/SimpleTrackHttpRequestServlet.java, test/smoke/testApps/CoreAndFilter/src/smokeTest/java/com/microsoft/applicationinsights/smoketest/CoreAndFilterTests.java
Fix [#8144875](https://msazure.visualstudio.com/One/_boards/board/t/Azure%20Attach%20(Java%20NET)/Features/?workitem=8144875)
=> Instrument trackRequest and trackException

CHANGELOG.md, gradle.properties
Updated CHANGELOG and version number.
=> Prepare for 2.6.2 GA release

agent/agent-bootstrap/src/main/java/com/microsoft/applicationinsights/agent/bootstrap/configuration/ConfigurationBuilder.java, agent/agent-bootstrap/src/main/java/com/microsoft/applicationinsights/agent/bootstrap/configuration/InstrumentationSettings.java, agent/agent-bootstrap/src/test/java/com/microsoft/applicationinsights/agent/bootstrap/configuration/ConfigurationBuilderTest.java, agent/agent-bootstrap/src/test/java/com/microsoft/applicationinsights/agent/bootstrap/configuration/ConfigurationTest.java, agent/agent-bootstrap/src/test/resources/ApplicationInsights.json, agent/exporter/src/main/java/com/microsoft/applicationinsights/agent/Exporter.java
Fix [#7963772](https://msazure.visualstudio.com/One/_boards/board/t/Azure%20Attach%20(Java%20NET)/Features/?workitem=7963772), [#8261291](https://msazure.visualstudio.com/One/_boards/board/t/Azure%20Attach%20(Java%20NET)/Features/?workitem=8261291), [#8206362](https://msazure.visualstudio.com/One/_boards/board/t/Azure%20Attach%20(Java%20NET)/Features/?workitem=8206362).
=> Add 3 env variables

agent/agent-bootstrap/build.gradle, agent/agent-bootstrap/src/main/java/com/microsoft/applicationinsights/agent/bootstrap/MainEntryPoint.java, agent/agent-bootstrap/src/main/java/io/opentelemetry/javaagent/bootstrap/ConfigureLogging.java, agent/agent-bootstrap/src/main/java/io/opentelemetry/javaagent/config/ConfigOverride.java, agent/agent-tooling/build.gradle, agent/agent-tooling/src/main/java/com/microsoft/applicationinsights/agent/internal/BeforeAgentInstaller.java, agent/agent-tooling/src/main/java/io/opentelemetry/javaagent/tooling/BeforeAgentInstaller.java, agent/agent-tooling/src/main/java/io/opentelemetry/javaagent/tooling/TracerInstaller.java, agent/agent/build.gradle, agent/agent/jar_contents.regex, agent/agent/spotbugs.exclude.xml, agent/agent/src/main/java/io/opentelemetry/javaagent/OpenTelemetryAgent.java, agent/agent/src/main/java/io/opentelemetry/javaagent/Profiler.java, agent/exporter/build.gradle, agent/exporter/src/main/java/com/microsoft/applicationinsights/agent/Exporter.java, agent/instrumentation/build.gradle, core/src/main/java/com/microsoft/applicationinsights/internal/perfcounter/AbstractJmxPerformanceCounter.java, test/smoke/testApps/HttpClients/build.gradle, test/smoke/testApps/HttpClients/src/main/java/com/microsoft/applicationinsights/smoketestapp/HttpClientTestServlet.java, test/smoke/testApps/HttpClients/src/smokeTest/java/com/microsoft/applicationinsights/smoketestapp/HttpClientSmokeTest.java, test/smoke/testApps/JMS/src/smokeTest/java/com/microsoft/applicationinsights/smoketest/JmsTest.java, test/smoke/testApps/VerifyShading/src/main/java/com/microsoft/ajl/simple/TestController.java
Update to OpenTelemetry auto-instrumentation 0.8.0 and interop with OpenTelemetry SDK 0.8.0
Also included smoke tests and fix for Apache HttpAsyncClient instrumentation (Resolves #1321)
=> Update to otel 0.8.0

instrumentation-api/src/main/java/io/opentelemetry/instrumentation/api/tracer/HttpClientTracer.java, instrumentation-api/src/test/groovy/io/opentelemetry/instrumentation/api/tracer/HttpClientTracerTest.groovy, instrumentation/aws-sdk/aws-sdk-1.11/src/test/groovy/AWS1ClientTest.groovy, instrumentation/aws-sdk/aws-sdk-1.11/src/test_before_1_11_106/groovy/AWS0ClientTest.groovy, instrumentation/aws-sdk/aws-sdk-2.2/testing/src/main/groovy/io/opentelemetry/instrumentation/awssdk/v2_2/AbstractAws2ClientTest.groovy, instrumentation/http-url-connection/src/test/groovy/UrlConnectionTest.groovy
This was fixed in upstream otel repo recently, and will be available in the otel 0.9.0 release, but patching locally for now.
=> Fix for url with spaces

agent/exporter/src/main/java/com/microsoft/applicationinsights/agent/Exporter.java, test/fakeIngestion/standalone/src/main/java/com/microsoft/applicationinsights/test/fakeingestion/MockedAppInsightsIngestionServer.java, test/smoke/testApps/CachingCalculator/src/smokeTest/java/com/microsoft/applicationinsights/smoketest/SampleTestWithDependencyContainer.java, test/smoke/testApps/Cassandra/src/smokeTest/java/com/microsoft/applicationinsights/smoketestapp/CassandraSmokeTest.java, test/smoke/testApps/CoreAndFilter/src/smokeTest/java/com/microsoft/applicationinsights/smoketest/CoreAndFilterTests.java, test/smoke/testApps/HttpClients/src/smokeTest/java/com/microsoft/applicationinsights/smoketestapp/HttpClientSmokeTest.java, test/smoke/testApps/JMS/src/smokeTest/java/com/microsoft/applicationinsights/smoketest/JmsTest.java, test/smoke/testApps/Jdbc/src/main/java/com/microsoft/applicationinsights/smoketestapp/JdbcTestServlet.java, test/smoke/testApps/Jdbc/src/smokeTest/java/com/microsoft/applicationinsights/smoketestapp/JdbcSmokeTest.java, test/smoke/testApps/Kafka/src/smokeTest/java/com/microsoft/applicationinsights/smoketest/KafkaTest.java, test/smoke/testApps/Lettuce/src/smokeTest/java/com/microsoft/applicationinsights/smoketest/LettuceSmokeTest.java, test/smoke/testApps/MongoDB/src/smokeTest/java/com/microsoft/applicationinsights/smoketestapp/MongoSmokeTest.java, test/smoke/testApps/SpringBootTest/src/smokeTest/java/com/springbootstartertest/smoketest/SpringbootSmokeTest.java, test/smoke/testApps/SpringCloudStream/src/smokeTest/java/com/microsoft/applicationinsights/smoketest/SpringCloudStreamTest.java, test/smoke/testApps/TraceJavaUtilLoggingUsingAgent/src/smokeTest/java/com/microsoft/applicationinsights/smoketest/TraceJavaUtilLoggingTest.java, test/smoke/testApps/TraceLog4j1_2/src/smokeTest/java/com/microsoft/applicationinsights/smoketest/TraceLog4j1_2Test.java, test/smoke/testApps/TraceLog4j1_2UsingAgent/src/smokeTest/java/com/microsoft/applicationinsights/smoketest/TraceLog4j1_2Test.java, test/smoke/testApps/TraceLog4j2/src/smokeTest/java/com/microsoft/applicationinsights/smoketest/TraceLog4j2Test.java, test/smoke/testApps/TraceLog4j2UsingAgent/src/smokeTest/java/com/microsoft/applicationinsights/smoketest/TraceLog4j2Test.java, test/smoke/testApps/TraceLogBack/src/smokeTest/java/com/microsoft/applicationinsights/smoketest/TraceLogBackTest.java, test/smoke/testApps/TraceLogBackUsingAgent/src/smokeTest/java/com/microsoft/applicationinsights/smoketest/TraceLogBackTest.java, test/smoke/testApps/gRPC/src/smokeTest/java/com/microsoft/applicationinsights/smoketest/GrpcTest.java
This PR is to finish [workitem](https://msazure.visualstudio.com/One/_workitems/edit/7963836)
=> update sql dependency name

core/src/main/java/com/microsoft/applicationinsights/internal/quickpulse/DefaultQuickPulseDataFetcher.java
This will address this issue [#206218273](https://portal.microsofticm.com/imp/v3/incidents/details/206218273/home).
=> Use the correct metric weight for Live Metrics

agent/exporter/src/main/java/com/microsoft/applicationinsights/agent/Exporter.java
Update to use message queue icon in App Map for Kafka.
=> update to use message queue icon

test/smoke/testApps/HttpClients/src/smokeTest/java/com/microsoft/applicationinsights/smoketestapp/HttpClientSmokeTest.java
Fix [#8406278](https://msazure.visualstudio.com/One/_boards/board/t/Azure%20Attach%20(Java%20NET)/Features/?workitem=8406278)
=> Add smoke test for SpringWebClient

agent/agent-bootstrap/src/main/java/com/microsoft/applicationinsights/agent/bootstrap/configuration/InstrumentationSettings.java, agent/agent-tooling/src/main/java/com/microsoft/applicationinsights/agent/internal/BeforeAgentInstaller.java, core/build.gradle, core/src/main/java/com/microsoft/applicationinsights/extensibility/initializer/ResourceAttributesContextInitializer.java, core/src/test/java/com/microsoft/applicationinsights/extensibility/initializer/ResourceAttributesContextInitializerTest.java, test/smoke/appServers/global-resources/ResourceAttributes_ApplicationInsights.json, test/smoke/testApps/ResourceAttributes/build.gradle, test/smoke/testApps/ResourceAttributes/src/main/java/com/microsoft/ajl/simple/SpringBootApp.java, test/smoke/testApps/ResourceAttributes/src/main/java/com/microsoft/ajl/simple/TestController.java, test/smoke/testApps/ResourceAttributes/src/smokeTest/java/com/microsoft/applicationinsights/smoketest/ResourceAttributesTest.java, test/smoke/testApps/ResourceAttributes/src/smokeTest/resources/appServers.txt, test/smoke/testApps/ResourceAttributes/src/smokeTest/resources/logback-test.xml
Support resource attributes. 
[workitem](https://msazure.visualstudio.com/One/_workitems/edit/7013136)
=> Support resource attributes

agent/exporter/src/main/java/com/microsoft/applicationinsights/agent/Exporter.java, test/smoke/testApps/JMS/src/smokeTest/java/com/microsoft/applicationinsights/smoketest/JmsTest.java, test/smoke/testApps/JMS/src/smokeTest/resources/jre.excludes.txt, test/smoke/testApps/Kafka/src/smokeTest/java/com/microsoft/applicationinsights/smoketest/KafkaTest.java
=> update JMS type to use Queue message icon

agent/agent-tooling/src/main/java/com/microsoft/applicationinsights/agent/internal/BeforeAgentInstaller.java, agent/exporter/src/main/java/com/microsoft/applicationinsights/agent/Exporter.java, core/src/main/java/com/microsoft/applicationinsights/web/internal/correlation/CdsProfileFetcher.java, test/smoke/testApps/CachingCalculator/src/smokeTest/java/com/microsoft/applicationinsights/smoketest/SampleTestWithDependencyContainer.java, test/smoke/testApps/Cassandra/src/smokeTest/java/com/microsoft/applicationinsights/smoketestapp/CassandraSmokeTest.java, test/smoke/testApps/HttpClients/src/smokeTest/java/com/microsoft/applicationinsights/smoketestapp/HttpClientSmokeTest.java, test/smoke/testApps/JMS/src/smokeTest/java/com/microsoft/applicationinsights/smoketest/JmsTest.java, test/smoke/testApps/Jdbc/src/main/java/com/microsoft/applicationinsights/smoketestapp/JdbcTestServlet.java, test/smoke/testApps/Jdbc/src/smokeTest/java/com/microsoft/applicationinsights/smoketestapp/JdbcSmokeTest.java, test/smoke/testApps/Kafka/src/smokeTest/java/com/microsoft/applicationinsights/smoketest/KafkaTest.java, test/smoke/testApps/Lettuce/src/smokeTest/java/com/microsoft/applicationinsights/smoketest/LettuceSmokeTest.java, test/smoke/testApps/MongoDB/src/smokeTest/java/com/microsoft/applicationinsights/smoketestapp/MongoSmokeTest.java, test/smoke/testApps/SpringCloudStream/src/smokeTest/java/com/microsoft/applicationinsights/smoketest/SpringCloudStreamTest.java, test/smoke/testApps/gRPC/src/smokeTest/java/com/microsoft/applicationinsights/smoketest/GrpcTest.java
Improvements to the exporter mappings.
Also a commit that fixes `CdsProfileFetcher` to use configured http proxy.
=> Update exporter mappings

agent/exporter/src/main/java/com/microsoft/applicationinsights/agent/Exporter.java
A few things:
* by adding special case for "spring-scheduling" INTERNAL span, it will prevent misc INTERNAL spans from showing up in request table
* fixed mapping of CONSUMER spans (due to new instrumentation in 0.10.0 that hasn't been released yet)
* fixed dependency type for messaging spans that are not PRODUCER
=> Exporter mapping improvements

test/smoke/testApps/AutoPerfCounters/build.gradle, test/smoke/testApps/CachingCalculator/build.gradle, test/smoke/testApps/Cassandra/build.gradle, test/smoke/testApps/CoreAndFilter/build.gradle, test/smoke/testApps/CustomDimensions/build.gradle, test/smoke/testApps/CustomInstrumentation/build.gradle, test/smoke/testApps/FixedRateSampling/build.gradle, test/smoke/testApps/HeartBeat/build.gradle, test/smoke/testApps/HttpClients/build.gradle, test/smoke/testApps/Jdbc/build.gradle, test/smoke/testApps/Lettuce/build.gradle, test/smoke/testApps/MongoDB/build.gradle, test/smoke/testApps/SpringBoot1_3Auto/build.gradle, test/smoke/testApps/SpringBootAuto/build.gradle, test/smoke/testApps/SpringBootTest/build.gradle, test/smoke/testApps/SpringBootTest/src/smokeTest/java/com/springbootstartertest/smoketest/SpringbootSmokeTest.java, test/smoke/testApps/SpringScheduler/build.gradle, test/smoke/testApps/SpringScheduler/src/smokeTest/java/com/microsoft/applicationinsights/smoketest/SpringSchedulerTest.java, test/smoke/testApps/TraceJavaUtilLoggingUsingAgent/build.gradle, test/smoke/testApps/TraceLog4j1_2/build.gradle, test/smoke/testApps/TraceLog4j1_2UsingAgent/build.gradle, test/smoke/testApps/TraceLog4j2/build.gradle, test/smoke/testApps/TraceLog4j2UsingAgent/build.gradle, test/smoke/testApps/TraceLogBack/build.gradle, test/smoke/testApps/TraceLogBackUsingAgent/build.gradle, test/smoke/testApps/WebAuto/build.gradle
Need to update submodule commit hash after #1362 is merged.
=> Add context root to beginning of span names

agent/agent-tooling/src/main/java/com/microsoft/applicationinsights/agent/internal/ConnectionStringAccessor.java, core/src/main/java/com/microsoft/applicationinsights/TelemetryClient.java
and use logger.info
Fix [#8752524](https://msazure.visualstudio.com/One/_boards/board/t/TelReachSDKTeam/Features/?workitem=8752524)
=> Fix NullPointerException for Linux consumption plan

agent/agent-tooling/src/main/java/com/microsoft/applicationinsights/agent/internal/JsonConfigPolling.java, core/src/main/java/com/microsoft/applicationinsights/internal/channel/common/TransmitterImpl.java
Applying feedback from previous PRs
* https://github.com/microsoft/ApplicationInsights-Java/pull/1368#discussion_r515233089
* https://github.com/microsoft/ApplicationInsights-Java/pull/1368#discussion_r515223800
=> Apply feedback from previous PRs

instrumentation/azure-functions/src/main/java/io/opentelemetry/instrumentation/auto/azure/functions/AzureFunctionsInstrumentation.java, instrumentation/azure-functions/src/main/java/io/opentelemetry/instrumentation/auto/azure/functions/AzureFunctionsInstrumentationHelper.java, instrumentation/azure-functions/src/main/java/io/opentelemetry/instrumentation/auto/azure/functions/InvocationRequestExtractAdapter.java, instrumentation/azure-functions/src/test/java/io/opentelemetry/instrumentation/auto/azure/functions/AzureFunctionsInstrumentationHelperTest.java
Fix [#8752539](https://msazure.visualstudio.com/One/_boards/board/t/TelReachSDKTeam/Features/?workitem=8752539)
Tested the following:
=> Support preview opt-in and GA opt-out for Linux consumption plan

instrumentation/azure-functions/azure-functions.gradle, instrumentation/azure-functions/src/main/java/io/opentelemetry/instrumentation/auto/azure/functions/AzureFunctionsInstrumentationHelper.java, instrumentation/azure-functions/src/test/java/io/opentelemetry/instrumentation/auto/azure/functions/AzureFunctionsInstrumentationHelperTest.java
=> Remove guava usage from Azure Functions instrumentation

core/src/main/java/com/microsoft/applicationinsights/extensibility/initializer/ResourceAttributesContextInitializer.java, test/smoke/appServers/global-resources/customdimensions_applicationinsights.json, test/smoke/testApps/CustomDimensions/src/smokeTest/java/com/microsoft/applicationinsights/smoketest/CustomDimensionsTest.java
=> Map service.version to application_Version

agent/agent-bootstrap/src/main/java/com/microsoft/applicationinsights/agent/bootstrap/MainEntryPoint.java, agent/agent-bootstrap/src/main/java/com/microsoft/applicationinsights/agent/bootstrap/configuration/Configuration.java, agent/agent-bootstrap/src/main/java/com/microsoft/applicationinsights/agent/bootstrap/customExceptions/FriendlyException.java, agent/agent-bootstrap/src/test/java/com/microsoft/applicationinsights/agent/bootstrap/MainEntryPointTest.java, agent/agent-tooling/src/main/java/com/microsoft/applicationinsights/agent/internal/BeforeAgentInstaller.java, agent/agent-tooling/src/main/java/com/microsoft/applicationinsights/agent/internal/processors/ExporterWithAttributeProcessor.java, agent/agent-tooling/src/main/java/com/microsoft/applicationinsights/agent/internal/processors/ExporterWithSpanProcessor.java, agent/agent-tooling/src/main/java/io/opentelemetry/javaagent/tooling/TracerInstaller.java, agent/agent-tooling/src/test/java/com/microsoft/applicationinsights/agent/internal/processors/ExporterWithAttributeProcessorTest.java, agent/agent-tooling/src/test/java/com/microsoft/applicationinsights/agent/internal/processors/ExporterWithSpanProcessorTest.java, core/src/main/java/com/microsoft/applicationinsights/customExceptions/FriendlyException.java, core/src/main/java/com/microsoft/applicationinsights/internal/channel/common/ApacheSender.java, core/src/main/java/com/microsoft/applicationinsights/internal/channel/common/ApacheSender43.java, core/src/main/java/com/microsoft/applicationinsights/internal/channel/common/TransmissionNetworkOutput.java, core/src/main/java/com/microsoft/applicationinsights/internal/quickpulse/DefaultQuickPulsePingSender.java, core/src/main/java/com/microsoft/applicationinsights/web/internal/correlation/ApplicationIdResolver.java, core/src/main/java/com/microsoft/applicationinsights/web/internal/correlation/CdsProfileFetcher.java, core/src/main/java/com/microsoft/applicationinsights/web/internal/correlation/InstrumentationKeyResolver.java
Feature request
Includes friendly error messages for
* Missing connection string
* Invalid SSL certificate issues when not able to connect to IngestionEndPoint Url, Live endpoint Url and CdsProfiler endpoint url.
* Invalid Telemetry Processor Configuration
The following are forwarding urls used in the log messages
https://go.microsoft.com/fwlink/?linkid=2151450  -> Troubleshooting Docs
https://go.microsoft.com/fwlink/?linkid=2151557  -> Telemetry Processors
https://go.microsoft.com/fwlink/?linkid=2151451  -> Java IPA Overview
=> Enable Awesome Logging

CHANGELOG.md
=> Getting Ready for release 3.0.1-BETA

instrumentation/log4j/log4j-spans-2.0/javaagent/log4j-spans-2.0-javaagent.gradle, instrumentation/log4j/log4j-spans-2.0/javaagent/src/main/java/io/opentelemetry/javaagent/instrumentation/log4j/v2_0/Log4jSpansInstrumentationModule.java
Addresses #1389 (will resolve in PR that bumps submodule)
=> Capture log4j2 async logging

agent/agent-tooling/build.gradle, build.gradle
=> Update a couple of dependencies

agent/agent-bootstrap/src/main/java/com/microsoft/applicationinsights/agent/bootstrap/configuration/ConfigurationBuilder.java
Resolves #1422
(this PR also contains minor unrelated refactoring of jmx metrics config method)
=> Add APPLICATIONINSIGHTS_SELF_DIAGNOSTICS_LEVEL env var

CHANGELOG.md, NOTICE, gradle.properties
=> Getting ready for 3.0.1 GA

agent/agent-bootstrap/src/main/java/com/microsoft/applicationinsights/agent/bootstrap/MainEntryPoint.java, agent/agent-bootstrap/src/main/resources/applicationinsights.appsvc.logback.xml, agent/agent-bootstrap/src/main/resources/logger-config/common.xml
Fix [9130498](https://msazure.visualstudio.com/One/_sprints/taskboard/TelReachSDKTeam/One/AEP/Cobalt/2101?workitem=9130498).
=> Fix App Services logback parser failure 

agent/agent-bootstrap/src/main/java/com/microsoft/applicationinsights/agent/bootstrap/configuration/ConfigurationBuilder.java, agent/agent-bootstrap/src/test/java/com/microsoft/applicationinsights/agent/bootstrap/configuration/ConfigurationTest.java, agent/agent-bootstrap/src/test/resources/applicationinsights_NoRole.json
=> Fix role name config

agent/agent-bootstrap/spotbugs.exclude.xml, agent/agent-bootstrap/src/main/java/com/microsoft/applicationinsights/agent/bootstrap/MainEntryPoint.java, agent/agent-bootstrap/src/main/java/com/microsoft/applicationinsights/agent/bootstrap/configuration/ConfigurationBuilder.java, agent/agent-bootstrap/src/test/java/com/microsoft/applicationinsights/agent/bootstrap/configuration/ConfigurationTest.java, agent/agent-bootstrap/src/test/resources/ApplicationInsights_SpanProcessor.json, agent/agent-bootstrap/src/test/resources/applicationinsights_faulty.json, test/smoke/appServers/global-resources/spanprocessor_applicationinsights.json
Enhancements:
Improve discoverability of configuration file syntax error
Fail on invalid config attributes instead of silently ignoring
=> Configuration file related changes

agent/agent-bootstrap/src/main/java/com/microsoft/applicationinsights/agent/bootstrap/configuration/ConfigurationBuilder.java
Added screenshots of the error message seen when exception is thrown.
=> Friendly exception for configuration related issues added

instrumentation/applicationinsights-web-2.3/javaagent/src/main/java/io.opentelemetry.javaagent.instrumentation.applicationinsightsweb/RequestTelemetryContextInstrumentation.java, instrumentation/applicationinsights-web-2.3/javaagent/src/test/groovy/ApplicationInsightsWebTest.groovy
See https://github.com/microsoft/ApplicationInsights-Java/issues/1442#issuecomment-767277089 item 1
=> Fix RequestTelemetryContext.getTracestate() interop

core/src/main/java/com/microsoft/applicationinsights/internal/channel/common/ApacheSender43.java, core/src/main/java/com/microsoft/applicationinsights/internal/util/DeviceInfo.java, core/src/main/java/com/microsoft/applicationinsights/internal/util/SSLUtil.java, core/src/main/java/com/microsoft/applicationinsights/web/internal/correlation/CdsProfileFetcher.java
Some screen shots:
Will add more screenshots once I find the binary that has cert issue.
=> Improve friendly messages for cert issues.

instrumentation/java-util-logging-spans/javaagent/src/main/java/io/opentelemetry/javaagent/instrumentation/jul/JavaUtilLoggingSpansInstrumentationModule.java, instrumentation/log4j/log4j-spans-1.2/javaagent/src/main/java/io/opentelemetry/javaagent/instrumentation/log4j/v1_2/Log4jSpansInstrumentationModule.java, instrumentation/log4j/log4j-spans-2.0/javaagent/src/main/java/io/opentelemetry/javaagent/instrumentation/log4j/v2_0/Log4jSpansInstrumentationModule.java, instrumentation/logback/logback-spans-1.0/javaagent/src/main/java/io/opentelemetry/javaagent/instrumentation/logback/LogbackSpansInstrumentationModule.java, instrumentation/spring/spring-webmvc-3.1/javaagent/src/main/java/io/opentelemetry/javaagent/instrumentation/springwebmvc/HandlerMappingResourceNameFilter.java
This PR also brings in a few unrelated useful comments
=> Trying to fix JBoss ear issue

benchmark-e2e/benchmark-e2e.gradle, examples/distro/smoke-tests/build.gradle, gradle/dependencies.gradle, instrumentation-api/src/main/java/io/opentelemetry/instrumentation/api/aiappid/AiAppId.java, instrumentation-api/src/main/java/io/opentelemetry/instrumentation/api/tracer/HttpClientTracer.java, instrumentation-api/src/main/java/io/opentelemetry/instrumentation/api/tracer/HttpServerTracer.java, instrumentation/apache-camel-2.20/javaagent/apache-camel-2.20-javaagent.gradle, instrumentation/applicationinsights-web-2.3/javaagent/src/main/java/io.opentelemetry.javaagent.instrumentation.applicationinsightsweb/RequestTelemetryInstrumentation.java, instrumentation/applicationinsights-web-2.3/javaagent/src/main/java/io.opentelemetry.javaagent.instrumentation.applicationinsightsweb/ThreadContextInstrumentation.java, instrumentation/applicationinsights-web-2.3/javaagent/src/test/groovy/ApplicationInsightsWebTest.groovy, instrumentation/applicationinsights-web-2.3/javaagent/src/test/java/Code.java
note to self: merge don't squash
=> Add 2.x setSource() interop

core/build.gradle, gradle.properties
=> Update xstream dependency

agent/agent-bootstrap/build.gradle, agent/agent-bootstrap/src/main/java/com/microsoft/applicationinsights/agent/bootstrap/BytecodeUtil.java, agent/agent-tooling/build.gradle, agent/agent-tooling/src/main/java/com/microsoft/applicationinsights/agent/internal/BeforeAgentInstaller.java, agent/agent-tooling/src/main/java/com/microsoft/applicationinsights/agent/internal/instrumentation/sdk/BytecodeUtilImpl.java, agent/agent-tooling/src/main/java/com/microsoft/applicationinsights/agent/internal/instrumentation/sdk/RequestTelemetryClassFileTransformer.java, agent/agent-tooling/src/main/java/com/microsoft/applicationinsights/agent/internal/instrumentation/sdk/TelemetryClientClassFileTransformer.java, agent/agent-tooling/src/main/java/com/microsoft/applicationinsights/agent/internal/propagator/AiLegacyPropagator.java, agent/agent-tooling/src/main/java/com/microsoft/applicationinsights/agent/internal/propagator/DelegatingPropagator.java, agent/agent-tooling/src/main/java/com/microsoft/applicationinsights/agent/internal/sampling/AiSampler.java, agent/agent-tooling/src/main/java/com/microsoft/applicationinsights/agent/internal/sampling/DelegatingSampler.java, agent/agent-tooling/src/test/java/com/microsoft/applicationinsights/agent/internal/JsonConfigPollingTest.java, agent/exporter/build.gradle, agent/exporter/src/main/java/com/microsoft/applicationinsights/agent/Exporter.java, agent/instrumentation/build.gradle
Also adds 2.x interop for RequestTelemetry source attribute https://github.com/microsoft/ApplicationInsights-Java/issues/1442#issuecomment-776358807
=> Update to latest otel version

.github/workflows/pr.yaml
=> Run GitHub Actions on merge

agent/exporter/src/main/java/com/microsoft/applicationinsights/agent/Exporter.java
I don't think it's needed anymore. Let's see if smoke tests pass without it now 😄.
cc: @srnagar
=> Remove todo

agent/exporter/src/main/java/com/microsoft/applicationinsights/agent/Exporter.java
This special case is no longer needed due to https://github.com/open-telemetry/opentelemetry-java-instrumentation/pull/2091
=> Remove JMS special case

agent/exporter/src/main/java/com/microsoft/applicationinsights/agent/Exporter.java, test/smoke/testApps/SpringBootAuto/src/smokeTest/java/com/microsoft/applicationinsights/smoketest/SpringBootAutoTest.java
=> Populate client IP

core/build.gradle, core/src/main/java/com/microsoft/applicationinsights/internal/channel/common/LazyHttpClient.java, core/src/main/java/com/microsoft/applicationinsights/internal/channel/common/TransmissionNetworkOutput.java, test/smoke/framework/utils/build.gradle, test/smoke/testApps/HttpClients/build.gradle, test/smoke/testApps/JMS/build.gradle, test/smoke/testApps/Kafka/build.gradle, test/smoke/testApps/SpringBootTest/build.gradle
Also set timeouts more consistently.
=> Update Apache HttpClient version

agent/agent-tooling/src/main/java/com/microsoft/applicationinsights/agent/internal/wasbootstrap/configuration/ConfigurationBuilder.java, agent/agent-tooling/src/test/java/com/microsoft/applicationinsights/agent/internal/wasbootstrap/configuration/ConfigurationBuilderTest.java, agent/agent-tooling/src/test/java/com/microsoft/applicationinsights/agent/internal/wasbootstrap/configuration/ConfigurationTest.java
=> Add APPLICATIONINSIGHTS_CONFIGURATION_CONTENT env var

build.gradle, test/smoke/framework/testCore/build.gradle, test/smoke/framework/utils/build.gradle, test/smoke/testApps/build.gradle
It is shutting down, and starting to cause build failures this morning.
https://www.infoq.com/news/2021/02/jfrog-jcenter-bintray-closure/
=> Remove JCenter

.github/workflows/pr.yaml
The `accept-pr` workflow has been hanging sometimes, hoping this will help.
=> Bump technote-space/workflow-conclusion-action version

.idea/codeStyles/Project.xml
This keeps getting changed automatically for me locally, and noticed the same is happening for others in #1513, so makes sense to make the change to the file under source control.
=> Update Intellij project xml

agent/agent-tooling/src/main/java/com/microsoft/applicationinsights/agent/internal/wasbootstrap/configuration/Configuration.java
=> Fix logging

core/src/main/java/com/microsoft/applicationinsights/internal/perfcounter/OshiPerformanceCounter.java
Fixes startup time regression due to oshi.
=> Startup optimization

.pipelines/pipeline.user.windows.official.yml, .pipelines/pipeline.user.windows.yml, .scripts/copy-source.cmd, gradle.properties
Release pipeline is fixed now: https://github-private.visualstudio.com/microsoft/_releaseProgress?releaseId=1271&_a=release-pipeline-progress.
=> Copy and Upload .Scripts to build output

agent/agent-profiler/docs/README.md
=> Add warning about configuring JFR profiles

examples/distro/instrumentation/servlet-3/src/main/java/com/example/javaagent/instrumentation/DemoServlet3InstrumentationModule.java, instrumentation/apache-httpclient/apache-httpclient-4.0/javaagent/src/main/java/io/opentelemetry/javaagent/instrumentation/apachehttpclient/v4_0/HostAndRequestAsHttpUriRequest.java, instrumentation/apache-httpclient/apache-httpclient-4.0/javaagent/src/main/java/io/opentelemetry/javaagent/instrumentation/apachehttpclient/v4_0/HttpHeadersInjectAdapter.java, instrumentation/apache-httpclient/apache-httpclient-5.0/javaagent/src/main/java/io/opentelemetry/javaagent/instrumentation/apachehttpclient/v5_0/HttpHeadersInjectAdapter.java, instrumentation/jaxrs-client/jaxrs-client-2.0/jaxrs-client-2.0-resteasy-2.0/javaagent/jaxrs-client-2.0-resteasy-2.0-javaagent.gradle, instrumentation/kubernetes-client-7.0/javaagent/src/main/java/io/opentelemetry/javaagent/instrumentation/kubernetesclient/RequestBuilderInjectAdapter.java, instrumentation/netty/netty-4.1/javaagent/src/test/groovy/Netty41ClientTest.groovy, instrumentation/okhttp/okhttp-2.2/javaagent/src/main/java/io/opentelemetry/javaagent/instrumentation/okhttp/v2_2/RequestBuilderInjectAdapter.java, instrumentation/okhttp/okhttp-3.0/library/src/main/java/io/opentelemetry/instrumentation/okhttp/v3_0/RequestBuilderInjectAdapter.java
Backport of fix to prevent duplicate headers
=> otel fork: duplicate headers

agent/agent-bootstrap/src/test/java/com/microsoft/applicationinsights/agent/bootstrap/diagnostics/status/StatusFileTests.java
Small fix to make tests pass locally.
=> Fix local test

agent/agent-tooling/src/main/java/com/microsoft/applicationinsights/agent/internal/wasbootstrap/configuration/ConfigurationBuilder.java, agent/agent-tooling/src/main/java/com/microsoft/applicationinsights/agent/internal/wasbootstrap/configuration/RpConfigurationBuilder.java
* Env variable always win if both provided.
Signed-off-by: Pan Li <panli@microsoft.com>
=> Introduce env variable for application insights RP configuration file.

agent/agent-tooling/src/main/java/com/microsoft/applicationinsights/agent/internal/wasbootstrap/configuration/ConfigurationBuilder.java, agent/agent-tooling/src/main/java/com/microsoft/applicationinsights/agent/internal/wasbootstrap/configuration/RpConfiguration.java
* Role doesn't support hot load.
* Role can be overriden by environment variables.
Signed-off-by: Pan Li <panli@microsoft.com>
=> Introduce role to application rp configuration.

agent/agent-tooling/src/main/java/com/microsoft/applicationinsights/agent/internal/wasbootstrap/configuration/ConfigurationBuilder.java, agent/agent-tooling/src/test/java/com/microsoft/applicationinsights/agent/internal/wasbootstrap/configuration/ConfigurationTest.java
=> Add test for RpConfiguration

gradle.properties
Also bumps version to 3.0.4-BETA.3
Attaching SNAPSHOT for testing: [applicationinsights-agent-3.0.4-BETA.3-SNAPSHOT.jar.zip](https://github.com/microsoft/ApplicationInsights-Java/files/6431578/applicationinsights-agent-3.0.4-BETA.3-SNAPSHOT.jar.zip)
=> Support OpenEJB CXF too

instrumentation/azure-core-1.14/javaagent/src/main/java/io/opentelemetry/javaagent/instrumentation/azuresdk/AzureSdkInstrumentationModule.java
Another azure sdk instrumentation fix
=> otel fork: azure sdk fix

agent/exporter/src/main/java/com/microsoft/applicationinsights/agent/Exporter.java
=> Reduce spammy error

agent/agent-tooling/build.gradle, agent/agent-tooling/gradle/dependency-locks/compileClasspath.lockfile, agent/agent-tooling/gradle/dependency-locks/runtimeClasspath.lockfile, agent/agent-tooling/src/main/java/com/microsoft/applicationinsights/agent/internal/AiComponentInstaller.java, agent/agent-tooling/src/main/java/com/microsoft/applicationinsights/agent/internal/instrumentation/sdk/BytecodeUtilImpl.java, agent/agent-tooling/src/main/java/com/microsoft/applicationinsights/agent/internal/wasbootstrap/OpenTelemetryConfigurer.java, agent/exporter/src/main/java/com/microsoft/applicationinsights/agent/Exporter.java, agent/instrumentation/gradle/dependency-locks/runtimeClasspath.lockfile, core/src/main/java/com/microsoft/applicationinsights/BatchSpanProcessor.java, core/src/main/java/com/microsoft/applicationinsights/BatchSpanProcessorBuilder.java, core/src/main/java/com/microsoft/applicationinsights/ByteBufferOutputStream.java, core/src/main/java/com/microsoft/applicationinsights/ByteBufferPool.java, core/src/main/java/com/microsoft/applicationinsights/LowLevelClient.java, core/src/main/java/com/microsoft/applicationinsights/TelemetryChannel.java, core/src/main/java/com/microsoft/applicationinsights/TelemetryClient.java, test/smoke/testApps/SystemExit/src/smokeTest/java/com/microsoft/applicationinsights/smoketest/SpringBootAutoTest.java
And improvements to the telemetry pipeline that will help when adding falling back to disk.
=> AAD branch: fix shutdown hook

core/src/main/java/com/microsoft/applicationinsights/TelemetryChannel.java, core/src/main/java/com/microsoft/applicationinsights/internal/authentication/AadAuthentication.java, core/src/main/java/com/microsoft/applicationinsights/internal/config/connection/EndpointProvider.java, test/fakeIngestion/servlet/src/main/java/com/microsoft/applicationinsights/test/fakeingestion/MockedAppInsightsIngestionServlet.java, test/smoke/framework/testCore/src/main/java/com/microsoft/applicationinsights/smoketest/AiSmokeTest.java, test/smoke/testApps/CoreAndFilter/src/main/resources/ApplicationInsights.xml
// TODO add redirect policy to http pipeline, else the agent will ignore redirects from v2.1/track
=> add v2.1/track endpoint, add retry policy

CHANGELOG.md, agent/agent-tooling/build.gradle, agent/agent-tooling/gradle/dependency-locks/runtimeClasspath.lockfile, agent/instrumentation/gradle/dependency-locks/runtimeClasspath.lockfile, gradle.properties
OTel changed from `grpc-netty` to `grpc-netty-shaded`
=> Fix agent jar size

agent/agent-bootstrap/src/main/java/com/microsoft/applicationinsights/agent/bootstrap/BytecodeUtil.java, agent/agent-tooling/src/main/java/com/microsoft/applicationinsights/agent/internal/instrumentation/sdk/BytecodeUtilImpl.java, agent/agent-tooling/src/main/java/com/microsoft/applicationinsights/agent/internal/instrumentation/sdk/TelemetryClientClassFileTransformer.java, gradle.properties, test/smoke/testApps/CoreAndFilter/src/main/java/com/microsoft/applicationinsights/smoketestapp/SimpleTrackPageViewServlet.java, test/smoke/testApps/CoreAndFilter/src/smokeTest/java/com/microsoft/applicationinsights/smoketest/CoreAndFilterTests.java
Attaching SNAPSHOT for testing: [applicationinsights-agent-3.1.1-BETA.5-SNAPSHOT.jar.zip](https://github.com/microsoft/ApplicationInsights-Java/files/6595443/applicationinsights-agent-3.1.1-BETA.5-SNAPSHOT.jar.zip)
=> Fix 2.x interop of timestamps

core/src/main/java/com/microsoft/applicationinsights/MetricFilter.java
Seems worthwhile optimization for large exclusion lists, e.g. #1665
=> Metric filter optimization

agent/agent-tooling/src/main/java/com/microsoft/applicationinsights/agent/internal/AiComponentInstaller.java, core/src/main/java/com/microsoft/applicationinsights/internal/statsbeat/Feature.java, core/src/main/java/com/microsoft/applicationinsights/internal/statsbeat/FeatureStatsbeat.java, core/src/main/java/com/microsoft/applicationinsights/internal/statsbeat/StatsbeatModule.java, core/src/test/java/com/microsoft/applicationinsights/internal/statsbeat/FeatureStatsbeatTest.java, core/src/test/java/com/microsoft/applicationinsights/internal/statsbeat/StatsbeatTestUtils.java
Fix [#10122256](https://msazure.visualstudio.com/One/_sprints/taskboard/TelReachSDKTeam/One/AEP/Cobalt/2106?workitem=10122256).
=> Track AAD enablement via Statsbeat

.config/CredScanSuppressions.json
```
<DEFECTS version="21170">
<DEFECT>
<SFA>
<FILEPATH>C:\source\otel\testing-common\src\misc</FILEPATH>
<FILENAME>README.md</FILENAME>
<LINE>5</LINE>
</SFA>
<DEFECTCODE>SecretinFile</DEFECTCODE>
<DESCRIPTION>{{Searcher}}CSCAN-GENERAL0060
{{Code}}See README.md line 5 for the code resulting in match
{{Info}}Found General Password.
{{Suggest}}Validate file contains secrets, remove, roll credential, and use approved store. For additional information on secret remediation see https://aka.ms/credscan </DESCRIPTION>
<RANK>1</RANK>
<ADDITIONALINFO>
<entry key="HashKey:R8MbOpBei/ewtpNjyQ/Yd+J2N69ebpp5wf3ljn2tw8w=" />
<entry key="MatchingScore:71" />
<entry key="SearcherName:General Password" />
</ADDITIONALINFO>
</DEFECT>
<DEFECT>
<SFA>
<FILEPATH>C:\source\otel\testing-common\src\misc</FILEPATH> …
```
=> Suppress cres scan violations

agent/agent-tooling/src/main/java/com/microsoft/applicationinsights/agent/internal/init/LazyConfigurationAccessor.java, agent/agent-tooling/src/main/java/com/microsoft/applicationinsights/agent/internal/init/OpenTelemetryConfigurer.java, agent/agent-tooling/src/main/java/com/microsoft/applicationinsights/agent/internal/legacyheaders/AiLegacyPropagator.java
These comments were renamed by accident when package renaming
=> Fix renames

build.gradle
Forgot to bump version in #1782
=> otel fork: bump version

agent/agent-tooling/src/main/java/com/microsoft/applicationinsights/agent/internal/configuration/Configuration.java, agent/agent-tooling/src/main/java/com/microsoft/applicationinsights/agent/internal/configuration/ConfigurationBuilder.java, agent/agent-tooling/src/main/java/com/microsoft/applicationinsights/agent/internal/init/ConfigOverride.java, agent/agent-tooling/src/test/java/com/microsoft/applicationinsights/agent/internal/configuration/ConfigurationTest.java, agent/instrumentation/build.gradle, agent/instrumentation/gradle.lockfile
SNAPSHOT for testing: [applicationinsights-agent-3.2.0-BETA.2-SNAPSHOT.jar.zip](https://github.com/microsoft/ApplicationInsights-Java/files/6752335/applicationinsights-agent-3.2.0-BETA.2-SNAPSHOT.jar.zip)
=> Add Spring Integration preview

agent/agent-tooling/src/main/java/com/microsoft/applicationinsights/agent/internal/common/ExceptionStats.java, agent/agent-tooling/src/main/java/com/microsoft/applicationinsights/agent/internal/common/TelemetryTruncation.java, agent/agent-tooling/src/main/java/com/microsoft/applicationinsights/agent/internal/exporter/models/AvailabilityData.java, agent/agent-tooling/src/main/java/com/microsoft/applicationinsights/agent/internal/exporter/models/MessageData.java, agent/agent-tooling/src/main/java/com/microsoft/applicationinsights/agent/internal/exporter/models/MetricDataPoint.java, agent/agent-tooling/src/main/java/com/microsoft/applicationinsights/agent/internal/exporter/models/PageViewData.java, agent/agent-tooling/src/main/java/com/microsoft/applicationinsights/agent/internal/exporter/models/PageViewPerfData.java, agent/agent-tooling/src/main/java/com/microsoft/applicationinsights/agent/internal/exporter/models/RemoteDependencyData.java, agent/agent-tooling/src/main/java/com/microsoft/applicationinsights/agent/internal/exporter/models/RequestData.java, agent/agent-tooling/src/main/java/com/microsoft/applicationinsights/agent/internal/exporter/models/StackFrame.java, agent/agent-tooling/src/main/java/com/microsoft/applicationinsights/agent/internal/exporter/models/TelemetryEventData.java, agent/agent-tooling/src/main/java/com/microsoft/applicationinsights/agent/internal/exporter/models/TelemetryExceptionData.java, agent/agent-tooling/src/main/java/com/microsoft/applicationinsights/agent/internal/exporter/models/TelemetryExceptionDetails.java, agent/agent-tooling/src/main/java/com/microsoft/applicationinsights/agent/internal/exporter/models/TelemetryItem.java, agent/agent-tooling/src/main/java/com/microsoft/applicationinsights/agent/internal/exporter/utils/SanitizationHelper.java
=> Log controlled warning when telemetry is truncated

CHANGELOG.md, gradle.properties
=> Release 3.2.0-BETA.2

CHANGELOG.md
=> more updates to release notes 3.2.0-BETA.2

agent/agent-tooling/src/main/java/com/microsoft/applicationinsights/agent/internal/httpclient/LazyHttpClient.java, agent/agent-tooling/src/main/java/com/microsoft/applicationinsights/agent/internal/telemetry/TelemetryChannel.java, agent/agent-tooling/src/main/java/com/microsoft/applicationinsights/agent/internal/telemetry/TelemetryClient.java
Disable AAD authentication while sending statsbeat data
=> Disable AAD authentication on statsbeat

buildSrc/src/main/kotlin/ai.spotless-conventions.gradle.kts
Similar to https://github.com/open-telemetry/opentelemetry-java-instrumentation/pull/3647
=> Faster spotlessApply

agent/agent-tooling/src/main/java/com/microsoft/applicationinsights/agent/internal/quickpulse/QuickPulseDataCollector.java, buildSrc/src/main/kotlin/ai.java-conventions.gradle.kts, buildSrc/src/main/kotlin/ai.smoke-test.gradle.kts
disabling quickpulse option is undocumented, but I noticed when trying to disable it as part of investigating #1822
=> Fix quick pulse disabled option

agent/agent-tooling/src/main/java/com/microsoft/applicationinsights/agent/internal/exporter/Exporter.java
Following guidance: https://github.com/microsoft/common-schema/blob/main/Mappings/AzureMonitor-AI.md#requestresponsecode
=> Update default response code

agent/agent-profiler/agent-profiler-api/src/main/java/com/microsoft/applicationinsights/profiler/config/ServiceProfilerServiceConfig.java, agent/agent-profiler/agent-service-profiler/src/main/java/com/microsoft/applicationinsights/serviceprofilerapi/profiler/JfrProfiler.java, agent/agent-tooling/src/main/java/com/microsoft/applicationinsights/agent/internal/init/AiComponentInstaller.java, agent/agent-tooling/src/test/java/com/microsoft/applicationinsights/agent/internal/profiler/ProfilerServiceTest.java
=> Use tmpdir to store temporary jfr recordings

agent/agent-tooling/src/main/java/com/microsoft/applicationinsights/agent/internal/exporter/Exporter.java, test/smoke/testApps/gRPC/src/smokeTest/java/com/microsoft/applicationinsights/smoketest/GrpcTest.java
Based on https://github.com/microsoft/common-schema/issues/217#issuecomment-893028597
=> Change span events to traces

agent/agent-tooling/src/main/java/com/microsoft/applicationinsights/agent/internal/exporter/Exporter.java
based on https://github.com/microsoft/common-schema/pull/268
cc: @vishweshbankwar
=> Update target mapping

.lgtm.yml, instrumentation/azure-core/azure-core-1.19/javaagent/build.gradle.kts
=> Otel fork updated

agent/agent-tooling/src/main/java/com/microsoft/applicationinsights/agent/internal/init/TempGetAttribute.java
Follow-up from https://github.com/microsoft/ApplicationInsights-Java/pull/1772#discussion_r689773002
=> Use logger instead of printStackTrace

CHANGELOG.md, NOTICE
=> Release 3.2.0-BETA.3

agent/agent-tooling/src/main/java/com/microsoft/applicationinsights/agent/internal/init/TelemetryClientInitializer.java
There will be a follow up pr with perf counters included once we get all the information from app services team.
=> temporary fix for windows app service performance counters issue

agent/agent-tooling/src/main/java/com/microsoft/applicationinsights/agent/internal/exporter/Exporter.java, test/smoke/testApps/Jdbc/src/smokeTest/java/com/microsoft/applicationinsights/smoketestapp/JdbcTest.java, test/smoke/testApps/MongoDB/src/smokeTest/java/com/microsoft/applicationinsights/smoketestapp/MongoTest.java, test/smoke/testApps/TelemetryFiltering/src/smokeTest/java/com/microsoft/applicationinsights/smoketestapp/TelemetryFilteringSmokeTest.java
~Built on top of #1890~ EDIT: no longer as #1890 has been merged to `main`
=> Update db mappings

instrumentation/jms-1.1/javaagent/build.gradle.kts, instrumentation/jms-1.1/javaagent/src/jms2TestReceiveSpansDisabled/groovy/SpringListenerJms2SuppressReceiveSpansTest.groovy, instrumentation/jms-1.1/javaagent/src/main/java/io/opentelemetry/javaagent/instrumentation/jms/JmsSingletons.java, instrumentation/jms-1.1/javaagent/src/test/groovy/SpringListenerJms1SuppressReceiveSpansTest.groovy
suppress JMS receive spans similar to Kafka receive spans
=> otel fork update

agent/agent-tooling/src/main/java/com/microsoft/applicationinsights/agent/internal/exporter/Exporter.java
cc @vishweshbankwar 
attaching CI snapshot for testing: [applicationinsights-agent-3.2.3-BETA-SNAPSHOT.jar.zip](https://github.com/microsoft/ApplicationInsights-Java/files/7479210/applicationinsights-agent-3.2.3-BETA-SNAPSHOT.jar.zip)
=> Fix consumer span exporter mapping

CHANGELOG.md, gradle.properties
will wait for the other 2 PRs to get merged first.
=> Prepare 3.2.3 GA release

agent/agent-tooling/src/main/java/com/microsoft/applicationinsights/agent/internal/localstorage/LocalFileLoader.java, agent/agent-tooling/src/main/java/com/microsoft/applicationinsights/agent/internal/localstorage/LocalFilePurger.java, agent/agent-tooling/src/main/java/com/microsoft/applicationinsights/agent/internal/telemetry/TelemetryChannel.java
Important to log since this is data loss
=> Add logging when purging old telemetry files

agent/agent-tooling/src/main/java/com/microsoft/applicationinsights/agent/internal/telemetry/TelemetryChannel.java, agent/agent-tooling/src/test/java/com/microsoft/applicationinsights/agent/internal/localstorage/IntegrationTests.java
a couple of minor fixes/improvements, nothing too serious
=> TelemetryChannel improvements

agent/agent-tooling/src/main/java/com/microsoft/applicationinsights/agent/internal/exporter/Exporter.java, test/smoke/framework/utils/src/main/java/com/microsoft/applicationinsights/smoketest/schemav2/Envelope.java, test/smoke/testApps/HttpClients/src/smokeTest/java/com/microsoft/applicationinsights/smoketestapp/HttpClientSmokeTest.java
Sample rate 100 is the default, can reduce ingestion cost by not sending it.
=> Don't send sampleRate 100

agent/agent-tooling/src/main/java/com/microsoft/applicationinsights/agent/internal/common/NetworkFriendlyExceptions.java, agent/agent-tooling/src/main/java/com/microsoft/applicationinsights/agent/internal/init/AppIdSupplier.java, agent/agent-tooling/src/main/java/com/microsoft/applicationinsights/agent/internal/quickpulse/QuickPulsePingSender.java, agent/agent-tooling/src/main/java/com/microsoft/applicationinsights/agent/internal/telemetry/TelemetryChannel.java
noticed this while testing with fiddler and I hadn't imported the fiddler cert
=> Reduce cert exception noise

instrumentation/applicationinsights-web-2.3/javaagent/src/main/java/io/opentelemetry/javaagent/instrumentation/applicationinsightsweb/ApplicationInsightsWebInstrumentationModule.java, instrumentation/applicationinsights-web-2.3/javaagent/src/main/java/io/opentelemetry/javaagent/instrumentation/applicationinsightsweb/BaseTelemetryInstrumentation.java, instrumentation/applicationinsights-web-2.3/javaagent/src/main/java/io/opentelemetry/javaagent/instrumentation/applicationinsightsweb/DeviceContextInstrumentation.java, instrumentation/applicationinsights-web-2.3/javaagent/src/main/java/io/opentelemetry/javaagent/instrumentation/applicationinsightsweb/OperationContextInstrumentation.java, instrumentation/applicationinsights-web-2.3/javaagent/src/main/java/io/opentelemetry/javaagent/instrumentation/applicationinsightsweb/RequestTelemetryContextInstrumentation.java, instrumentation/applicationinsights-web-2.3/javaagent/src/main/java/io/opentelemetry/javaagent/instrumentation/applicationinsightsweb/RequestTelemetryInstrumentation.java, instrumentation/applicationinsights-web-2.3/javaagent/src/main/java/io/opentelemetry/javaagent/instrumentation/applicationinsightsweb/SessionContextInstrumentation.java, instrumentation/applicationinsights-web-2.3/javaagent/src/main/java/io/opentelemetry/javaagent/instrumentation/applicationinsightsweb/TelemetryContextInstrumentation.java, instrumentation/applicationinsights-web-2.3/javaagent/src/main/java/io/opentelemetry/javaagent/instrumentation/applicationinsightsweb/UserContextInstrumentation.java, instrumentation/applicationinsights-web-2.3/javaagent/src/test/groovy/ApplicationInsightsWebTest.groovy, instrumentation/applicationinsights-web-2.3/javaagent/src/test/java/Code.java
=> Add support for 2.x DeviceContext setOperatingSystem and setOperatingSystemVersion

instrumentation/applicationinsights-web-2.3/javaagent/src/main/java/io/opentelemetry/javaagent/instrumentation/applicationinsightsweb/DeviceContextInstrumentation.java
=> Fix device instrumentation

agent/agent-tooling/src/main/java/com/microsoft/applicationinsights/agent/internal/exporter/Exporter.java, agent/agent-tooling/src/main/java/com/microsoft/applicationinsights/agent/internal/exporter/models/ContextTagKeys.java, test/smoke/testApps/LegacySdkWebInterop/src/main/java/com/microsoft/applicationinsights/smoketestapp/TestController.java, test/smoke/testApps/LegacySdkWebInterop/src/smokeTest/java/com/microsoft/applicationinsights/smoketest/LegacySdkWebInteropTest.java
=> Add smoke test for ai.device.os and ai.device.osVersion

agent/agent-tooling/src/main/java/com/microsoft/applicationinsights/agent/internal/configuration/Configuration.java, agent/agent-tooling/src/main/java/com/microsoft/applicationinsights/agent/internal/init/AiComponentInstaller.java, agent/agent-tooling/src/main/java/com/microsoft/applicationinsights/agent/internal/telemetry/BatchSpanProcessor.java, agent/agent-tooling/src/main/java/com/microsoft/applicationinsights/agent/internal/telemetry/TelemetryClient.java
=> Add configuration for export queue capacity

agent/agent-tooling/src/main/java/com/microsoft/applicationinsights/agent/internal/statsbeat/Instrumentations.java, agent/instrumentation/build.gradle.kts, agent/instrumentation/gradle.lockfile
=> Add vertx instrumentation

agent/agent-tooling/src/main/java/com/microsoft/applicationinsights/agent/internal/common/TelemetryTruncation.java, test/smoke/appServers/Wildfly.11/wildfly11.linux.partial.dockerfile, test/smoke/framework/testCore/src/main/java/com/microsoft/applicationinsights/smoketest/AiSmokeTest.java
=> Fix truncation log spamming

agent/agent-tooling/src/main/java/com/microsoft/applicationinsights/agent/internal/telemetry/TelemetryChannel.java
Provided a clear message when breeze responds with 401 or 403 status codes
Sample:
Sending telemetry to the ingestion service: Authentication required. Please provide Azure Active Directory credentials (telemetry will be stored to disk and retried later) (future warnings will be aggregated and logged once every 5 minutes)
=> Handle 401 and 403 responses from Breeze

agent/agent-tooling/src/main/java/com/microsoft/applicationinsights/agent/internal/exporter/Exporter.java
Minor updates to sync code with azure-monitor-opentelemetry-exporter
=> Minor Exporter updates

agent/agent-tooling/src/main/java/com/microsoft/applicationinsights/agent/internal/configuration/Configuration.java, agent/agent-tooling/src/main/java/com/microsoft/applicationinsights/agent/internal/telemetry/ConnectionString.java, agent/agent-tooling/src/main/java/com/microsoft/applicationinsights/agent/internal/telemetry/StatsbeatConnectionString.java, agent/agent-tooling/src/test/java/com/microsoft/applicationinsights/agent/internal/telemetry/StatsbeatConnectionStringTest.java
azure doc draft
https://github.com/MicrosoftDocs/azure-docs-pr/pull/187423
spec: https://microsoft.sharepoint.com/:w:/t/OneDSJavascript/EYRX-qyTul5CvaXYOwNhVAoBVIIUWun4FFoRXklRAtseiA?e=fZZMpa
=> Support Statsbeat in EU regions

agent/agent-tooling/src/main/java/com/microsoft/applicationinsights/agent/internal/telemetry/ConnectionString.java
this is now logged all the time since #2082
=> Remove incorrect warning

gradle.properties
=> Merge main into vnext

agent/agent-tooling/src/main/java/com/microsoft/applicationinsights/agent/internal/perfcounter/OshiPerformanceCounter.java, agent/agent-tooling/src/main/java/com/microsoft/applicationinsights/agent/internal/telemetry/TelemetryClient.java, agent/agent/src/main/java/com/microsoft/applicationinsights/agent/StartupProfiler.java
Remember to merge not squash this.
=> Merge main into vnext branch

.github/workflows/ci.yml, .github/workflows/nightly.yml, .github/workflows/pr.yml, .github/workflows/release-gradle-plugins.yml, instrumentation/build.gradle.kts, instrumentation/micrometer-1.0/javaagent/src/main/java/io/opentelemetry/javaagent/instrumentation/micrometer/AzureMonitorAutoConfiguration.java
includes micrometer fix which is also going into 3.2.x (#2146)
=> update vnext otel fork

agent/agent-tooling/build.gradle.kts, agent/agent-tooling/src/main/java/com/microsoft/applicationinsights/agent/internal/configuration/Configuration.java, agent/agent-tooling/src/main/java/com/microsoft/applicationinsights/agent/internal/init/AiComponentInstaller.java, agent/agent-tooling/src/main/java/com/microsoft/applicationinsights/agent/internal/init/LazyConfigurationAccessor.java, agent/agent-tooling/src/main/java/com/microsoft/applicationinsights/agent/internal/init/OpenTelemetryConfigurer.java, agent/agent-tooling/src/main/java/com/microsoft/applicationinsights/agent/internal/legacyheaders/DelegatingPropagator.java
Resolves #1883
```
{
"preview": {
"additionalPropagators": [
"b3multi"
]
}
}
```
attaching CI snapshot for testing: [applicationinsights-agent-3.2.3-BETA-SNAPSHOT.jar.zip](https://github.com/microsoft/ApplicationInsights-Java/files/7471986/applicationinsights-agent-3.2.3-BETA-SNAPSHOT.jar.zip)
=> Support b3multi propagation

agent/agent-tooling/src/main/java/com/microsoft/applicationinsights/agent/internal/common/NetworkFriendlyExceptions.java, agent/agent-tooling/src/main/java/com/microsoft/applicationinsights/agent/internal/init/MainEntryPoint.java
got another of these cases, and this would have been helpful
then we should update https://docs.microsoft.com/en-us/azure/azure-monitor/app/java-standalone-troubleshoot#how-to-determine-client-side-cipher-suites
=> Log found cipher suites

agent/agent-tooling/src/main/java/com/microsoft/applicationinsights/agent/internal/configuration/Configuration.java, agent/agent-tooling/src/main/java/com/microsoft/applicationinsights/agent/internal/legacyheaders/DelegatingPropagator.java
Resolves #2162
requires doc update
=> Support b3 (single)

agent/agent-tooling/src/main/java/com/microsoft/applicationinsights/agent/internal/configuration/Configuration.java, agent/agent-tooling/src/main/java/com/microsoft/applicationinsights/agent/internal/init/InheritedRoleNameSpanProcessor.java, agent/agent-tooling/src/main/java/com/microsoft/applicationinsights/agent/internal/init/OpenTelemetryConfigurer.java, test/smoke/appServers/global-resources/telemetryfiltering_applicationinsights.json, test/smoke/testApps/TelemetryFiltering/src/smokeTest/java/com/microsoft/applicationinsights/smoketestapp/TelemetryFilteringSmokeTest.java
Resolves #2133
requires doc update
=> Add role name overrides

agent/agent-profiler/agent-service-profiler/src/main/java/com/microsoft/applicationinsights/serviceprofilerapi/client/ProfilerFrontendClientV2.java, agent/agent-tooling/src/main/java/com/azure/monitor/opentelemetry/exporter/implementation/quickpulse/QuickPulseDataSender.java, agent/agent-tooling/src/main/java/com/azure/monitor/opentelemetry/exporter/implementation/quickpulse/QuickPulsePingSender.java, agent/agent-tooling/src/main/java/com/microsoft/applicationinsights/agent/internal/httpclient/LazyHttpClient.java
The underlying bug was fixed in azure sdk.
=> Remove http response draining

agent/agent-tooling/src/main/java/com/microsoft/applicationinsights/agent/internal/init/OpenTelemetryConfigurer.java
the configured value is already set above
=> Fix bsp delay

agent/agent-tooling/src/main/java/com/microsoft/applicationinsights/agent/internal/exporter/Exceptions.java, agent/agent-tooling/src/test/java/com/microsoft/applicationinsights/agent/internal/exporter/ExceptionsTest.java
=> Fix exception parsing

agent/agent-tooling/src/main/java/com/microsoft/applicationinsights/agent/internal/telemetry/BatchSpanProcessor.java
Resolves issue reported in https://github.com/microsoft/ApplicationInsights-Java/issues/2129#issuecomment-1079116110
=> Fix statsbeat warning

agent/agent-tooling/src/main/java/com/microsoft/applicationinsights/agent/internal/telemetry/TelemetryChannel.java
https://portal.microsofticm.com/imp/v3/incidents/details/294321451/home
=> Add Exception for AMPL

agent/agent-tooling/src/main/java/com/azure/monitor/opentelemetry/exporter/LiveMetricsSpanProcessor.java, agent/agent-tooling/src/main/java/com/azure/monitor/opentelemetry/exporter/implementation/quickpulse/QuickPulse.java, agent/agent-tooling/src/main/java/com/azure/monitor/opentelemetry/exporter/implementation/quickpulse/QuickPulseDataCollector.java, agent/agent-tooling/src/main/java/com/azure/monitor/opentelemetry/exporter/implementation/utils/CpuPerformanceCounterCalculator.java, agent/agent-tooling/src/main/java/com/microsoft/applicationinsights/agent/internal/configuration/Configuration.java, agent/agent-tooling/src/main/java/com/microsoft/applicationinsights/agent/internal/init/TelemetryClientInitializer.java, agent/agent-tooling/src/main/java/com/microsoft/applicationinsights/agent/internal/perfcounter/MetricNames.java, agent/agent-tooling/src/main/java/com/microsoft/applicationinsights/agent/internal/perfcounter/OshiPerformanceCounter.java, agent/agent-tooling/src/main/java/com/microsoft/applicationinsights/agent/internal/perfcounter/ProcessCpuPerformanceCounter.java, agent/agent-tooling/src/main/java/com/microsoft/applicationinsights/agent/internal/profiler/AlertingServiceFactory.java, agent/agent-tooling/src/main/java/com/microsoft/applicationinsights/agent/internal/telemetry/TelemetryClient.java, agent/agent-tooling/src/test/java/com/azure/monitor/opentelemetry/exporter/implementation/quickpulse/QuickPulseCoordinatorTest.java, agent/agent-tooling/src/test/java/com/azure/monitor/opentelemetry/exporter/implementation/quickpulse/QuickPulseDataCollectorTests.java, agent/agent-tooling/src/test/java/com/azure/monitor/opentelemetry/exporter/implementation/quickpulse/QuickPulseDataFetcherTests.java, agent/agent-tooling/src/test/java/com/azure/monitor/opentelemetry/exporter/implementation/quickpulse/QuickPulseIntegrationTests.java, agent/agent-tooling/src/test/java/com/microsoft/applicationinsights/agent/internal/profiler/ProfilerServiceTest.java, test/smoke/testApps/AutoPerfCounters/src/smokeTest/java/com/microsoft/applicationinsights/smoketest/PerfCountersDataTest.java
~currently built on top of #2176, will rebase once that is merged~
~One outstanding question about whether we should apply the config option to system cpu percentage also.~
requires doc update
=> Add process cpu normalized

agent/agent-tooling/src/main/java/com/microsoft/applicationinsights/agent/internal/exporter/LoggerExporter.java
@rajkumar-rangaraj @vishweshbankwar is there already a standard way of handling empty messages in Application Insights .NET SDK?
=> Add default log message

agent/agent-tooling/src/main/java/com/microsoft/applicationinsights/agent/internal/statsbeat/AzureMetadataService.java
this log is unnecessary at the default INFO level
=> Reduce logging level

instrumentation/jboss-logmanager-mdc-1.1/javaagent/build.gradle.kts, instrumentation/jboss-logmanager-mdc-1.1/javaagent/src/main/java/io/opentelemetry/javaagent/instrumentation/jbosslogmanager/v1_1/JbossExtLogRecordInstrumentation.java, instrumentation/jboss-logmanager-mdc-1.1/javaagent/src/main/java/io/opentelemetry/javaagent/instrumentation/jbosslogmanager/v1_1/JbossLoggerInstrumentation.java, instrumentation/jboss-logmanager-mdc-1.1/javaagent/src/main/java/io/opentelemetry/javaagent/instrumentation/jbosslogmanager/v1_1/JbossLogmanagerInstrumentationModule.java, instrumentation/jboss-logmanager-mdc-1.1/javaagent/src/test/groovy/JbossLogmanagerMdcTest.groovy
somehow lost jboss mdc instrumentation in the last update 🤔
=> [vnext] otel fork updated

agent/agent-tooling/src/main/java/com/microsoft/applicationinsights/agent/internal/init/AiConfigPropertySource.java
=> Fix warning message

agent/agent-tooling/src/main/java/com/microsoft/applicationinsights/agent/internal/exporter/Exporter.java
=> Update azure sdk messaging mappings

.github/workflows/pr.yaml
got the idea from https://github.com/gradle/gradle-build-action/issues/115
=> Remove github action cache

agent/agent-tooling/src/main/java/com/microsoft/applicationinsights/agent/internal/init/LoggingLevelConfigurator.java
=> Stop DeltaMetricStorage warning messages

agent/agent-tooling/src/main/java/com/microsoft/applicationinsights/agent/internal/configuration/Configuration.java, agent/agent-tooling/src/main/java/com/microsoft/applicationinsights/agent/internal/sampling/SamplingOverrides.java, agent/agent-tooling/src/test/java/com/microsoft/applicationinsights/agent/internal/init/InheritedAttributesSpanProcessorTest.java, smoke-tests/apps/HttpHeaders/src/main/java/com/microsoft/applicationinsights/smoketestapp/TestController.java, smoke-tests/servers/global-resources/httpheaders_applicationinsights.json
=> Support sampling overrides on http request headers

agent/azure-monitor-exporter/src/main/java/com/azure/monitor/opentelemetry/exporter/implementation/LogDataMapper.java, agent/azure-monitor-exporter/src/main/java/com/azure/monitor/opentelemetry/exporter/implementation/SpanDataMapper.java
and small refactoring in LogDataMapper for more consistency with SpanDataMapper
(not for 3.3.0-BETA.2)
=> Capture custom attributes on exceptions

agent/azure-monitor-exporter/src/main/java/com/azure/monitor/opentelemetry/exporter/implementation/logging/NetworkFriendlyExceptions.java, agent/azure-monitor-exporter/src/test/java/com/azure/monitor/opentelemetry/exporter/implementation/logging/NetworkFriendlyExceptionsTest.java
=> Avoid incorrect SSL cert warnings

agent/agent-tooling/build.gradle.kts, agent/agent-tooling/src/main/java/com/microsoft/applicationinsights/agent/internal/statsbeat/NetworkStatsbeat.java, agent/agent-tooling/src/main/java/com/microsoft/applicationinsights/agent/internal/statsbeat/NetworkStatsbeatHttpPipelinePolicy.java, agent/agent-tooling/src/main/java/com/microsoft/applicationinsights/agent/internal/utils/Constant.java, agent/agent-tooling/src/test/java/com/microsoft/applicationinsights/agent/internal/statsbeat/NetworkStatsbeatTest.java, agent/azure-monitor-exporter/src/main/java/com/azure/monitor/opentelemetry/exporter/implementation/utils/StatusCodes.java
spec https://github.com/microsoft/Telemetry-Collection-Spec/pull/61
=> Track statusCode and exceptionType via Statsbeat

.github/workflows/ci.yaml, .github/workflows/pr.yaml
Based on https://github.com/microsoft/ApplicationInsights-Java/pull/2335#pullrequestreview-1014217300
=> Simplify GitHub actions

agent/agent/build.gradle.kts, agent/runtime-attach/build.gradle.kts, agent/runtime-attach/gradle.lockfile, buildSrc/src/main/kotlin/ai.publish-conventions.gradle.kts, smoke-tests/servers/build.gradle
This is step 1. Step 2 is to update the release scripts.
=> Publish runtime-attach artifact

CHANGELOG.md, gradle.properties
azure doc update: https://github.com/MicrosoftDocs/azure-docs-pr/pull/202374
=> Prepare for 3.3.0 GA release

agent/agent-tooling/src/main/java/com/microsoft/applicationinsights/agent/internal/exporter/AgentLogExporter.java, agent/agent-tooling/src/main/java/com/microsoft/applicationinsights/agent/internal/exporter/AgentMetricExporter.java, agent/agent-tooling/src/main/java/com/microsoft/applicationinsights/agent/internal/exporter/AgentSpanExporter.java, agent/agent-tooling/src/main/java/com/microsoft/applicationinsights/agent/internal/init/LazyConfigurationAccessor.java, agent/agent-tooling/src/test/java/com/microsoft/applicationinsights/agent/internal/init/LazyConfigurationAccessorTest.java
=> Clean up Azure Functions consumption plan code

buildSrc/src/main/kotlin/ai.errorprone-conventions.gradle.kts
syncing with upstream
(hide whitespace for easier to review diff)
after this, you can suppress error prone locally by creating ~/.gradle/gradle.properties file with
```
disableErrorProne=true
```
=> Fix disableErrorProne setting

.github/workflows/ci.yaml
e.g. for re-testing with cache
=> Allow to manually run CI build

.github/CODEOWNERS
@johnoliver with your approval of course, to make sure that you are automatically notified and included as a reviewer for the profiler components
=> Add johnoliver to CODEOWNERS

agent/agent-tooling/src/main/java/com/microsoft/applicationinsights/agent/internal/init/AiConfigCustomizer.java, agent/azure-monitor-exporter/src/main/java/com/azure/monitor/opentelemetry/exporter/implementation/LogDataMapper.java, smoke-tests/apps/TraceLogBack/src/smokeTest/java/com/microsoft/applicationinsights/smoketest/TraceLogBackTest.java, smoke-tests/apps/TraceLogBackUsingAgent/src/smokeTest/java/com/microsoft/applicationinsights/smoketest/TraceLogBackTest.java
=> Capture MDC attributes for jboss-logging

agent/agent-profiler/docs/README.md, agent/agent-tooling/src/main/java/com/microsoft/applicationinsights/agent/internal/configuration/Configuration.java, agent/agent-tooling/src/main/java/com/microsoft/applicationinsights/agent/internal/init/ProfilingInitializer.java
=> Change default profile to the reduced profile. Update profiler documentation

agent/agent-tooling/src/main/java/com/microsoft/applicationinsights/agent/internal/init/AiConfigCustomizer.java, agent/agent-tooling/src/main/java/com/microsoft/applicationinsights/agent/internal/statsbeat/Instrumentations.java
=> Add Spring JMS instrumentation

README.md
I think enough time has passed now
=> Remove log4j notice on README

agent/agent-tooling/src/main/java/com/microsoft/applicationinsights/agent/internal/legacysdk/BytecodeUtilImpl.java, agent/azure-monitor-exporter/src/main/java/com/azure/monitor/opentelemetry/exporter/implementation/LogDataMapper.java, agent/azure-monitor-exporter/src/main/java/com/azure/monitor/opentelemetry/exporter/implementation/builders/MessageTelemetryBuilder.java
=> Fix missing message data

agent/agent/src/main/java/com/microsoft/applicationinsights/agent/Agent.java
Improve agent already loaded check
=> Improve agent already loaded check

agent/agent-profiler/agent-service-profiler/src/main/java/com/microsoft/applicationinsights/serviceprofilerapi/profiler/JfrProfiler.java
=> Ensure that profile is shutdown

agent/agent-tooling/src/main/java/com/microsoft/applicationinsights/agent/internal/configuration/Configuration.java
=> Fix incorrect default trigger cooldown

LICENSE, agent/agent/build.gradle.kts, smoke-tests/apps/VerifyShading/src/main/java/com/microsoft/applicationinsights/smoketestapp/TestController.java
I shouldn't have removed it recently in #2427
=> Fix license file

agent/azure-monitor-exporter/src/main/java/com/azure/monitor/opentelemetry/exporter/implementation/LogDataMapper.java, smoke-tests/apps/NonDaemonThreads/src/smokeTest/java/com/microsoft/applicationinsights/smoketest/NonDaemonThreadsTest.java, smoke-tests/framework/src/main/java/com/microsoft/applicationinsights/smoketest/SmokeTestExtension.java
=> Fix 0000... for non-parented log records

smoke-tests/apps/Micrometer/src/smokeTest/java/com/microsoft/applicationinsights/smoketest/MicrometerDisabledTest.java, smoke-tests/apps/Micrometer/src/smokeTest/java/com/microsoft/applicationinsights/smoketest/MicrometerTest.java
=> Fix sporadically failing smoke test

agent/agent-tooling/src/main/java/com/microsoft/applicationinsights/agent/internal/init/SecondEntryPoint.java, agent/agent-tooling/src/main/java/com/microsoft/applicationinsights/agent/internal/profiler/triggers/AlertTriggerSpanProcessor.java, agent/agent-tooling/src/test/java/com/microsoft/applicationinsights/agent/internal/profiler/AlertTriggerSpanProcessorTest.java, agent/azure-monitor-exporter/src/main/java/com/azure/monitor/opentelemetry/exporter/implementation/SpanDataMapper.java
this has the benefit of working even with OTLP exporter
=> Update alerts to SpanProcessor

agent/agent-profiler/agent-profiler-api/src/main/java/com/microsoft/applicationinsights/profiler/config/ServiceProfilerServiceConfig.java, agent/agent-profiler/agent-service-profiler/src/main/java/com/microsoft/applicationinsights/serviceprofilerapi/profiler/AlternativeJfrConfigurations.java, agent/agent-profiler/agent-service-profiler/src/main/java/com/microsoft/applicationinsights/serviceprofilerapi/profiler/JfrProfiler.java, agent/agent-tooling/src/main/java/com/microsoft/applicationinsights/agent/internal/configuration/Configuration.java, agent/agent-tooling/src/main/java/com/microsoft/applicationinsights/agent/internal/init/ProfilingInitializer.java, agent/agent-tooling/src/test/java/com/microsoft/applicationinsights/agent/internal/profiler/ProfilerServiceTest.java
=> Cause manual trigger to execute the same profile as a cpu trigger

agent/agent-profiler/agent-profiler-api/src/main/java/com/microsoft/applicationinsights/profiler/Profiler.java, agent/agent-profiler/agent-service-profiler/src/main/java/com/microsoft/applicationinsights/serviceprofilerapi/JfrProfilerService.java, agent/agent-profiler/agent-service-profiler/src/main/java/com/microsoft/applicationinsights/serviceprofilerapi/profiler/JfrProfiler.java
Noticed this could be simplified while reviewing #2457
=> Simplify profiler init exception handling

agent/agent-tooling/src/main/java/com/microsoft/applicationinsights/agent/internal/configuration/ConfigurationBuilder.java
and consolidates some logic between file config parsing and env var / runtime attach config parsing
=> Better configuration debug logging

agent/agent-tooling/src/main/java/com/microsoft/applicationinsights/agent/internal/configuration/ConfigurationBuilder.java
Disable profiler-related features for OpenJ9 JVM
=> Disable profiler-related features for OpenJ9 JVM

agent/agent-bootstrap/src/main/java/io/opentelemetry/instrumentation/api/instrumenter/BootstrapSemanticAttributes.java, agent/agent-bootstrap/src/main/java/io/opentelemetry/instrumentation/api/instrumenter/http/HttpClientMetrics.java, agent/agent-bootstrap/src/main/java/io/opentelemetry/instrumentation/api/instrumenter/rpc/RpcClientMetrics.java, agent/azure-monitor-exporter/src/main/java/com/azure/monitor/opentelemetry/exporter/implementation/MetricDataMapper.java, agent/azure-monitor-exporter/src/main/java/com/azure/monitor/opentelemetry/exporter/implementation/SpanDataMapper.java, agent/azure-monitor-exporter/src/test/java/com/azure/monitor/opentelemetry/exporter/PreAggregatedMetricsTest.java, smoke-tests/apps/Jdbc/src/smokeTest/java/com/microsoft/applicationinsights/smoketest/JdbcTest.java, smoke-tests/apps/Jdbc/src/smokeTest/java/com/microsoft/applicationinsights/smoketest/JdbcUnmaskedTest.java, smoke-tests/apps/TelemetryFiltering/src/smokeTest/java/com/microsoft/applicationinsights/smoketest/TelemetryFilteringSmokeTest.java
@heyams I think some recent changes in otel specification / java instrumentation allow us to simplify this
=> Calculate target using existing otel metric attributes

agent/azure-monitor-exporter/src/main/java/com/azure/monitor/opentelemetry/exporter/implementation/logging/DiagnosticTelemetryPipelineListener.java
=> Suppress ingestion sampling warnings

agent/agent-tooling/src/main/java/com/microsoft/applicationinsights/agent/internal/configuration/ConfigurationBuilder.java, agent/agent-tooling/src/test/java/com/microsoft/applicationinsights/agent/internal/configuration/ConfigurationBuilderTest.java, agent/agent-tooling/src/test/resources/applicationinsights_with_utf8_bom.json
This was a regression in 3.4.0-BETA.
=> Fix config parsing

.github/dependabot.yml, dependencyManagement/build.gradle.kts
Trying out alternative approach, of explicitly suppressing versions in the dependabot configuration
=> Dependabot suppression

.github/workflows/owasp-dependency-check-daily.yml, buildSrc/build.gradle.kts, buildSrc/src/main/kotlin/ai.java-conventions.gradle.kts
(note, this is duplicative of internal component governance reports, but I think that's ok)
currently built on top of #2614
=> Run owasp daily check

buildSrc/build.gradle.kts
This will be easier than merging/rebasing all of the dependabot PRs.
Dependabot should close those other PRs automatically after this is merged.
=> Update buildSrc dependencies

agent/agent-tooling/src/main/java/com/microsoft/applicationinsights/agent/internal/configuration/Configuration.java
~waiting for Function team to confirm~ confirmed
=> Use the same dir as app service

agent/agent-tooling/src/main/java/com/microsoft/applicationinsights/agent/internal/statsbeat/StatsbeatModule.java, agent/agent-tooling/src/main/java/com/microsoft/applicationinsights/agent/internal/telemetry/TelemetryClient.java, agent/azure-monitor-exporter/src/main/java/com/azure/monitor/opentelemetry/exporter/implementation/configuration/StatsbeatConnectionString.java
https://github.com/aep-health-and-standards/Telemetry-Collection-Spec/pull/113
=> Harcode non-EU regions

CHANGELOG.md, gradle.properties
i will automate release note and version update next week. @trask
=> Release 3.4.3

agent/agent-tooling/src/main/java/com/microsoft/applicationinsights/agent/internal/init/AiConfigCustomizer.java
This helps with context propagation issues when using akka or play instrumentation.
=> Add scala instrumentation

CHANGELOG.md
use "rich diff" option to get less diff noise in this case
=> More change log formatting

buildSrc/build.gradle.kts
(this was copied over from otel where they are needed for building the muzzle plugin)
=> Remove unused buildSrc dependencies

agent/azure-monitor-exporter/src/main/java/com/azure/monitor/opentelemetry/exporter/implementation/logging/NetworkFriendlyExceptions.java
GET endpoint:  ../api/profiles/../appId
=> Display only the import certificate message for the GET endpoint

.github/dependabot.yml
also removing the ignore on otel updates as we discussed previously
=> Add dependabot ignores

.github/workflows/comment-driven-automation.yml, build.gradle.kts, buildSrc/src/main/kotlin/ai.java-conventions.gradle.kts
to align with naming in docs: https://docs.gradle.org/current/userguide/dependency_locking.html#lock_all_configurations_in_one_build_execution
also, fixed an issue I was having when regenerating the lock files by moving it to java-conventions
=> Update gradle locking

agent/agent-tooling/src/main/java/com/microsoft/applicationinsights/agent/internal/configuration/ConfigurationBuilder.java, agent/agent-tooling/src/main/java/com/microsoft/applicationinsights/agent/internal/init/AfterAgentListener.java, agent/agent-tooling/src/main/java/com/microsoft/applicationinsights/agent/internal/init/SecondEntryPoint.java, agent/azure-monitor-exporter/src/main/java/com/azure/monitor/opentelemetry/exporter/AzureMonitorExporterBuilder.java, agent/azure-monitor-exporter/src/main/java/com/azure/monitor/opentelemetry/exporter/implementation/LogDataMapper.java, agent/azure-monitor-exporter/src/main/java/com/azure/monitor/opentelemetry/exporter/implementation/SpanDataMapper.java, agent/azure-monitor-exporter/src/main/java/com/azure/monitor/opentelemetry/exporter/implementation/logging/AggregatingLogger.java, agent/azure-monitor-exporter/src/main/java/com/azure/monitor/opentelemetry/exporter/implementation/logging/NetworkFriendlyExceptions.java, agent/azure-monitor-exporter/src/main/java/com/azure/monitor/opentelemetry/exporter/implementation/pipeline/TelemetryItemExporter.java, agent/azure-monitor-exporter/src/test/java/com/azure/monitor/opentelemetry/exporter/AppConfigurationExporterIntegrationTest.java, agent/azure-monitor-exporter/src/test/java/com/azure/monitor/opentelemetry/exporter/AzureMonitorExportersEndToEndTest.java, agent/azure-monitor-exporter/src/test/java/com/azure/monitor/opentelemetry/exporter/AzureMonitorMetricExporterTest.java, agent/azure-monitor-exporter/src/test/java/com/azure/monitor/opentelemetry/exporter/EventHubsExporterIntegrationTest.java, agent/azure-monitor-exporter/src/test/java/com/azure/monitor/opentelemetry/exporter/MonitorExporterClientTestBase.java, agent/azure-monitor-exporter/src/test/java/com/azure/monitor/opentelemetry/exporter/implementation/localstorage/IntegrationTests.java, agent/azure-monitor-exporter/src/test/java/com/azure/monitor/opentelemetry/exporter/implementation/utils/TestUtils.java, agent/azure-monitor-exporter/src/test/resources/session-records/quickPulsePingAndPostPlayback.json, agent/azure-monitor-exporter/src/test/resources/session-records/quickPulsePingPlayback.json, agent/azure-monitor-exporter/src/test/resources/session-records/regularTelemetryPlayback.json
(note for reviewing, the json file diffs are much easier with hiding whitespace)
=> Syncing changes back from azure-monitor-opentelemetry-exporter

smoke-tests/apps/JavaUtilLogging/src/smokeTest/java/com/microsoft/applicationinsights/smoketest/JavaUtilLoggingTest.java, smoke-tests/apps/Log4j2/src/main/java/com/microsoft/applicationinsights/smoketestapp/Log4j2Servlet.java, smoke-tests/apps/Log4j2/src/smokeTest/java/com/microsoft/applicationinsights/smoketest/Log4j2Test.java
(currently baselined to #2792)
=> Add Log4j MapMessage smoke test

agent/agent-tooling/src/main/java/com/microsoft/applicationinsights/agent/internal/init/RpConfigurationPolling.java, agent/azure-monitor-exporter/src/main/java/com/azure/monitor/opentelemetry/exporter/implementation/quickpulse/QuickPulse.java
=> Fix flaky test

agent/agent-tooling/src/main/java/com/microsoft/applicationinsights/agent/internal/profiler/ProfilingInitializer.java, agent/agent-tooling/src/main/java/com/microsoft/applicationinsights/agent/internal/profiler/util/ServiceLoaderUtil.java
=> Allow service loader util to detect services provided by an extension

etw/native/build.gradle
=> Revert etw dll control flow guard change

agent/agent-tooling/src/main/java/com/microsoft/applicationinsights/agent/internal/configuration/Configuration.java, agent/agent-tooling/src/main/java/com/microsoft/applicationinsights/agent/internal/configuration/ConfigurationBuilder.java, agent/agent-tooling/src/main/java/com/microsoft/applicationinsights/agent/internal/init/AiConfigCustomizer.java, agent/agent-tooling/src/main/java/com/microsoft/applicationinsights/agent/internal/init/PerformanceCounterInitializer.java, agent/agent-tooling/src/main/java/com/microsoft/applicationinsights/agent/internal/init/SecondEntryPoint.java, smoke-tests/apps/ActuatorMetrics/src/smokeTest/resources/applicationinsights.json, smoke-tests/apps/ActuatorMetrics/src/smokeTest/resources/disabled_applicationinsights.json, smoke-tests/apps/AutoPerfCounters/src/smokeTest/resources/applicationinsights.json, smoke-tests/apps/Micrometer/src/smokeTest/resources/applicationinsights.json, smoke-tests/apps/Micrometer/src/smokeTest/resources/disabled_applicationinsights.json
=> GA metricIntervalSeconds config

agent/agent-tooling/src/main/java/com/microsoft/applicationinsights/agent/internal/profiler/service/ServiceProfilerClient.java, agent/agent-tooling/src/test/resources/session-records/UploadServiceTest.uploadFileGoodPathReturnsExpectedResponse.json
=> Remove unnecessary quotes from upload etag

.github/dependabot.yml
=> Revert dependabot ignoring spring-boot-gradle-plugin dependency update

.github/workflows/comment-driven-automation.yml
=> Revert "Improve command-driven GitHub Actions automation (#2884)"

agent/azure-monitor-exporter/src/main/java/com/azure/monitor/opentelemetry/exporter/implementation/SpanDataMapper.java
https://1dsdocs.azurewebsites.net/schema/Mappings/AzureMonitor-AI.html#remotedependencyresultcode
=> Set resultCode to zero when Span.httpStatusCode is not present

agent/agent-tooling/src/main/java/com/microsoft/applicationinsights/agent/internal/profiler/PerformanceMonitoringService.java
=> Use the correct enable flag for enabling diagnostics

agent/agent-profiler/request-triggers.md
=> add request trigger documentation

agent/agent-tooling/src/main/java/com/microsoft/applicationinsights/agent/internal/profiler/service/ServiceProfilerClient.java
=> Add additional error message to HttpResponseException

agent/agent-bootstrap/src/main/java/com/microsoft/applicationinsights/agent/bootstrap/BytecodeUtil.java, agent/agent-bootstrap/src/main/java/com/microsoft/applicationinsights/agent/bootstrap/MicrometerUtil.java, agent/agent-tooling/src/main/java/com/microsoft/applicationinsights/agent/internal/configuration/Configuration.java, agent/agent-tooling/src/main/java/com/microsoft/applicationinsights/agent/internal/init/AiConfigCustomizer.java, agent/instrumentation/micrometer-1.0/src/main/java/io/opentelemetry/javaagent/instrumentation/micrometer/ai/AzureMonitorMeterRegistry.java, agent/instrumentation/micrometer-1.0/src/main/java/io/opentelemetry/javaagent/instrumentation/micrometer/ai/AzureMonitorRegistryConfig.java, agent/instrumentation/micrometer-1.0/src/test/java/AgentTestingMicrometerDelegate.java, agent/instrumentation/micrometer-1.0/src/test/java/MicrometerTest.java, smoke-tests/apps/Micrometer/src/smokeTest/java/com/microsoft/applicationinsights/smoketest/MicrometerNamespaceTest.java, smoke-tests/apps/Micrometer/src/smokeTest/java/com/microsoft/applicationinsights/smoketest/MicrometerTest.java, smoke-tests/apps/Micrometer/src/smokeTest/resources/namespace_applicationinsights.json
=> Make Micrometer Namespace Configurable

.github/workflows/reusable-scheduled-job-notification.yml
Fixes #3054 (which shouldn't have been created since OWASP check succeeded)
=> Fix workflow

agent/azure-monitor-exporter/src/main/java/com/azure/monitor/opentelemetry/exporter/implementation/heartbeat/DefaultHeartBeatPropertyProvider.java, agent/azure-monitor-exporter/src/main/java/com/azure/monitor/opentelemetry/exporter/implementation/heartbeat/HeartBeatPayloadProviderInterface.java, agent/azure-monitor-exporter/src/main/java/com/azure/monitor/opentelemetry/exporter/implementation/heartbeat/WebAppsHeartbeatProvider.java
I think(?) this is what it's complaining about: https://github.com/microsoft/ApplicationInsights-Java/actions/runs/4918955360/jobs/8785954492
=> Fix CodeQL failure

.github/workflows/codeql-daily.yml, .github/workflows/owasp-dependency-check-daily.yml
=> Revert "Simplify workflow script (#3059)"

agent/agent-tooling/src/main/java/com/microsoft/applicationinsights/agent/internal/configuration/Configuration.java, agent/agent-tooling/src/main/java/com/microsoft/applicationinsights/agent/internal/configuration/SnippetConfiguration.java, agent/agent-tooling/src/main/java/com/microsoft/applicationinsights/agent/internal/init/RuntimeConfigurator.java, agent/agent-tooling/src/main/java/com/microsoft/applicationinsights/agent/internal/init/SecondEntryPoint.java, agent/agent-tooling/src/test/java/com/microsoft/applicationinsights/agent/internal/configuration/SnippetConfigurationTest.java
Fix 1. remove static for snippetInjection 2. change the way of readfile 3. enable snippet injection with initial connectionString
=> Fix Snippet Injection

smoke-tests/apps/Diagnostics/JfrFileReader/src/main/java/com/microsoft/applicationinsights/jfrfile/JfrFileReader.java, smoke-tests/apps/Diagnostics/src/main/java/com/microsoft/applicationinsights/smoketestapp/TestController.java
=> Try to fix sporadically failing diagnostics smoke test

smoke-tests/apps/SnippetInjection/src/smokeTest/java/com/microsoft/applicationinsights/smoketest/SnippetInjectionTest.java
(also removed debug setting while in the file)
=> Fix merge conflict

smoke-tests/apps/Diagnostics/src/main/java/com/microsoft/applicationinsights/smoketestapp/TestController.java
=> Attempt to fix unreliable diagnostics tests

agent/agent-tooling/src/main/java/com/microsoft/applicationinsights/agent/internal/init/TimestampingLogRecordProcessor.java
Probably this code will be deleted before next release anyways, but just in case it's helpful in the meanwhile...
=> Better toString()

agent/agent/build.gradle.kts, licenses/more-licenses.md
=> Remove no longer needed version pin

agent/agent-tooling/src/main/java/com/microsoft/applicationinsights/agent/internal/configuration/Configuration.java, agent/agent-tooling/src/test/java/com/microsoft/applicationinsights/agent/internal/processors/TelemetryProcessorMaskingTest.java, agent/agent-tooling/src/test/java/com/microsoft/applicationinsights/agent/internal/processors/TelemetryProcessorMaskingValidationTest.java, smoke-tests/apps/TelemetryProcessors/src/main/java/com/microsoft/applicationinsights/smoketestapp/TestController.java, smoke-tests/apps/TelemetryProcessors/src/smokeTest/java/com/microsoft/applicationinsights/smoketest/TelemetryProcessorsTest.java, smoke-tests/apps/TelemetryProcessors/src/smokeTest/resources/applicationinsights.json
Add tests for Telemetry processor attribute masking and ability to mask an attribute without a group name
=> Add tests for Telemetry processor attribute masking and ability to mask an attribute without a group name

agent/agent-tooling/src/main/java/com/microsoft/applicationinsights/agent/internal/configuration/Configuration.java, agent/agent-tooling/src/main/java/com/microsoft/applicationinsights/agent/internal/init/AiConfigCustomizer.java
TODO statsbeat and public docs
=> Add r2dbc preview instrumentation

agent/agent-tooling/src/main/java/com/microsoft/applicationinsights/agent/internal/diagnostics/DiagnosticsHelper.java, agent/instrumentation/azure-functions/src/main/java/io/opentelemetry/javaagent/instrumentation/azurefunctions/FunctionEnvironmentReloadInstrumentation.java
=> Fix azure functions consumption initialization

.github/dependabot.yml
=> Ignore dependabot for uk.org.webcompere:system-stubs-jupiter

agent/agent/build.gradle.kts, agent/agent/src/main/java/com/microsoft/applicationinsights/agent/Agent.java
https://msazure.visualstudio.com/One/_workitems/edit/24411060
=> Add warning when run as application instead of using -javaagent

buildscripts/dependency-check-suppressions.xml
=> Suppress CVE false positive

agent/agent-bootstrap/src/main/java/io/opentelemetry/instrumentation/api/instrumenter/InstrumenterBuilder.java
(maintaining this copy continues to be a risk)
=> Update copy of InstrumenterBuilder

smoke-tests/apps/Sampling/src/main/java/com/microsoft/applicationinsights/smoketestapp/NoSamplingServlet.java, smoke-tests/apps/Sampling/src/smokeTest/java/com/microsoft/applicationinsights/smoketest/NoSamplingTest.java, smoke-tests/apps/Sampling/src/smokeTest/resources/applicationinsights-no-sampling.json
investigating this icm: https://portal.microsofticm.com/imp/v3/incidents/incident/442738458/summary
confirmed itemCount = 1 always.
=> Add a smoke test for no sampling

agent/agent-tooling/src/main/java/com/microsoft/applicationinsights/agent/internal/init/AppInsightsCertificate.java
=> Change the log level for an issue with the certificate diagnostic

.github/workflows/build-common.yml, .github/workflows/release.yml
=> Fix set-output

dependencyManagement/build.gradle.kts
https://github.com/microsoft/ApplicationInsights-Java/pull/3609
=> Remove the workaround since azure-identity 1.11.4 contains the fix

.github/CODEOWNERS
Adding myself as owner to this repo.
=> Adding myself as owner

smoke-tests/apps/Sampling/src/smokeTest/java/com/microsoft/applicationinsights/smoketest/IngestionSamplingTest.java, smoke-tests/apps/Sampling/src/smokeTest/java/com/microsoft/applicationinsights/smoketest/SamplingTest.java, smoke-tests/apps/SamplingOverrides/src/smokeTest/java/com/microsoft/applicationinsights/smoketest/ExceptionWithSamplingOverridesTest.java, smoke-tests/apps/SamplingOverrides/src/smokeTest/java/com/microsoft/applicationinsights/smoketest/ExceptionWithoutSamplingOverridesTest.java, smoke-tests/apps/SamplingOverrides/src/smokeTest/java/com/microsoft/applicationinsights/smoketest/SamplingOverrides2Test.java, smoke-tests/apps/SamplingOverrides/src/smokeTest/java/com/microsoft/applicationinsights/smoketest/SamplingOverridesOldSemconvTest.java, smoke-tests/apps/SamplingOverrides/src/smokeTest/java/com/microsoft/applicationinsights/smoketest/SamplingOverridesTest.java, smoke-tests/apps/SamplingOverrides/src/smokeTest/java/com/microsoft/applicationinsights/smoketest/SamplingOverridesThreadName.java, smoke-tests/apps/SamplingOverrides/src/smokeTest/java/com/microsoft/applicationinsights/smoketest/UrlQuerySamplingOverridesTest.java, smoke-tests/framework/src/main/java/com/microsoft/applicationinsights/smoketest/EnvironmentValue.java
added environment TOMCAT_8_JAVA_21 for  sampling test case
=> feat: added java 21 tomcat 8 test for sampling

agent/agent-tooling/src/main/java/com/microsoft/applicationinsights/agent/internal/configuration/Configuration.java
=> Fail if HTTP status code used in sampling override

smoke-tests/apps/ConnectionStringOverrides/src/main/java/com/microsoft/applicationinsights/smoketestapp/ConnectionStringOverridesServlet.java, smoke-tests/apps/ConnectionStringOverrides/src/smokeTest/java/com/microsoft/applicationinsights/smoketest/ConnectionStringOverridesTest.java, smoke-tests/apps/DetectUnexpectedOtelMetrics/src/main/java/com/microsoft/applicationinsights/smoketestapp/DetectUnexpectedOtelMetricsServlet.java, smoke-tests/apps/HttpClients/src/main/java/com/microsoft/applicationinsights/smoketestapp/HttpClientServlet.java, smoke-tests/apps/HttpClients/src/smokeTest/java/com/microsoft/applicationinsights/smoketest/HttpClientTest.java, smoke-tests/apps/HttpHeaders/src/main/java/com/microsoft/applicationinsights/smoketestapp/TestController.java, smoke-tests/apps/HttpPreaggregatedMetrics/src/main/java/com/microsoft/applicationinsights/smoketestapp/HttpPreaggregatedMetricsServlet.java, smoke-tests/apps/HttpPreaggregatedMetrics/src/smokeTest/java/com/microsoft/applicationinsights/smoketest/HttpPreaggregatedMetricsTest.java, smoke-tests/apps/InstrumentationKeyOverrides/src/main/java/com/microsoft/applicationinsights/smoketestapp/InstrumentationKeyOverridesServlet.java, smoke-tests/apps/InstrumentationKeyOverrides/src/smokeTest/java/com/microsoft/applicationinsights/smoketest/InstrumentationKeyOverridesTest.java, smoke-tests/apps/OtelResourceCustomMetric/src/main/java/com/microsoft/applicationinsights/smoketestapp/OtelResourceCustomMetric.java, smoke-tests/apps/PreAggMetricsWithRoleNameOverridesAndSampling/src/main/java/com/microsoft/applicationinsights/smoketestapp/PreAggMetricsWithRoleNameOverridesAndSamplingServlet.java, smoke-tests/apps/PreAggMetricsWithRoleNameOverridesAndSampling/src/smokeTest/java/com/microsoft/applicationinsights/smoketest/PreAggMetricsWithRoleNameOverridesAndSamplingTest.java, smoke-tests/apps/RoleNameOverrides/src/main/java/com/microsoft/applicationinsights/smoketestapp/RoleNameOverridesServlet.java, smoke-tests/apps/RoleNameOverrides/src/smokeTest/java/com/microsoft/applicationinsights/smoketest/RoleNameOverridesTest.java, smoke-tests/framework/src/main/java/com/microsoft/applicationinsights/smoketest/fakeingestion/MockedAppInsightsIngestionServlet.java
https://mock.codes site has been failing from time to time
=> Fix sporadic CI failures

agent/agent-tooling/src/main/java/com/microsoft/applicationinsights/agent/internal/configuration/ConfigurationBuilder.java, agent/agent-tooling/src/test/java/com/microsoft/applicationinsights/agent/internal/configuration/ConfigurationBuilderTest.java
Fix https://github.com/microsoft/ApplicationInsights-Java/issues/3707
replaced #3759
regression from https://github.com/microsoft/ApplicationInsights-Java/pull/3471
=> Check connection string env var before loading from a file

buildscripts/dependency-check-suppressions.xml
Running owasp action on this branch: https://github.com/microsoft/ApplicationInsights-Java/actions/runs/10085004115
=> Suppress owasp false positive

CHANGELOG.md
https://github.com/microsoft/ApplicationInsights-Java/pull/3805#discussion_r1691768785
i resolved comment and forgot to merge the proposed changes.
=> Update changelog per comment

.github/workflows/reusable-create-docs-pull-request.yml
AARON_MAXWELL_TOKEN has been updated accordingly to reflect the update.
cc @AaronMaxwell
=> Update `azure-docs-pr` to `azure-monitor-docs-pr`

agent/agent-tooling/build.gradle.kts
=> Remove azure-json pin

agent/agent-tooling/build.gradle.kts, agent/agent/build.gradle.kts, licenses/more-licenses.md
=> Bump azure-identity to 1.15.2 and json-smart to 2.5.2

.github/workflows/build-common.yml
Matrix out each test to reduce build duration.
=> Faster smoke tests

agent/agent-gc-monitor/gc-monitor-core/src/main/java/com/microsoft/gcmonitor/collectors/GcCollectionSample.java, agent/agent-gc-monitor/gc-monitor-core/src/main/java/com/microsoft/gcmonitor/notifications/NotificationObserver.java, agent/agent-profiler/agent-alerting/src/main/java/com/microsoft/applicationinsights/alerting/AlertingSubsystem.java, agent/agent-profiler/agent-alerting/src/main/java/com/microsoft/applicationinsights/alerting/analysis/pipelines/AlertPipelines.java, agent/agent-profiler/agent-alerting/src/main/java/com/microsoft/applicationinsights/alerting/analysis/pipelines/SingleAlertPipeline.java, agent/agent-profiler/agent-diagnostics/src/main/java/com/microsoft/applicationinsights/diagnostics/appinsights/CodeOptimizerDiagnosticEngineJfr.java, agent/agent-profiler/agent-diagnostics/src/main/java/com/microsoft/applicationinsights/diagnostics/collection/calibration/CalibratorDefault.java, agent/agent-profiler/agent-diagnostics/src/main/java/com/microsoft/applicationinsights/diagnostics/collection/libos/os/OperatingSystemDetector.java, agent/agent-profiler/agent-diagnostics/src/main/java/com/microsoft/applicationinsights/diagnostics/collection/libos/os/linux/LinuxProcessCpuStats.java, agent/agent-profiler/agent-diagnostics/src/main/java/com/microsoft/applicationinsights/diagnostics/collection/libos/os/linux/LinuxProcessDumper.java, agent/agent-profiler/agent-diagnostics/src/main/java/com/microsoft/applicationinsights/diagnostics/collection/libos/os/linux/LinuxProcessIoStats.java, agent/agent-profiler/agent-diagnostics/src/main/java/com/microsoft/applicationinsights/diagnostics/collection/libos/os/linux/TwoStepProcReader.java, agent/agent-profiler/agent-diagnostics/src/main/java/com/microsoft/applicationinsights/diagnostics/jfr/CodeOptimizerDiagnosticsJfrInit.java, agent/agent-profiler/agent-diagnostics/src/main/java/com/microsoft/applicationinsights/diagnostics/jfr/SystemStatsProvider.java, agent/agent-tooling/src/main/java/com/microsoft/applicationinsights/agent/internal/classicsdk/TelemetryClientClassFileTransformer.java, agent/agent-tooling/src/main/java/com/microsoft/applicationinsights/agent/internal/configuration/SnippetConfiguration.java, agent/agent-tooling/src/test/java/com/microsoft/applicationinsights/agent/internal/init/InheritedAttributesSpanProcessorTest.java, agent/agent/src/devtest/java/com/microsoft/applicationinsights/agent/bootstrap/diagnostics/etw/DiagnosticsLoggerProxy.java, buildscripts/checkstyle.xml, etw/java/src/main/java/com/microsoft/applicationinsights/agent/internal/diagnostics/etw/DllFileUtils.java, etw/java/src/main/jni/com/microsoft/applicationinsights/agent/internal/diagnostics/etw/EtwProvider.java
Upstream file: https://github.com/open-telemetry/opentelemetry-java-instrumentation/blob/main/buildscripts/checkstyle.xml
=> Sync checkstyle configuration with OpenTelemetry Java Instrumentation

.github/workflows/copilot-setup-steps.yml
This was just fixed in copilot itself!
https://github.blog/changelog/2025-07-30-copilot-coding-agent-custom-setup-steps-are-more-reliable-and-easier-to-debug/
=> Revert "Fix copilot setup steps (#4402)"
